// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrysm/v1alpha1/validator-client/web_api.proto

package validatorpb

import (
	context "context"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Deprecated: Marked as deprecated in proto/qrysm/v1alpha1/validator-client/web_api.proto.
type KeymanagerKind int32

const (
	KeymanagerKind_DERIVED    KeymanagerKind = 0
	KeymanagerKind_IMPORTED   KeymanagerKind = 1
	KeymanagerKind_REMOTE     KeymanagerKind = 2
	KeymanagerKind_WEB3SIGNER KeymanagerKind = 3
)

// Enum value maps for KeymanagerKind.
var (
	KeymanagerKind_name = map[int32]string{
		0: "DERIVED",
		1: "IMPORTED",
		2: "REMOTE",
		3: "WEB3SIGNER",
	}
	KeymanagerKind_value = map[string]int32{
		"DERIVED":    0,
		"IMPORTED":   1,
		"REMOTE":     2,
		"WEB3SIGNER": 3,
	}
)

func (x KeymanagerKind) Enum() *KeymanagerKind {
	p := new(KeymanagerKind)
	*p = x
	return p
}

func (x KeymanagerKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KeymanagerKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_qrysm_v1alpha1_validator_client_web_api_proto_enumTypes[0].Descriptor()
}

func (KeymanagerKind) Type() protoreflect.EnumType {
	return &file_proto_qrysm_v1alpha1_validator_client_web_api_proto_enumTypes[0]
}

func (x KeymanagerKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KeymanagerKind.Descriptor instead.
func (KeymanagerKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescGZIP(), []int{0}
}

// Deprecated: Marked as deprecated in proto/qrysm/v1alpha1/validator-client/web_api.proto.
type ExportSlashingProtectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          string                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportSlashingProtectionResponse) Reset() {
	*x = ExportSlashingProtectionResponse{}
	mi := &file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSlashingProtectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSlashingProtectionResponse) ProtoMessage() {}

func (x *ExportSlashingProtectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSlashingProtectionResponse.ProtoReflect.Descriptor instead.
func (*ExportSlashingProtectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescGZIP(), []int{0}
}

func (x *ExportSlashingProtectionResponse) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

// Deprecated: Marked as deprecated in proto/qrysm/v1alpha1/validator-client/web_api.proto.
type ImportSlashingProtectionRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SlashingProtectionJson string                 `protobuf:"bytes,1,opt,name=slashing_protection_json,json=slashingProtectionJson,proto3" json:"slashing_protection_json,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ImportSlashingProtectionRequest) Reset() {
	*x = ImportSlashingProtectionRequest{}
	mi := &file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportSlashingProtectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportSlashingProtectionRequest) ProtoMessage() {}

func (x *ImportSlashingProtectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportSlashingProtectionRequest.ProtoReflect.Descriptor instead.
func (*ImportSlashingProtectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescGZIP(), []int{1}
}

func (x *ImportSlashingProtectionRequest) GetSlashingProtectionJson() string {
	if x != nil {
		return x.SlashingProtectionJson
	}
	return ""
}

var File_proto_qrysm_v1alpha1_validator_client_web_api_proto protoreflect.FileDescriptor

const file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDesc = "" +
	"\n" +
	"3proto/qrysm/v1alpha1/validator-client/web_api.proto\x12\x1ctheqrl.validator.accounts.v2\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\":\n" +
	" ExportSlashingProtectionResponse\x12\x12\n" +
	"\x04file\x18\x01 \x01(\tR\x04file:\x02\x18\x01\"_\n" +
	"\x1fImportSlashingProtectionRequest\x128\n" +
	"\x18slashing_protection_json\x18\x01 \x01(\tR\x16slashingProtectionJson:\x02\x18\x01*K\n" +
	"\x0eKeymanagerKind\x12\v\n" +
	"\aDERIVED\x10\x00\x12\f\n" +
	"\bIMPORTED\x10\x01\x12\n" +
	"\n" +
	"\x06REMOTE\x10\x02\x12\x0e\n" +
	"\n" +
	"WEB3SIGNER\x10\x03\x1a\x02\x18\x012\xea\x02\n" +
	"\x12SlashingProtection\x12\xa7\x01\n" +
	"\x18ExportSlashingProtection\x12\x16.google.protobuf.Empty\x1a>.theqrl.validator.accounts.v2.ExportSlashingProtectionResponse\"3\x82\xd3\xe4\x93\x02*\x12(/v2/validator/slashing-protection/export\x88\x02\x01\x12\xa9\x01\n" +
	"\x18ImportSlashingProtection\x12=.theqrl.validator.accounts.v2.ImportSlashingProtectionRequest\x1a\x16.google.protobuf.Empty\"6\x82\xd3\xe4\x93\x02-:\x01*\"(/v2/validator/slashing-protection/import\x88\x02\x01B\xb7\x01\n" +
	" org.theqrl.validator.accounts.v2B\bWebProtoP\x01ZIgithub.com/theQRL/qrysm/proto/qrysm/v1alpha1/validator-client;validatorpb\xaa\x02\x1cTheQRL.Validator.Accounts.V2\xca\x02\x1cTheQRL\\Validator\\Accounts\\V2b\x06proto3"

var (
	file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescOnce sync.Once
	file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescData []byte
)

func file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescGZIP() []byte {
	file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescOnce.Do(func() {
		file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDesc), len(file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDesc)))
	})
	return file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDescData
}

var file_proto_qrysm_v1alpha1_validator_client_web_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_qrysm_v1alpha1_validator_client_web_api_proto_goTypes = []any{
	(KeymanagerKind)(0),                      // 0: theqrl.validator.accounts.v2.KeymanagerKind
	(*ExportSlashingProtectionResponse)(nil), // 1: theqrl.validator.accounts.v2.ExportSlashingProtectionResponse
	(*ImportSlashingProtectionRequest)(nil),  // 2: theqrl.validator.accounts.v2.ImportSlashingProtectionRequest
	(*emptypb.Empty)(nil),                    // 3: google.protobuf.Empty
}
var file_proto_qrysm_v1alpha1_validator_client_web_api_proto_depIdxs = []int32{
	3, // 0: theqrl.validator.accounts.v2.SlashingProtection.ExportSlashingProtection:input_type -> google.protobuf.Empty
	2, // 1: theqrl.validator.accounts.v2.SlashingProtection.ImportSlashingProtection:input_type -> theqrl.validator.accounts.v2.ImportSlashingProtectionRequest
	1, // 2: theqrl.validator.accounts.v2.SlashingProtection.ExportSlashingProtection:output_type -> theqrl.validator.accounts.v2.ExportSlashingProtectionResponse
	3, // 3: theqrl.validator.accounts.v2.SlashingProtection.ImportSlashingProtection:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_qrysm_v1alpha1_validator_client_web_api_proto_init() }
func file_proto_qrysm_v1alpha1_validator_client_web_api_proto_init() {
	if File_proto_qrysm_v1alpha1_validator_client_web_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDesc), len(file_proto_qrysm_v1alpha1_validator_client_web_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_qrysm_v1alpha1_validator_client_web_api_proto_goTypes,
		DependencyIndexes: file_proto_qrysm_v1alpha1_validator_client_web_api_proto_depIdxs,
		EnumInfos:         file_proto_qrysm_v1alpha1_validator_client_web_api_proto_enumTypes,
		MessageInfos:      file_proto_qrysm_v1alpha1_validator_client_web_api_proto_msgTypes,
	}.Build()
	File_proto_qrysm_v1alpha1_validator_client_web_api_proto = out.File
	file_proto_qrysm_v1alpha1_validator_client_web_api_proto_goTypes = nil
	file_proto_qrysm_v1alpha1_validator_client_web_api_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SlashingProtectionClient is the client API for SlashingProtection service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SlashingProtectionClient interface {
	// Deprecated: Do not use.
	ExportSlashingProtection(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ExportSlashingProtectionResponse, error)
	// Deprecated: Do not use.
	ImportSlashingProtection(ctx context.Context, in *ImportSlashingProtectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type slashingProtectionClient struct {
	cc grpc.ClientConnInterface
}

func NewSlashingProtectionClient(cc grpc.ClientConnInterface) SlashingProtectionClient {
	return &slashingProtectionClient{cc}
}

// Deprecated: Do not use.
func (c *slashingProtectionClient) ExportSlashingProtection(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ExportSlashingProtectionResponse, error) {
	out := new(ExportSlashingProtectionResponse)
	err := c.cc.Invoke(ctx, "/theqrl.validator.accounts.v2.SlashingProtection/ExportSlashingProtection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *slashingProtectionClient) ImportSlashingProtection(ctx context.Context, in *ImportSlashingProtectionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/theqrl.validator.accounts.v2.SlashingProtection/ImportSlashingProtection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SlashingProtectionServer is the server API for SlashingProtection service.
type SlashingProtectionServer interface {
	// Deprecated: Do not use.
	ExportSlashingProtection(context.Context, *emptypb.Empty) (*ExportSlashingProtectionResponse, error)
	// Deprecated: Do not use.
	ImportSlashingProtection(context.Context, *ImportSlashingProtectionRequest) (*emptypb.Empty, error)
}

// UnimplementedSlashingProtectionServer can be embedded to have forward compatible implementations.
type UnimplementedSlashingProtectionServer struct {
}

func (*UnimplementedSlashingProtectionServer) ExportSlashingProtection(context.Context, *emptypb.Empty) (*ExportSlashingProtectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportSlashingProtection not implemented")
}
func (*UnimplementedSlashingProtectionServer) ImportSlashingProtection(context.Context, *ImportSlashingProtectionRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportSlashingProtection not implemented")
}

func RegisterSlashingProtectionServer(s *grpc.Server, srv SlashingProtectionServer) {
	s.RegisterService(&_SlashingProtection_serviceDesc, srv)
}

func _SlashingProtection_ExportSlashingProtection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlashingProtectionServer).ExportSlashingProtection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.validator.accounts.v2.SlashingProtection/ExportSlashingProtection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlashingProtectionServer).ExportSlashingProtection(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SlashingProtection_ImportSlashingProtection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSlashingProtectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SlashingProtectionServer).ImportSlashingProtection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.validator.accounts.v2.SlashingProtection/ImportSlashingProtection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SlashingProtectionServer).ImportSlashingProtection(ctx, req.(*ImportSlashingProtectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SlashingProtection_serviceDesc = grpc.ServiceDesc{
	ServiceName: "theqrl.validator.accounts.v2.SlashingProtection",
	HandlerType: (*SlashingProtectionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExportSlashingProtection",
			Handler:    _SlashingProtection_ExportSlashingProtection_Handler,
		},
		{
			MethodName: "ImportSlashingProtection",
			Handler:    _SlashingProtection_ImportSlashingProtection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/qrysm/v1alpha1/validator-client/web_api.proto",
}
