// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrl/service/beacon_debug_service.proto

package service

import (
	context "context"
	reflect "reflect"
	unsafe "unsafe"

	v1 "github.com/theQRL/qrysm/proto/qrl/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_qrl_service_beacon_debug_service_proto protoreflect.FileDescriptor

const file_proto_qrl_service_beacon_debug_service_proto_rawDesc = "" +
	"\n" +
	",proto/qrl/service/beacon_debug_service.proto\x12\x12theqrl.qrl.service\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fproto/qrl/v1/beacon_chain.proto\x1a\x1fproto/qrl/v1/beacon_state.proto\x1a\x16proto/qrl/v1/ssz.proto2\xac\x04\n" +
	"\vBeaconDebug\x12\x90\x01\n" +
	"\x0eGetBeaconState\x12!.theqrl.qrl.v1.BeaconStateRequest\x1a\".theqrl.qrl.v1.BeaconStateResponse\"7\x82\xd3\xe4\x93\x021\x12//internal/qrl/v1/debug/beacon/states/{state_id}\x12\x90\x01\n" +
	"\x11GetBeaconStateSSZ\x12!.theqrl.qrl.v1.BeaconStateRequest\x1a\x1b.theqrl.qrl.v1.SSZContainer\";\x82\xd3\xe4\x93\x025\x123/internal/qrl/v1/debug/beacon/states/{state_id}/ssz\x12\x82\x01\n" +
	"\x13ListForkChoiceHeads\x12\x16.google.protobuf.Empty\x1a&.theqrl.qrl.v1.ForkChoiceHeadsResponse\"+\x82\xd3\xe4\x93\x02%\x12#/internal/qrl/v1/debug/beacon/heads\x12r\n" +
	"\rGetForkChoice\x12\x16.google.protobuf.Empty\x1a\x1d.theqrl.qrl.v1.ForkChoiceDump\"*\x82\xd3\xe4\x93\x02$\x12\"/internal/qrl/v1/debug/fork_choiceB\x88\x01\n" +
	"\x16org.theqrl.qrl.serviceB\x17BeaconDebugServiceProtoP\x01Z)github.com/theQRL/qrysm/proto/qrl/service\xaa\x02\x12TheQRL.QRL.Service\xca\x02\x12TheQRL\\QRL\\Serviceb\x06proto3"

var file_proto_qrl_service_beacon_debug_service_proto_goTypes = []any{
	(*v1.BeaconStateRequest)(nil),      // 0: theqrl.qrl.v1.BeaconStateRequest
	(*emptypb.Empty)(nil),              // 1: google.protobuf.Empty
	(*v1.BeaconStateResponse)(nil),     // 2: theqrl.qrl.v1.BeaconStateResponse
	(*v1.SSZContainer)(nil),            // 3: theqrl.qrl.v1.SSZContainer
	(*v1.ForkChoiceHeadsResponse)(nil), // 4: theqrl.qrl.v1.ForkChoiceHeadsResponse
	(*v1.ForkChoiceDump)(nil),          // 5: theqrl.qrl.v1.ForkChoiceDump
}
var file_proto_qrl_service_beacon_debug_service_proto_depIdxs = []int32{
	0, // 0: theqrl.qrl.service.BeaconDebug.GetBeaconState:input_type -> theqrl.qrl.v1.BeaconStateRequest
	0, // 1: theqrl.qrl.service.BeaconDebug.GetBeaconStateSSZ:input_type -> theqrl.qrl.v1.BeaconStateRequest
	1, // 2: theqrl.qrl.service.BeaconDebug.ListForkChoiceHeads:input_type -> google.protobuf.Empty
	1, // 3: theqrl.qrl.service.BeaconDebug.GetForkChoice:input_type -> google.protobuf.Empty
	2, // 4: theqrl.qrl.service.BeaconDebug.GetBeaconState:output_type -> theqrl.qrl.v1.BeaconStateResponse
	3, // 5: theqrl.qrl.service.BeaconDebug.GetBeaconStateSSZ:output_type -> theqrl.qrl.v1.SSZContainer
	4, // 6: theqrl.qrl.service.BeaconDebug.ListForkChoiceHeads:output_type -> theqrl.qrl.v1.ForkChoiceHeadsResponse
	5, // 7: theqrl.qrl.service.BeaconDebug.GetForkChoice:output_type -> theqrl.qrl.v1.ForkChoiceDump
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_qrl_service_beacon_debug_service_proto_init() }
func file_proto_qrl_service_beacon_debug_service_proto_init() {
	if File_proto_qrl_service_beacon_debug_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrl_service_beacon_debug_service_proto_rawDesc), len(file_proto_qrl_service_beacon_debug_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_qrl_service_beacon_debug_service_proto_goTypes,
		DependencyIndexes: file_proto_qrl_service_beacon_debug_service_proto_depIdxs,
	}.Build()
	File_proto_qrl_service_beacon_debug_service_proto = out.File
	file_proto_qrl_service_beacon_debug_service_proto_goTypes = nil
	file_proto_qrl_service_beacon_debug_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BeaconDebugClient is the client API for BeaconDebug service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BeaconDebugClient interface {
	GetBeaconState(ctx context.Context, in *v1.BeaconStateRequest, opts ...grpc.CallOption) (*v1.BeaconStateResponse, error)
	GetBeaconStateSSZ(ctx context.Context, in *v1.BeaconStateRequest, opts ...grpc.CallOption) (*v1.SSZContainer, error)
	ListForkChoiceHeads(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*v1.ForkChoiceHeadsResponse, error)
	GetForkChoice(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*v1.ForkChoiceDump, error)
}

type beaconDebugClient struct {
	cc grpc.ClientConnInterface
}

func NewBeaconDebugClient(cc grpc.ClientConnInterface) BeaconDebugClient {
	return &beaconDebugClient{cc}
}

func (c *beaconDebugClient) GetBeaconState(ctx context.Context, in *v1.BeaconStateRequest, opts ...grpc.CallOption) (*v1.BeaconStateResponse, error) {
	out := new(v1.BeaconStateResponse)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.BeaconDebug/GetBeaconState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconDebugClient) GetBeaconStateSSZ(ctx context.Context, in *v1.BeaconStateRequest, opts ...grpc.CallOption) (*v1.SSZContainer, error) {
	out := new(v1.SSZContainer)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.BeaconDebug/GetBeaconStateSSZ", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconDebugClient) ListForkChoiceHeads(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*v1.ForkChoiceHeadsResponse, error) {
	out := new(v1.ForkChoiceHeadsResponse)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.BeaconDebug/ListForkChoiceHeads", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconDebugClient) GetForkChoice(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*v1.ForkChoiceDump, error) {
	out := new(v1.ForkChoiceDump)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.BeaconDebug/GetForkChoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeaconDebugServer is the server API for BeaconDebug service.
type BeaconDebugServer interface {
	GetBeaconState(context.Context, *v1.BeaconStateRequest) (*v1.BeaconStateResponse, error)
	GetBeaconStateSSZ(context.Context, *v1.BeaconStateRequest) (*v1.SSZContainer, error)
	ListForkChoiceHeads(context.Context, *emptypb.Empty) (*v1.ForkChoiceHeadsResponse, error)
	GetForkChoice(context.Context, *emptypb.Empty) (*v1.ForkChoiceDump, error)
}

// UnimplementedBeaconDebugServer can be embedded to have forward compatible implementations.
type UnimplementedBeaconDebugServer struct {
}

func (*UnimplementedBeaconDebugServer) GetBeaconState(context.Context, *v1.BeaconStateRequest) (*v1.BeaconStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBeaconState not implemented")
}
func (*UnimplementedBeaconDebugServer) GetBeaconStateSSZ(context.Context, *v1.BeaconStateRequest) (*v1.SSZContainer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBeaconStateSSZ not implemented")
}
func (*UnimplementedBeaconDebugServer) ListForkChoiceHeads(context.Context, *emptypb.Empty) (*v1.ForkChoiceHeadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListForkChoiceHeads not implemented")
}
func (*UnimplementedBeaconDebugServer) GetForkChoice(context.Context, *emptypb.Empty) (*v1.ForkChoiceDump, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForkChoice not implemented")
}

func RegisterBeaconDebugServer(s *grpc.Server, srv BeaconDebugServer) {
	s.RegisterService(&_BeaconDebug_serviceDesc, srv)
}

func _BeaconDebug_GetBeaconState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.BeaconStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconDebugServer).GetBeaconState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.BeaconDebug/GetBeaconState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconDebugServer).GetBeaconState(ctx, req.(*v1.BeaconStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconDebug_GetBeaconStateSSZ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.BeaconStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconDebugServer).GetBeaconStateSSZ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.BeaconDebug/GetBeaconStateSSZ",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconDebugServer).GetBeaconStateSSZ(ctx, req.(*v1.BeaconStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconDebug_ListForkChoiceHeads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconDebugServer).ListForkChoiceHeads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.BeaconDebug/ListForkChoiceHeads",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconDebugServer).ListForkChoiceHeads(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconDebug_GetForkChoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconDebugServer).GetForkChoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.BeaconDebug/GetForkChoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconDebugServer).GetForkChoice(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _BeaconDebug_serviceDesc = grpc.ServiceDesc{
	ServiceName: "theqrl.qrl.service.BeaconDebug",
	HandlerType: (*BeaconDebugServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBeaconState",
			Handler:    _BeaconDebug_GetBeaconState_Handler,
		},
		{
			MethodName: "GetBeaconStateSSZ",
			Handler:    _BeaconDebug_GetBeaconStateSSZ_Handler,
		},
		{
			MethodName: "ListForkChoiceHeads",
			Handler:    _BeaconDebug_ListForkChoiceHeads_Handler,
		},
		{
			MethodName: "GetForkChoice",
			Handler:    _BeaconDebug_GetForkChoice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/qrl/service/beacon_debug_service.proto",
}
