// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrl/service/events_service.proto

package service

import (
	context "context"
	reflect "reflect"
	unsafe "unsafe"

	gateway "github.com/grpc-ecosystem/grpc-gateway/v2/proto/gateway"
	v1 "github.com/theQRL/qrysm/proto/qrl/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_qrl_service_events_service_proto protoreflect.FileDescriptor

const file_proto_qrl_service_events_service_proto_rawDesc = "" +
	"\n" +
	"&proto/qrl/service/events_service.proto\x12\x12theqrl.qrl.service\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\x1a\x19proto/qrl/v1/events.proto\x1a proto/gateway/event_source.proto2u\n" +
	"\x06Events\x12k\n" +
	"\fStreamEvents\x12\".theqrl.qrl.v1.StreamEventsRequest\x1a\x14.gateway.EventSource\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/internal/qrl/v1/events0\x01B\x83\x01\n" +
	"\x16org.theqrl.qrl.serviceB\x12EventsServiceProtoP\x01Z)github.com/theQRL/qrysm/proto/qrl/service\xaa\x02\x12TheQRL.QRL.Service\xca\x02\x12TheQRL\\QRL\\Serviceb\x06proto3"

var file_proto_qrl_service_events_service_proto_goTypes = []any{
	(*v1.StreamEventsRequest)(nil), // 0: theqrl.qrl.v1.StreamEventsRequest
	(*gateway.EventSource)(nil),    // 1: gateway.EventSource
}
var file_proto_qrl_service_events_service_proto_depIdxs = []int32{
	0, // 0: theqrl.qrl.service.Events.StreamEvents:input_type -> theqrl.qrl.v1.StreamEventsRequest
	1, // 1: theqrl.qrl.service.Events.StreamEvents:output_type -> gateway.EventSource
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_qrl_service_events_service_proto_init() }
func file_proto_qrl_service_events_service_proto_init() {
	if File_proto_qrl_service_events_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrl_service_events_service_proto_rawDesc), len(file_proto_qrl_service_events_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_qrl_service_events_service_proto_goTypes,
		DependencyIndexes: file_proto_qrl_service_events_service_proto_depIdxs,
	}.Build()
	File_proto_qrl_service_events_service_proto = out.File
	file_proto_qrl_service_events_service_proto_goTypes = nil
	file_proto_qrl_service_events_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EventsClient is the client API for Events service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EventsClient interface {
	StreamEvents(ctx context.Context, in *v1.StreamEventsRequest, opts ...grpc.CallOption) (Events_StreamEventsClient, error)
}

type eventsClient struct {
	cc grpc.ClientConnInterface
}

func NewEventsClient(cc grpc.ClientConnInterface) EventsClient {
	return &eventsClient{cc}
}

func (c *eventsClient) StreamEvents(ctx context.Context, in *v1.StreamEventsRequest, opts ...grpc.CallOption) (Events_StreamEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Events_serviceDesc.Streams[0], "/theqrl.qrl.service.Events/StreamEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &eventsStreamEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Events_StreamEventsClient interface {
	Recv() (*gateway.EventSource, error)
	grpc.ClientStream
}

type eventsStreamEventsClient struct {
	grpc.ClientStream
}

func (x *eventsStreamEventsClient) Recv() (*gateway.EventSource, error) {
	m := new(gateway.EventSource)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EventsServer is the server API for Events service.
type EventsServer interface {
	StreamEvents(*v1.StreamEventsRequest, Events_StreamEventsServer) error
}

// UnimplementedEventsServer can be embedded to have forward compatible implementations.
type UnimplementedEventsServer struct {
}

func (*UnimplementedEventsServer) StreamEvents(*v1.StreamEventsRequest, Events_StreamEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}

func RegisterEventsServer(s *grpc.Server, srv EventsServer) {
	s.RegisterService(&_Events_serviceDesc, srv)
}

func _Events_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(v1.StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventsServer).StreamEvents(m, &eventsStreamEventsServer{stream})
}

type Events_StreamEventsServer interface {
	Send(*gateway.EventSource) error
	grpc.ServerStream
}

type eventsStreamEventsServer struct {
	grpc.ServerStream
}

func (x *eventsStreamEventsServer) Send(m *gateway.EventSource) error {
	return x.ServerStream.SendMsg(m)
}

var _Events_serviceDesc = grpc.ServiceDesc{
	ServiceName: "theqrl.qrl.service.Events",
	HandlerType: (*EventsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _Events_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/qrl/service/events_service.proto",
}
