// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrl/service/key_management.proto

package service

import (
	context "context"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_qrysm_consensus_types_primitives "github.com/theQRL/qrysm/consensus-types/primitives"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportedKeystoreStatus_Status int32

const (
	ImportedKeystoreStatus_IMPORTED  ImportedKeystoreStatus_Status = 0
	ImportedKeystoreStatus_DUPLICATE ImportedKeystoreStatus_Status = 1
	ImportedKeystoreStatus_ERROR     ImportedKeystoreStatus_Status = 2
)

// Enum value maps for ImportedKeystoreStatus_Status.
var (
	ImportedKeystoreStatus_Status_name = map[int32]string{
		0: "IMPORTED",
		1: "DUPLICATE",
		2: "ERROR",
	}
	ImportedKeystoreStatus_Status_value = map[string]int32{
		"IMPORTED":  0,
		"DUPLICATE": 1,
		"ERROR":     2,
	}
)

func (x ImportedKeystoreStatus_Status) Enum() *ImportedKeystoreStatus_Status {
	p := new(ImportedKeystoreStatus_Status)
	*p = x
	return p
}

func (x ImportedKeystoreStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImportedKeystoreStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_qrl_service_key_management_proto_enumTypes[0].Descriptor()
}

func (ImportedKeystoreStatus_Status) Type() protoreflect.EnumType {
	return &file_proto_qrl_service_key_management_proto_enumTypes[0]
}

func (x ImportedKeystoreStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImportedKeystoreStatus_Status.Descriptor instead.
func (ImportedKeystoreStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{5, 0}
}

type DeletedKeystoreStatus_Status int32

const (
	DeletedKeystoreStatus_DELETED    DeletedKeystoreStatus_Status = 0
	DeletedKeystoreStatus_NOT_FOUND  DeletedKeystoreStatus_Status = 1
	DeletedKeystoreStatus_NOT_ACTIVE DeletedKeystoreStatus_Status = 2
	DeletedKeystoreStatus_ERROR      DeletedKeystoreStatus_Status = 3
)

// Enum value maps for DeletedKeystoreStatus_Status.
var (
	DeletedKeystoreStatus_Status_name = map[int32]string{
		0: "DELETED",
		1: "NOT_FOUND",
		2: "NOT_ACTIVE",
		3: "ERROR",
	}
	DeletedKeystoreStatus_Status_value = map[string]int32{
		"DELETED":    0,
		"NOT_FOUND":  1,
		"NOT_ACTIVE": 2,
		"ERROR":      3,
	}
)

func (x DeletedKeystoreStatus_Status) Enum() *DeletedKeystoreStatus_Status {
	p := new(DeletedKeystoreStatus_Status)
	*p = x
	return p
}

func (x DeletedKeystoreStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeletedKeystoreStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_qrl_service_key_management_proto_enumTypes[1].Descriptor()
}

func (DeletedKeystoreStatus_Status) Type() protoreflect.EnumType {
	return &file_proto_qrl_service_key_management_proto_enumTypes[1]
}

func (x DeletedKeystoreStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeletedKeystoreStatus_Status.Descriptor instead.
func (DeletedKeystoreStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{6, 0}
}

type ListKeystoresResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Data          []*ListKeystoresResponse_Keystore `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeystoresResponse) Reset() {
	*x = ListKeystoresResponse{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeystoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeystoresResponse) ProtoMessage() {}

func (x *ListKeystoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeystoresResponse.ProtoReflect.Descriptor instead.
func (*ListKeystoresResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{0}
}

func (x *ListKeystoresResponse) GetData() []*ListKeystoresResponse_Keystore {
	if x != nil {
		return x.Data
	}
	return nil
}

type ImportKeystoresRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Keystores          []string               `protobuf:"bytes,1,rep,name=keystores,proto3" json:"keystores,omitempty"`
	Passwords          []string               `protobuf:"bytes,2,rep,name=passwords,proto3" json:"passwords,omitempty"`
	SlashingProtection string                 `protobuf:"bytes,3,opt,name=slashing_protection,json=slashingProtection,proto3" json:"slashing_protection,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ImportKeystoresRequest) Reset() {
	*x = ImportKeystoresRequest{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportKeystoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportKeystoresRequest) ProtoMessage() {}

func (x *ImportKeystoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportKeystoresRequest.ProtoReflect.Descriptor instead.
func (*ImportKeystoresRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{1}
}

func (x *ImportKeystoresRequest) GetKeystores() []string {
	if x != nil {
		return x.Keystores
	}
	return nil
}

func (x *ImportKeystoresRequest) GetPasswords() []string {
	if x != nil {
		return x.Passwords
	}
	return nil
}

func (x *ImportKeystoresRequest) GetSlashingProtection() string {
	if x != nil {
		return x.SlashingProtection
	}
	return ""
}

type ImportKeystoresResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          []*ImportedKeystoreStatus `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportKeystoresResponse) Reset() {
	*x = ImportKeystoresResponse{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportKeystoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportKeystoresResponse) ProtoMessage() {}

func (x *ImportKeystoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportKeystoresResponse.ProtoReflect.Descriptor instead.
func (*ImportKeystoresResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{2}
}

func (x *ImportKeystoresResponse) GetData() []*ImportedKeystoreStatus {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteKeystoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkeys       [][]byte               `protobuf:"bytes,1,rep,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeystoresRequest) Reset() {
	*x = DeleteKeystoresRequest{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeystoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeystoresRequest) ProtoMessage() {}

func (x *DeleteKeystoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeystoresRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeystoresRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteKeystoresRequest) GetPubkeys() [][]byte {
	if x != nil {
		return x.Pubkeys
	}
	return nil
}

type DeleteKeystoresResponse struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	Data               []*DeletedKeystoreStatus `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	SlashingProtection string                   `protobuf:"bytes,2,opt,name=slashing_protection,json=slashingProtection,proto3" json:"slashing_protection,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeleteKeystoresResponse) Reset() {
	*x = DeleteKeystoresResponse{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeystoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeystoresResponse) ProtoMessage() {}

func (x *DeleteKeystoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeystoresResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeystoresResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteKeystoresResponse) GetData() []*DeletedKeystoreStatus {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DeleteKeystoresResponse) GetSlashingProtection() string {
	if x != nil {
		return x.SlashingProtection
	}
	return ""
}

type ImportedKeystoreStatus struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Status        ImportedKeystoreStatus_Status `protobuf:"varint,1,opt,name=status,proto3,enum=theqrl.qrl.service.ImportedKeystoreStatus_Status" json:"status,omitempty"`
	Message       string                        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportedKeystoreStatus) Reset() {
	*x = ImportedKeystoreStatus{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportedKeystoreStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportedKeystoreStatus) ProtoMessage() {}

func (x *ImportedKeystoreStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportedKeystoreStatus.ProtoReflect.Descriptor instead.
func (*ImportedKeystoreStatus) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{5}
}

func (x *ImportedKeystoreStatus) GetStatus() ImportedKeystoreStatus_Status {
	if x != nil {
		return x.Status
	}
	return ImportedKeystoreStatus_IMPORTED
}

func (x *ImportedKeystoreStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeletedKeystoreStatus struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Status        DeletedKeystoreStatus_Status `protobuf:"varint,1,opt,name=status,proto3,enum=theqrl.qrl.service.DeletedKeystoreStatus_Status" json:"status,omitempty"`
	Message       string                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletedKeystoreStatus) Reset() {
	*x = DeletedKeystoreStatus{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletedKeystoreStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedKeystoreStatus) ProtoMessage() {}

func (x *DeletedKeystoreStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedKeystoreStatus.ProtoReflect.Descriptor instead.
func (*DeletedKeystoreStatus) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{6}
}

func (x *DeletedKeystoreStatus) GetStatus() DeletedKeystoreStatus_Status {
	if x != nil {
		return x.Status
	}
	return DeletedKeystoreStatus_DELETED
}

func (x *DeletedKeystoreStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PubkeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubkeyRequest) Reset() {
	*x = PubkeyRequest{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubkeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubkeyRequest) ProtoMessage() {}

func (x *PubkeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubkeyRequest.ProtoReflect.Descriptor instead.
func (*PubkeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{7}
}

func (x *PubkeyRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type GetFeeRecipientByPubkeyResponse struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Data          *GetFeeRecipientByPubkeyResponse_FeeRecipient `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeeRecipientByPubkeyResponse) Reset() {
	*x = GetFeeRecipientByPubkeyResponse{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeeRecipientByPubkeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeeRecipientByPubkeyResponse) ProtoMessage() {}

func (x *GetFeeRecipientByPubkeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeeRecipientByPubkeyResponse.ProtoReflect.Descriptor instead.
func (*GetFeeRecipientByPubkeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{8}
}

func (x *GetFeeRecipientByPubkeyResponse) GetData() *GetFeeRecipientByPubkeyResponse_FeeRecipient {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetFeeRecipientByPubkeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Qrladdress    []byte                 `protobuf:"bytes,2,opt,name=qrladdress,proto3" json:"qrladdress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFeeRecipientByPubkeyRequest) Reset() {
	*x = SetFeeRecipientByPubkeyRequest{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFeeRecipientByPubkeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFeeRecipientByPubkeyRequest) ProtoMessage() {}

func (x *SetFeeRecipientByPubkeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFeeRecipientByPubkeyRequest.ProtoReflect.Descriptor instead.
func (*SetFeeRecipientByPubkeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{9}
}

func (x *SetFeeRecipientByPubkeyRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *SetFeeRecipientByPubkeyRequest) GetQrladdress() []byte {
	if x != nil {
		return x.Qrladdress
	}
	return nil
}

type GetGasLimitResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Data          *GetGasLimitResponse_GasLimit `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGasLimitResponse) Reset() {
	*x = GetGasLimitResponse{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGasLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGasLimitResponse) ProtoMessage() {}

func (x *GetGasLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGasLimitResponse.ProtoReflect.Descriptor instead.
func (*GetGasLimitResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{10}
}

func (x *GetGasLimitResponse) GetData() *GetGasLimitResponse_GasLimit {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetGasLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	GasLimit      uint64                 `protobuf:"varint,2,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGasLimitRequest) Reset() {
	*x = SetGasLimitRequest{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGasLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGasLimitRequest) ProtoMessage() {}

func (x *SetGasLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGasLimitRequest.ProtoReflect.Descriptor instead.
func (*SetGasLimitRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{11}
}

func (x *SetGasLimitRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *SetGasLimitRequest) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

type DeleteGasLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGasLimitRequest) Reset() {
	*x = DeleteGasLimitRequest{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGasLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGasLimitRequest) ProtoMessage() {}

func (x *DeleteGasLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGasLimitRequest.ProtoReflect.Descriptor instead.
func (*DeleteGasLimitRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteGasLimitRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type SetVoluntaryExitRequest struct {
	state         protoimpl.MessageState                                   `protogen:"open.v1"`
	Pubkey        []byte                                                   `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty" ssz-size:"2592"`
	Epoch         github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVoluntaryExitRequest) Reset() {
	*x = SetVoluntaryExitRequest{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVoluntaryExitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVoluntaryExitRequest) ProtoMessage() {}

func (x *SetVoluntaryExitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVoluntaryExitRequest.ProtoReflect.Descriptor instead.
func (*SetVoluntaryExitRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{13}
}

func (x *SetVoluntaryExitRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *SetVoluntaryExitRequest) GetEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.Epoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

type SetVoluntaryExitResponse struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Data          *SetVoluntaryExitResponse_SignedVoluntaryExit `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVoluntaryExitResponse) Reset() {
	*x = SetVoluntaryExitResponse{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVoluntaryExitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVoluntaryExitResponse) ProtoMessage() {}

func (x *SetVoluntaryExitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVoluntaryExitResponse.ProtoReflect.Descriptor instead.
func (*SetVoluntaryExitResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{14}
}

func (x *SetVoluntaryExitResponse) GetData() *SetVoluntaryExitResponse_SignedVoluntaryExit {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListKeystoresResponse_Keystore struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ValidatingPubkey []byte                 `protobuf:"bytes,1,opt,name=validating_pubkey,json=validatingPubkey,proto3" json:"validating_pubkey,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListKeystoresResponse_Keystore) Reset() {
	*x = ListKeystoresResponse_Keystore{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeystoresResponse_Keystore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeystoresResponse_Keystore) ProtoMessage() {}

func (x *ListKeystoresResponse_Keystore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeystoresResponse_Keystore.ProtoReflect.Descriptor instead.
func (*ListKeystoresResponse_Keystore) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListKeystoresResponse_Keystore) GetValidatingPubkey() []byte {
	if x != nil {
		return x.ValidatingPubkey
	}
	return nil
}

type GetFeeRecipientByPubkeyResponse_FeeRecipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Qrladdress    []byte                 `protobuf:"bytes,2,opt,name=qrladdress,proto3" json:"qrladdress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeeRecipientByPubkeyResponse_FeeRecipient) Reset() {
	*x = GetFeeRecipientByPubkeyResponse_FeeRecipient{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeeRecipientByPubkeyResponse_FeeRecipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeeRecipientByPubkeyResponse_FeeRecipient) ProtoMessage() {}

func (x *GetFeeRecipientByPubkeyResponse_FeeRecipient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeeRecipientByPubkeyResponse_FeeRecipient.ProtoReflect.Descriptor instead.
func (*GetFeeRecipientByPubkeyResponse_FeeRecipient) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{8, 0}
}

func (x *GetFeeRecipientByPubkeyResponse_FeeRecipient) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *GetFeeRecipientByPubkeyResponse_FeeRecipient) GetQrladdress() []byte {
	if x != nil {
		return x.Qrladdress
	}
	return nil
}

type GetGasLimitResponse_GasLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	GasLimit      uint64                 `protobuf:"varint,2,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGasLimitResponse_GasLimit) Reset() {
	*x = GetGasLimitResponse_GasLimit{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGasLimitResponse_GasLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGasLimitResponse_GasLimit) ProtoMessage() {}

func (x *GetGasLimitResponse_GasLimit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGasLimitResponse_GasLimit.ProtoReflect.Descriptor instead.
func (*GetGasLimitResponse_GasLimit) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{10, 0}
}

func (x *GetGasLimitResponse_GasLimit) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *GetGasLimitResponse_GasLimit) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

type SetVoluntaryExitResponse_SignedVoluntaryExit struct {
	state         protoimpl.MessageState                                      `protogen:"open.v1"`
	Message       *SetVoluntaryExitResponse_SignedVoluntaryExit_VoluntaryExit `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                                                      `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetVoluntaryExitResponse_SignedVoluntaryExit) Reset() {
	*x = SetVoluntaryExitResponse_SignedVoluntaryExit{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVoluntaryExitResponse_SignedVoluntaryExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVoluntaryExitResponse_SignedVoluntaryExit) ProtoMessage() {}

func (x *SetVoluntaryExitResponse_SignedVoluntaryExit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVoluntaryExitResponse_SignedVoluntaryExit.ProtoReflect.Descriptor instead.
func (*SetVoluntaryExitResponse_SignedVoluntaryExit) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{14, 0}
}

func (x *SetVoluntaryExitResponse_SignedVoluntaryExit) GetMessage() *SetVoluntaryExitResponse_SignedVoluntaryExit_VoluntaryExit {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SetVoluntaryExitResponse_SignedVoluntaryExit) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SetVoluntaryExitResponse_SignedVoluntaryExit_VoluntaryExit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Epoch          uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ValidatorIndex uint64                 `protobuf:"varint,2,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetVoluntaryExitResponse_SignedVoluntaryExit_VoluntaryExit) Reset() {
	*x = SetVoluntaryExitResponse_SignedVoluntaryExit_VoluntaryExit{}
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetVoluntaryExitResponse_SignedVoluntaryExit_VoluntaryExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVoluntaryExitResponse_SignedVoluntaryExit_VoluntaryExit) ProtoMessage() {}

func (x *SetVoluntaryExitResponse_SignedVoluntaryExit_VoluntaryExit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_service_key_management_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVoluntaryExitResponse_SignedVoluntaryExit_VoluntaryExit.ProtoReflect.Descriptor instead.
func (*SetVoluntaryExitResponse_SignedVoluntaryExit_VoluntaryExit) Descriptor() ([]byte, []int) {
	return file_proto_qrl_service_key_management_proto_rawDescGZIP(), []int{14, 0, 0}
}

func (x *SetVoluntaryExitResponse_SignedVoluntaryExit_VoluntaryExit) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *SetVoluntaryExitResponse_SignedVoluntaryExit_VoluntaryExit) GetValidatorIndex() uint64 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

var File_proto_qrl_service_key_management_proto protoreflect.FileDescriptor

const file_proto_qrl_service_key_management_proto_rawDesc = "" +
	"\n" +
	"&proto/qrl/service/key_management.proto\x12\x12theqrl.qrl.service\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1bproto/qrl/ext/options.proto\"\x98\x01\n" +
	"\x15ListKeystoresResponse\x12F\n" +
	"\x04data\x18\x01 \x03(\v22.theqrl.qrl.service.ListKeystoresResponse.KeystoreR\x04data\x1a7\n" +
	"\bKeystore\x12+\n" +
	"\x11validating_pubkey\x18\x01 \x01(\fR\x10validatingPubkey\"\x85\x01\n" +
	"\x16ImportKeystoresRequest\x12\x1c\n" +
	"\tkeystores\x18\x01 \x03(\tR\tkeystores\x12\x1c\n" +
	"\tpasswords\x18\x02 \x03(\tR\tpasswords\x12/\n" +
	"\x13slashing_protection\x18\x03 \x01(\tR\x12slashingProtection\"Y\n" +
	"\x17ImportKeystoresResponse\x12>\n" +
	"\x04data\x18\x01 \x03(\v2*.theqrl.qrl.service.ImportedKeystoreStatusR\x04data\"2\n" +
	"\x16DeleteKeystoresRequest\x12\x18\n" +
	"\apubkeys\x18\x01 \x03(\fR\apubkeys\"\x89\x01\n" +
	"\x17DeleteKeystoresResponse\x12=\n" +
	"\x04data\x18\x01 \x03(\v2).theqrl.qrl.service.DeletedKeystoreStatusR\x04data\x12/\n" +
	"\x13slashing_protection\x18\x02 \x01(\tR\x12slashingProtection\"\xaf\x01\n" +
	"\x16ImportedKeystoreStatus\x12I\n" +
	"\x06status\x18\x01 \x01(\x0e21.theqrl.qrl.service.ImportedKeystoreStatus.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x06Status\x12\f\n" +
	"\bIMPORTED\x10\x00\x12\r\n" +
	"\tDUPLICATE\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x02\"\xbc\x01\n" +
	"\x15DeletedKeystoreStatus\x12H\n" +
	"\x06status\x18\x01 \x01(\x0e20.theqrl.qrl.service.DeletedKeystoreStatus.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"?\n" +
	"\x06Status\x12\v\n" +
	"\aDELETED\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01\x12\x0e\n" +
	"\n" +
	"NOT_ACTIVE\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\"'\n" +
	"\rPubkeyRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\"\xbf\x01\n" +
	"\x1fGetFeeRecipientByPubkeyResponse\x12T\n" +
	"\x04data\x18\x01 \x01(\v2@.theqrl.qrl.service.GetFeeRecipientByPubkeyResponse.FeeRecipientR\x04data\x1aF\n" +
	"\fFeeRecipient\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x1e\n" +
	"\n" +
	"qrladdress\x18\x02 \x01(\fR\n" +
	"qrladdress\"X\n" +
	"\x1eSetFeeRecipientByPubkeyRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x1e\n" +
	"\n" +
	"qrladdress\x18\x02 \x01(\fR\n" +
	"qrladdress\"\x9c\x01\n" +
	"\x13GetGasLimitResponse\x12D\n" +
	"\x04data\x18\x01 \x01(\v20.theqrl.qrl.service.GetGasLimitResponse.GasLimitR\x04data\x1a?\n" +
	"\bGasLimit\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x1b\n" +
	"\tgas_limit\x18\x02 \x01(\x04R\bgasLimit\"I\n" +
	"\x12SetGasLimitRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x1b\n" +
	"\tgas_limit\x18\x02 \x01(\x04R\bgasLimit\"/\n" +
	"\x15DeleteGasLimitRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\"\x8f\x01\n" +
	"\x17SetVoluntaryExitRequest\x12 \n" +
	"\x06pubkey\x18\x01 \x01(\fB\b\x8a\xb5\x18\x042592R\x06pubkey\x12R\n" +
	"\x05epoch\x18\x02 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x05epoch\"\xe6\x03\n" +
	"\x18SetVoluntaryExitResponse\x12T\n" +
	"\x04data\x18\x01 \x01(\v2@.theqrl.qrl.service.SetVoluntaryExitResponse.SignedVoluntaryExitR\x04data\x1a\xf3\x02\n" +
	"\x13SignedVoluntaryExit\x12h\n" +
	"\amessage\x18\x01 \x01(\v2N.theqrl.qrl.service.SetVoluntaryExitResponse.SignedVoluntaryExit.VoluntaryExitR\amessage\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x1a\xd3\x01\n" +
	"\rVoluntaryExit\x12R\n" +
	"\x05epoch\x18\x01 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x05epoch\x12n\n" +
	"\x0fvalidator_index\x18\x02 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\x0evalidatorIndex2\xf6\v\n" +
	"\rKeyManagement\x12v\n" +
	"\rListKeystores\x12\x16.google.protobuf.Empty\x1a).theqrl.qrl.service.ListKeystoresResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/internal/qrl/v1/keystores\x12\x91\x01\n" +
	"\x0fImportKeystores\x12*.theqrl.qrl.service.ImportKeystoresRequest\x1a+.theqrl.qrl.service.ImportKeystoresResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/internal/qrl/v1/keystores\x12\x91\x01\n" +
	"\x0fDeleteKeystores\x12*.theqrl.qrl.service.DeleteKeystoresRequest\x1a+.theqrl.qrl.service.DeleteKeystoresResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01**\x1a/internal/qrl/v1/keystores\x12\xac\x01\n" +
	"\x18ListFeeRecipientByPubkey\x12!.theqrl.qrl.service.PubkeyRequest\x1a3.theqrl.qrl.service.GetFeeRecipientByPubkeyResponse\"8\x82\xd3\xe4\x93\x022\x120/internal/qrl/v1/validator/{pubkey}/feerecipient\x12\xa2\x01\n" +
	"\x17SetFeeRecipientByPubkey\x122.theqrl.qrl.service.SetFeeRecipientByPubkeyRequest\x1a\x16.google.protobuf.Empty\";\x82\xd3\xe4\x93\x025:\x01*\"0/internal/qrl/v1/validator/{pubkey}/feerecipient\x12\x94\x01\n" +
	"\x1aDeleteFeeRecipientByPubkey\x12!.theqrl.qrl.service.PubkeyRequest\x1a\x16.google.protobuf.Empty\";\x82\xd3\xe4\x93\x025:\x01**0/internal/qrl/v1/validator/{pubkey}/feerecipient\x12\x90\x01\n" +
	"\vGetGasLimit\x12!.theqrl.qrl.service.PubkeyRequest\x1a'.theqrl.qrl.service.GetGasLimitResponse\"5\x82\xd3\xe4\x93\x02/\x12-/internal/qrl/v1/validator/{pubkey}/gas_limit\x12\x87\x01\n" +
	"\vSetGasLimit\x12&.theqrl.qrl.service.SetGasLimitRequest\x1a\x16.google.protobuf.Empty\"8\x82\xd3\xe4\x93\x022:\x01*\"-/internal/qrl/v1/validator/{pubkey}/gas_limit\x12\x8d\x01\n" +
	"\x0eDeleteGasLimit\x12).theqrl.qrl.service.DeleteGasLimitRequest\x1a\x16.google.protobuf.Empty\"8\x82\xd3\xe4\x93\x022:\x01**-/internal/qrl/v1/validator/{pubkey}/gas_limit\x12\xac\x01\n" +
	"\x10SetVoluntaryExit\x12+.theqrl.qrl.service.SetVoluntaryExitRequest\x1a,.theqrl.qrl.service.SetVoluntaryExitResponse\"=\x82\xd3\xe4\x93\x027:\x01*\"2/internal/qrl/v1/validator/{pubkey}/voluntary_exitB\x8a\x01\n" +
	"\x16org.theqrl.qrl.serviceB\x19KeyManagementServiceProtoP\x01Z)github.com/theQRL/qrysm/proto/qrl/service\xaa\x02\x12TheQRL.QRL.Service\xca\x02\x12TheQRL\\QRL\\Serviceb\x06proto3"

var (
	file_proto_qrl_service_key_management_proto_rawDescOnce sync.Once
	file_proto_qrl_service_key_management_proto_rawDescData []byte
)

func file_proto_qrl_service_key_management_proto_rawDescGZIP() []byte {
	file_proto_qrl_service_key_management_proto_rawDescOnce.Do(func() {
		file_proto_qrl_service_key_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrl_service_key_management_proto_rawDesc), len(file_proto_qrl_service_key_management_proto_rawDesc)))
	})
	return file_proto_qrl_service_key_management_proto_rawDescData
}

var file_proto_qrl_service_key_management_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_qrl_service_key_management_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_qrl_service_key_management_proto_goTypes = []any{
	(ImportedKeystoreStatus_Status)(0),                                 // 0: theqrl.qrl.service.ImportedKeystoreStatus.Status
	(DeletedKeystoreStatus_Status)(0),                                  // 1: theqrl.qrl.service.DeletedKeystoreStatus.Status
	(*ListKeystoresResponse)(nil),                                      // 2: theqrl.qrl.service.ListKeystoresResponse
	(*ImportKeystoresRequest)(nil),                                     // 3: theqrl.qrl.service.ImportKeystoresRequest
	(*ImportKeystoresResponse)(nil),                                    // 4: theqrl.qrl.service.ImportKeystoresResponse
	(*DeleteKeystoresRequest)(nil),                                     // 5: theqrl.qrl.service.DeleteKeystoresRequest
	(*DeleteKeystoresResponse)(nil),                                    // 6: theqrl.qrl.service.DeleteKeystoresResponse
	(*ImportedKeystoreStatus)(nil),                                     // 7: theqrl.qrl.service.ImportedKeystoreStatus
	(*DeletedKeystoreStatus)(nil),                                      // 8: theqrl.qrl.service.DeletedKeystoreStatus
	(*PubkeyRequest)(nil),                                              // 9: theqrl.qrl.service.PubkeyRequest
	(*GetFeeRecipientByPubkeyResponse)(nil),                            // 10: theqrl.qrl.service.GetFeeRecipientByPubkeyResponse
	(*SetFeeRecipientByPubkeyRequest)(nil),                             // 11: theqrl.qrl.service.SetFeeRecipientByPubkeyRequest
	(*GetGasLimitResponse)(nil),                                        // 12: theqrl.qrl.service.GetGasLimitResponse
	(*SetGasLimitRequest)(nil),                                         // 13: theqrl.qrl.service.SetGasLimitRequest
	(*DeleteGasLimitRequest)(nil),                                      // 14: theqrl.qrl.service.DeleteGasLimitRequest
	(*SetVoluntaryExitRequest)(nil),                                    // 15: theqrl.qrl.service.SetVoluntaryExitRequest
	(*SetVoluntaryExitResponse)(nil),                                   // 16: theqrl.qrl.service.SetVoluntaryExitResponse
	(*ListKeystoresResponse_Keystore)(nil),                             // 17: theqrl.qrl.service.ListKeystoresResponse.Keystore
	(*GetFeeRecipientByPubkeyResponse_FeeRecipient)(nil),               // 18: theqrl.qrl.service.GetFeeRecipientByPubkeyResponse.FeeRecipient
	(*GetGasLimitResponse_GasLimit)(nil),                               // 19: theqrl.qrl.service.GetGasLimitResponse.GasLimit
	(*SetVoluntaryExitResponse_SignedVoluntaryExit)(nil),               // 20: theqrl.qrl.service.SetVoluntaryExitResponse.SignedVoluntaryExit
	(*SetVoluntaryExitResponse_SignedVoluntaryExit_VoluntaryExit)(nil), // 21: theqrl.qrl.service.SetVoluntaryExitResponse.SignedVoluntaryExit.VoluntaryExit
	(*emptypb.Empty)(nil),                                              // 22: google.protobuf.Empty
}
var file_proto_qrl_service_key_management_proto_depIdxs = []int32{
	17, // 0: theqrl.qrl.service.ListKeystoresResponse.data:type_name -> theqrl.qrl.service.ListKeystoresResponse.Keystore
	7,  // 1: theqrl.qrl.service.ImportKeystoresResponse.data:type_name -> theqrl.qrl.service.ImportedKeystoreStatus
	8,  // 2: theqrl.qrl.service.DeleteKeystoresResponse.data:type_name -> theqrl.qrl.service.DeletedKeystoreStatus
	0,  // 3: theqrl.qrl.service.ImportedKeystoreStatus.status:type_name -> theqrl.qrl.service.ImportedKeystoreStatus.Status
	1,  // 4: theqrl.qrl.service.DeletedKeystoreStatus.status:type_name -> theqrl.qrl.service.DeletedKeystoreStatus.Status
	18, // 5: theqrl.qrl.service.GetFeeRecipientByPubkeyResponse.data:type_name -> theqrl.qrl.service.GetFeeRecipientByPubkeyResponse.FeeRecipient
	19, // 6: theqrl.qrl.service.GetGasLimitResponse.data:type_name -> theqrl.qrl.service.GetGasLimitResponse.GasLimit
	20, // 7: theqrl.qrl.service.SetVoluntaryExitResponse.data:type_name -> theqrl.qrl.service.SetVoluntaryExitResponse.SignedVoluntaryExit
	21, // 8: theqrl.qrl.service.SetVoluntaryExitResponse.SignedVoluntaryExit.message:type_name -> theqrl.qrl.service.SetVoluntaryExitResponse.SignedVoluntaryExit.VoluntaryExit
	22, // 9: theqrl.qrl.service.KeyManagement.ListKeystores:input_type -> google.protobuf.Empty
	3,  // 10: theqrl.qrl.service.KeyManagement.ImportKeystores:input_type -> theqrl.qrl.service.ImportKeystoresRequest
	5,  // 11: theqrl.qrl.service.KeyManagement.DeleteKeystores:input_type -> theqrl.qrl.service.DeleteKeystoresRequest
	9,  // 12: theqrl.qrl.service.KeyManagement.ListFeeRecipientByPubkey:input_type -> theqrl.qrl.service.PubkeyRequest
	11, // 13: theqrl.qrl.service.KeyManagement.SetFeeRecipientByPubkey:input_type -> theqrl.qrl.service.SetFeeRecipientByPubkeyRequest
	9,  // 14: theqrl.qrl.service.KeyManagement.DeleteFeeRecipientByPubkey:input_type -> theqrl.qrl.service.PubkeyRequest
	9,  // 15: theqrl.qrl.service.KeyManagement.GetGasLimit:input_type -> theqrl.qrl.service.PubkeyRequest
	13, // 16: theqrl.qrl.service.KeyManagement.SetGasLimit:input_type -> theqrl.qrl.service.SetGasLimitRequest
	14, // 17: theqrl.qrl.service.KeyManagement.DeleteGasLimit:input_type -> theqrl.qrl.service.DeleteGasLimitRequest
	15, // 18: theqrl.qrl.service.KeyManagement.SetVoluntaryExit:input_type -> theqrl.qrl.service.SetVoluntaryExitRequest
	2,  // 19: theqrl.qrl.service.KeyManagement.ListKeystores:output_type -> theqrl.qrl.service.ListKeystoresResponse
	4,  // 20: theqrl.qrl.service.KeyManagement.ImportKeystores:output_type -> theqrl.qrl.service.ImportKeystoresResponse
	6,  // 21: theqrl.qrl.service.KeyManagement.DeleteKeystores:output_type -> theqrl.qrl.service.DeleteKeystoresResponse
	10, // 22: theqrl.qrl.service.KeyManagement.ListFeeRecipientByPubkey:output_type -> theqrl.qrl.service.GetFeeRecipientByPubkeyResponse
	22, // 23: theqrl.qrl.service.KeyManagement.SetFeeRecipientByPubkey:output_type -> google.protobuf.Empty
	22, // 24: theqrl.qrl.service.KeyManagement.DeleteFeeRecipientByPubkey:output_type -> google.protobuf.Empty
	12, // 25: theqrl.qrl.service.KeyManagement.GetGasLimit:output_type -> theqrl.qrl.service.GetGasLimitResponse
	22, // 26: theqrl.qrl.service.KeyManagement.SetGasLimit:output_type -> google.protobuf.Empty
	22, // 27: theqrl.qrl.service.KeyManagement.DeleteGasLimit:output_type -> google.protobuf.Empty
	16, // 28: theqrl.qrl.service.KeyManagement.SetVoluntaryExit:output_type -> theqrl.qrl.service.SetVoluntaryExitResponse
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_qrl_service_key_management_proto_init() }
func file_proto_qrl_service_key_management_proto_init() {
	if File_proto_qrl_service_key_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrl_service_key_management_proto_rawDesc), len(file_proto_qrl_service_key_management_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_qrl_service_key_management_proto_goTypes,
		DependencyIndexes: file_proto_qrl_service_key_management_proto_depIdxs,
		EnumInfos:         file_proto_qrl_service_key_management_proto_enumTypes,
		MessageInfos:      file_proto_qrl_service_key_management_proto_msgTypes,
	}.Build()
	File_proto_qrl_service_key_management_proto = out.File
	file_proto_qrl_service_key_management_proto_goTypes = nil
	file_proto_qrl_service_key_management_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// KeyManagementClient is the client API for KeyManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KeyManagementClient interface {
	ListKeystores(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListKeystoresResponse, error)
	ImportKeystores(ctx context.Context, in *ImportKeystoresRequest, opts ...grpc.CallOption) (*ImportKeystoresResponse, error)
	DeleteKeystores(ctx context.Context, in *DeleteKeystoresRequest, opts ...grpc.CallOption) (*DeleteKeystoresResponse, error)
	ListFeeRecipientByPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*GetFeeRecipientByPubkeyResponse, error)
	SetFeeRecipientByPubkey(ctx context.Context, in *SetFeeRecipientByPubkeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteFeeRecipientByPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetGasLimit(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*GetGasLimitResponse, error)
	SetGasLimit(ctx context.Context, in *SetGasLimitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteGasLimit(ctx context.Context, in *DeleteGasLimitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SetVoluntaryExit(ctx context.Context, in *SetVoluntaryExitRequest, opts ...grpc.CallOption) (*SetVoluntaryExitResponse, error)
}

type keyManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyManagementClient(cc grpc.ClientConnInterface) KeyManagementClient {
	return &keyManagementClient{cc}
}

func (c *keyManagementClient) ListKeystores(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListKeystoresResponse, error) {
	out := new(ListKeystoresResponse)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.KeyManagement/ListKeystores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementClient) ImportKeystores(ctx context.Context, in *ImportKeystoresRequest, opts ...grpc.CallOption) (*ImportKeystoresResponse, error) {
	out := new(ImportKeystoresResponse)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.KeyManagement/ImportKeystores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementClient) DeleteKeystores(ctx context.Context, in *DeleteKeystoresRequest, opts ...grpc.CallOption) (*DeleteKeystoresResponse, error) {
	out := new(DeleteKeystoresResponse)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.KeyManagement/DeleteKeystores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementClient) ListFeeRecipientByPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*GetFeeRecipientByPubkeyResponse, error) {
	out := new(GetFeeRecipientByPubkeyResponse)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.KeyManagement/ListFeeRecipientByPubkey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementClient) SetFeeRecipientByPubkey(ctx context.Context, in *SetFeeRecipientByPubkeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.KeyManagement/SetFeeRecipientByPubkey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementClient) DeleteFeeRecipientByPubkey(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.KeyManagement/DeleteFeeRecipientByPubkey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementClient) GetGasLimit(ctx context.Context, in *PubkeyRequest, opts ...grpc.CallOption) (*GetGasLimitResponse, error) {
	out := new(GetGasLimitResponse)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.KeyManagement/GetGasLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementClient) SetGasLimit(ctx context.Context, in *SetGasLimitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.KeyManagement/SetGasLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementClient) DeleteGasLimit(ctx context.Context, in *DeleteGasLimitRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.KeyManagement/DeleteGasLimit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementClient) SetVoluntaryExit(ctx context.Context, in *SetVoluntaryExitRequest, opts ...grpc.CallOption) (*SetVoluntaryExitResponse, error) {
	out := new(SetVoluntaryExitResponse)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.KeyManagement/SetVoluntaryExit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyManagementServer is the server API for KeyManagement service.
type KeyManagementServer interface {
	ListKeystores(context.Context, *emptypb.Empty) (*ListKeystoresResponse, error)
	ImportKeystores(context.Context, *ImportKeystoresRequest) (*ImportKeystoresResponse, error)
	DeleteKeystores(context.Context, *DeleteKeystoresRequest) (*DeleteKeystoresResponse, error)
	ListFeeRecipientByPubkey(context.Context, *PubkeyRequest) (*GetFeeRecipientByPubkeyResponse, error)
	SetFeeRecipientByPubkey(context.Context, *SetFeeRecipientByPubkeyRequest) (*emptypb.Empty, error)
	DeleteFeeRecipientByPubkey(context.Context, *PubkeyRequest) (*emptypb.Empty, error)
	GetGasLimit(context.Context, *PubkeyRequest) (*GetGasLimitResponse, error)
	SetGasLimit(context.Context, *SetGasLimitRequest) (*emptypb.Empty, error)
	DeleteGasLimit(context.Context, *DeleteGasLimitRequest) (*emptypb.Empty, error)
	SetVoluntaryExit(context.Context, *SetVoluntaryExitRequest) (*SetVoluntaryExitResponse, error)
}

// UnimplementedKeyManagementServer can be embedded to have forward compatible implementations.
type UnimplementedKeyManagementServer struct {
}

func (*UnimplementedKeyManagementServer) ListKeystores(context.Context, *emptypb.Empty) (*ListKeystoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKeystores not implemented")
}
func (*UnimplementedKeyManagementServer) ImportKeystores(context.Context, *ImportKeystoresRequest) (*ImportKeystoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportKeystores not implemented")
}
func (*UnimplementedKeyManagementServer) DeleteKeystores(context.Context, *DeleteKeystoresRequest) (*DeleteKeystoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeystores not implemented")
}
func (*UnimplementedKeyManagementServer) ListFeeRecipientByPubkey(context.Context, *PubkeyRequest) (*GetFeeRecipientByPubkeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFeeRecipientByPubkey not implemented")
}
func (*UnimplementedKeyManagementServer) SetFeeRecipientByPubkey(context.Context, *SetFeeRecipientByPubkeyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetFeeRecipientByPubkey not implemented")
}
func (*UnimplementedKeyManagementServer) DeleteFeeRecipientByPubkey(context.Context, *PubkeyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFeeRecipientByPubkey not implemented")
}
func (*UnimplementedKeyManagementServer) GetGasLimit(context.Context, *PubkeyRequest) (*GetGasLimitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGasLimit not implemented")
}
func (*UnimplementedKeyManagementServer) SetGasLimit(context.Context, *SetGasLimitRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetGasLimit not implemented")
}
func (*UnimplementedKeyManagementServer) DeleteGasLimit(context.Context, *DeleteGasLimitRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGasLimit not implemented")
}
func (*UnimplementedKeyManagementServer) SetVoluntaryExit(context.Context, *SetVoluntaryExitRequest) (*SetVoluntaryExitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVoluntaryExit not implemented")
}

func RegisterKeyManagementServer(s *grpc.Server, srv KeyManagementServer) {
	s.RegisterService(&_KeyManagement_serviceDesc, srv)
}

func _KeyManagement_ListKeystores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServer).ListKeystores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.KeyManagement/ListKeystores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServer).ListKeystores(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagement_ImportKeystores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportKeystoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServer).ImportKeystores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.KeyManagement/ImportKeystores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServer).ImportKeystores(ctx, req.(*ImportKeystoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagement_DeleteKeystores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeystoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServer).DeleteKeystores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.KeyManagement/DeleteKeystores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServer).DeleteKeystores(ctx, req.(*DeleteKeystoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagement_ListFeeRecipientByPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServer).ListFeeRecipientByPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.KeyManagement/ListFeeRecipientByPubkey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServer).ListFeeRecipientByPubkey(ctx, req.(*PubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagement_SetFeeRecipientByPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFeeRecipientByPubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServer).SetFeeRecipientByPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.KeyManagement/SetFeeRecipientByPubkey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServer).SetFeeRecipientByPubkey(ctx, req.(*SetFeeRecipientByPubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagement_DeleteFeeRecipientByPubkey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServer).DeleteFeeRecipientByPubkey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.KeyManagement/DeleteFeeRecipientByPubkey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServer).DeleteFeeRecipientByPubkey(ctx, req.(*PubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagement_GetGasLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PubkeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServer).GetGasLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.KeyManagement/GetGasLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServer).GetGasLimit(ctx, req.(*PubkeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagement_SetGasLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetGasLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServer).SetGasLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.KeyManagement/SetGasLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServer).SetGasLimit(ctx, req.(*SetGasLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagement_DeleteGasLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGasLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServer).DeleteGasLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.KeyManagement/DeleteGasLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServer).DeleteGasLimit(ctx, req.(*DeleteGasLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagement_SetVoluntaryExit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVoluntaryExitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServer).SetVoluntaryExit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.KeyManagement/SetVoluntaryExit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServer).SetVoluntaryExit(ctx, req.(*SetVoluntaryExitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KeyManagement_serviceDesc = grpc.ServiceDesc{
	ServiceName: "theqrl.qrl.service.KeyManagement",
	HandlerType: (*KeyManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListKeystores",
			Handler:    _KeyManagement_ListKeystores_Handler,
		},
		{
			MethodName: "ImportKeystores",
			Handler:    _KeyManagement_ImportKeystores_Handler,
		},
		{
			MethodName: "DeleteKeystores",
			Handler:    _KeyManagement_DeleteKeystores_Handler,
		},
		{
			MethodName: "ListFeeRecipientByPubkey",
			Handler:    _KeyManagement_ListFeeRecipientByPubkey_Handler,
		},
		{
			MethodName: "SetFeeRecipientByPubkey",
			Handler:    _KeyManagement_SetFeeRecipientByPubkey_Handler,
		},
		{
			MethodName: "DeleteFeeRecipientByPubkey",
			Handler:    _KeyManagement_DeleteFeeRecipientByPubkey_Handler,
		},
		{
			MethodName: "GetGasLimit",
			Handler:    _KeyManagement_GetGasLimit_Handler,
		},
		{
			MethodName: "SetGasLimit",
			Handler:    _KeyManagement_SetGasLimit_Handler,
		},
		{
			MethodName: "DeleteGasLimit",
			Handler:    _KeyManagement_DeleteGasLimit_Handler,
		},
		{
			MethodName: "SetVoluntaryExit",
			Handler:    _KeyManagement_SetVoluntaryExit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/qrl/service/key_management.proto",
}
