// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrl/service/validator_service.proto

package service

import (
	context "context"
	reflect "reflect"
	unsafe "unsafe"

	v1 "github.com/theQRL/qrysm/proto/qrl/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_qrl_service_validator_service_proto protoreflect.FileDescriptor

const file_proto_qrl_service_validator_service_proto_rawDesc = "" +
	"\n" +
	")proto/qrl/service/validator_service.proto\x12\x12theqrl.qrl.service\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/descriptor.proto\x1a\x1cproto/qrl/v1/validator.proto\x1a\x16proto/qrl/v1/ssz.proto2\xe4\x04\n" +
	"\x0fBeaconValidator\x12\x89\x01\n" +
	"\fProduceBlock\x12\".theqrl.qrl.v1.ProduceBlockRequest\x1a#.theqrl.qrl.v1.ProduceBlockResponse\"0\x82\xd3\xe4\x93\x02*\x12(/internal/qrl/v1/validator/blocks/{slot}\x12\x88\x01\n" +
	"\x0fProduceBlockSSZ\x12\".theqrl.qrl.v1.ProduceBlockRequest\x1a\x1b.theqrl.qrl.v1.SSZContainer\"4\x82\xd3\xe4\x93\x02.\x12,/internal/qrl/v1/validator/blocks/{slot}/ssz\x12\x9f\x01\n" +
	"\x13ProduceBlindedBlock\x12\".theqrl.qrl.v1.ProduceBlockRequest\x1a*.theqrl.qrl.v1.ProduceBlindedBlockResponse\"8\x82\xd3\xe4\x93\x022\x120/internal/qrl/v1/validator/blinded_blocks/{slot}\x12\x97\x01\n" +
	"\x16ProduceBlindedBlockSSZ\x12\".theqrl.qrl.v1.ProduceBlockRequest\x1a\x1b.theqrl.qrl.v1.SSZContainer\"<\x82\xd3\xe4\x93\x026\x124/internal/qrl/v1/validator/blinded_blocks/{slot}/sszB\x86\x01\n" +
	"\x16org.theqrl.qrl.serviceB\x15ValidatorServiceProtoP\x01Z)github.com/theQRL/qrysm/proto/qrl/service\xaa\x02\x12TheQRL.QRL.Service\xca\x02\x12TheQRL\\QRL\\Serviceb\x06proto3"

var file_proto_qrl_service_validator_service_proto_goTypes = []any{
	(*v1.ProduceBlockRequest)(nil),         // 0: theqrl.qrl.v1.ProduceBlockRequest
	(*v1.ProduceBlockResponse)(nil),        // 1: theqrl.qrl.v1.ProduceBlockResponse
	(*v1.SSZContainer)(nil),                // 2: theqrl.qrl.v1.SSZContainer
	(*v1.ProduceBlindedBlockResponse)(nil), // 3: theqrl.qrl.v1.ProduceBlindedBlockResponse
}
var file_proto_qrl_service_validator_service_proto_depIdxs = []int32{
	0, // 0: theqrl.qrl.service.BeaconValidator.ProduceBlock:input_type -> theqrl.qrl.v1.ProduceBlockRequest
	0, // 1: theqrl.qrl.service.BeaconValidator.ProduceBlockSSZ:input_type -> theqrl.qrl.v1.ProduceBlockRequest
	0, // 2: theqrl.qrl.service.BeaconValidator.ProduceBlindedBlock:input_type -> theqrl.qrl.v1.ProduceBlockRequest
	0, // 3: theqrl.qrl.service.BeaconValidator.ProduceBlindedBlockSSZ:input_type -> theqrl.qrl.v1.ProduceBlockRequest
	1, // 4: theqrl.qrl.service.BeaconValidator.ProduceBlock:output_type -> theqrl.qrl.v1.ProduceBlockResponse
	2, // 5: theqrl.qrl.service.BeaconValidator.ProduceBlockSSZ:output_type -> theqrl.qrl.v1.SSZContainer
	3, // 6: theqrl.qrl.service.BeaconValidator.ProduceBlindedBlock:output_type -> theqrl.qrl.v1.ProduceBlindedBlockResponse
	2, // 7: theqrl.qrl.service.BeaconValidator.ProduceBlindedBlockSSZ:output_type -> theqrl.qrl.v1.SSZContainer
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_qrl_service_validator_service_proto_init() }
func file_proto_qrl_service_validator_service_proto_init() {
	if File_proto_qrl_service_validator_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrl_service_validator_service_proto_rawDesc), len(file_proto_qrl_service_validator_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_qrl_service_validator_service_proto_goTypes,
		DependencyIndexes: file_proto_qrl_service_validator_service_proto_depIdxs,
	}.Build()
	File_proto_qrl_service_validator_service_proto = out.File
	file_proto_qrl_service_validator_service_proto_goTypes = nil
	file_proto_qrl_service_validator_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BeaconValidatorClient is the client API for BeaconValidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BeaconValidatorClient interface {
	ProduceBlock(ctx context.Context, in *v1.ProduceBlockRequest, opts ...grpc.CallOption) (*v1.ProduceBlockResponse, error)
	ProduceBlockSSZ(ctx context.Context, in *v1.ProduceBlockRequest, opts ...grpc.CallOption) (*v1.SSZContainer, error)
	ProduceBlindedBlock(ctx context.Context, in *v1.ProduceBlockRequest, opts ...grpc.CallOption) (*v1.ProduceBlindedBlockResponse, error)
	ProduceBlindedBlockSSZ(ctx context.Context, in *v1.ProduceBlockRequest, opts ...grpc.CallOption) (*v1.SSZContainer, error)
}

type beaconValidatorClient struct {
	cc grpc.ClientConnInterface
}

func NewBeaconValidatorClient(cc grpc.ClientConnInterface) BeaconValidatorClient {
	return &beaconValidatorClient{cc}
}

func (c *beaconValidatorClient) ProduceBlock(ctx context.Context, in *v1.ProduceBlockRequest, opts ...grpc.CallOption) (*v1.ProduceBlockResponse, error) {
	out := new(v1.ProduceBlockResponse)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.BeaconValidator/ProduceBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconValidatorClient) ProduceBlockSSZ(ctx context.Context, in *v1.ProduceBlockRequest, opts ...grpc.CallOption) (*v1.SSZContainer, error) {
	out := new(v1.SSZContainer)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.BeaconValidator/ProduceBlockSSZ", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconValidatorClient) ProduceBlindedBlock(ctx context.Context, in *v1.ProduceBlockRequest, opts ...grpc.CallOption) (*v1.ProduceBlindedBlockResponse, error) {
	out := new(v1.ProduceBlindedBlockResponse)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.BeaconValidator/ProduceBlindedBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconValidatorClient) ProduceBlindedBlockSSZ(ctx context.Context, in *v1.ProduceBlockRequest, opts ...grpc.CallOption) (*v1.SSZContainer, error) {
	out := new(v1.SSZContainer)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.service.BeaconValidator/ProduceBlindedBlockSSZ", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeaconValidatorServer is the server API for BeaconValidator service.
type BeaconValidatorServer interface {
	ProduceBlock(context.Context, *v1.ProduceBlockRequest) (*v1.ProduceBlockResponse, error)
	ProduceBlockSSZ(context.Context, *v1.ProduceBlockRequest) (*v1.SSZContainer, error)
	ProduceBlindedBlock(context.Context, *v1.ProduceBlockRequest) (*v1.ProduceBlindedBlockResponse, error)
	ProduceBlindedBlockSSZ(context.Context, *v1.ProduceBlockRequest) (*v1.SSZContainer, error)
}

// UnimplementedBeaconValidatorServer can be embedded to have forward compatible implementations.
type UnimplementedBeaconValidatorServer struct {
}

func (*UnimplementedBeaconValidatorServer) ProduceBlock(context.Context, *v1.ProduceBlockRequest) (*v1.ProduceBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProduceBlock not implemented")
}
func (*UnimplementedBeaconValidatorServer) ProduceBlockSSZ(context.Context, *v1.ProduceBlockRequest) (*v1.SSZContainer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProduceBlockSSZ not implemented")
}
func (*UnimplementedBeaconValidatorServer) ProduceBlindedBlock(context.Context, *v1.ProduceBlockRequest) (*v1.ProduceBlindedBlockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProduceBlindedBlock not implemented")
}
func (*UnimplementedBeaconValidatorServer) ProduceBlindedBlockSSZ(context.Context, *v1.ProduceBlockRequest) (*v1.SSZContainer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProduceBlindedBlockSSZ not implemented")
}

func RegisterBeaconValidatorServer(s *grpc.Server, srv BeaconValidatorServer) {
	s.RegisterService(&_BeaconValidator_serviceDesc, srv)
}

func _BeaconValidator_ProduceBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ProduceBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconValidatorServer).ProduceBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.BeaconValidator/ProduceBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconValidatorServer).ProduceBlock(ctx, req.(*v1.ProduceBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconValidator_ProduceBlockSSZ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ProduceBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconValidatorServer).ProduceBlockSSZ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.BeaconValidator/ProduceBlockSSZ",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconValidatorServer).ProduceBlockSSZ(ctx, req.(*v1.ProduceBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconValidator_ProduceBlindedBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ProduceBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconValidatorServer).ProduceBlindedBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.BeaconValidator/ProduceBlindedBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconValidatorServer).ProduceBlindedBlock(ctx, req.(*v1.ProduceBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconValidator_ProduceBlindedBlockSSZ_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ProduceBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconValidatorServer).ProduceBlindedBlockSSZ(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.service.BeaconValidator/ProduceBlindedBlockSSZ",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconValidatorServer).ProduceBlindedBlockSSZ(ctx, req.(*v1.ProduceBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BeaconValidator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "theqrl.qrl.service.BeaconValidator",
	HandlerType: (*BeaconValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProduceBlock",
			Handler:    _BeaconValidator_ProduceBlock_Handler,
		},
		{
			MethodName: "ProduceBlockSSZ",
			Handler:    _BeaconValidator_ProduceBlockSSZ_Handler,
		},
		{
			MethodName: "ProduceBlindedBlock",
			Handler:    _BeaconValidator_ProduceBlindedBlock_Handler,
		},
		{
			MethodName: "ProduceBlindedBlockSSZ",
			Handler:    _BeaconValidator_ProduceBlindedBlockSSZ_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/qrl/service/validator_service.proto",
}
