load("@qrysm//tools/go:def.bzl", "go_library", "go_test")

go_library(
    name = "keyderivation",
    srcs = [
        "mnemonic.go",
        "path.go",
    ],
    importpath = "github.com/theQRL/qrysm/cmd/staking-deposit-cli/stakingdeposit/keyhandling/keyderivation",
    visibility = ["//visibility:public"],
    deps = [
        "//cmd/staking-deposit-cli/misc",
        "//config/fieldparams",
        "//crypto/rand",
        "@com_github_pkg_errors//:errors",
        "@com_github_theqrl_go_qrllib//wallet/misc",
        "@com_github_theqrl_go_qrllib//wallet/ml_dsa_87",
        "@org_golang_x_crypto//sha3",
    ],
)

go_test(
    name = "keyderivation_test",
    srcs = ["mnemonic_test.go"],
    embed = [":keyderivation"],
    deps = [
        "//testing/require",
        "@com_github_theqrl_go_qrllib//wallet/misc",
    ],
)
