// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrysm/v1alpha1/beacon_block.proto

package qrl

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_go_bitfield "github.com/theQRL/go-bitfield"
	github_com_theQRL_qrysm_consensus_types_primitives "github.com/theQRL/qrysm/consensus-types/primitives"
	v1 "github.com/theQRL/qrysm/proto/engine/v1"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenericSignedBeaconBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Block:
	//
	//	*GenericSignedBeaconBlock_Zond
	//	*GenericSignedBeaconBlock_BlindedZond
	Block         isGenericSignedBeaconBlock_Block `protobuf_oneof:"block"`
	IsBlinded     bool                             `protobuf:"varint,100,opt,name=is_blinded,json=isBlinded,proto3" json:"is_blinded,omitempty"`
	PayloadValue  uint64                           `protobuf:"varint,101,opt,name=payload_value,json=payloadValue,proto3" json:"payload_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericSignedBeaconBlock) Reset() {
	*x = GenericSignedBeaconBlock{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericSignedBeaconBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericSignedBeaconBlock) ProtoMessage() {}

func (x *GenericSignedBeaconBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericSignedBeaconBlock.ProtoReflect.Descriptor instead.
func (*GenericSignedBeaconBlock) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{0}
}

func (x *GenericSignedBeaconBlock) GetBlock() isGenericSignedBeaconBlock_Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *GenericSignedBeaconBlock) GetZond() *SignedBeaconBlockZond {
	if x != nil {
		if x, ok := x.Block.(*GenericSignedBeaconBlock_Zond); ok {
			return x.Zond
		}
	}
	return nil
}

func (x *GenericSignedBeaconBlock) GetBlindedZond() *SignedBlindedBeaconBlockZond {
	if x != nil {
		if x, ok := x.Block.(*GenericSignedBeaconBlock_BlindedZond); ok {
			return x.BlindedZond
		}
	}
	return nil
}

func (x *GenericSignedBeaconBlock) GetIsBlinded() bool {
	if x != nil {
		return x.IsBlinded
	}
	return false
}

func (x *GenericSignedBeaconBlock) GetPayloadValue() uint64 {
	if x != nil {
		return x.PayloadValue
	}
	return 0
}

type isGenericSignedBeaconBlock_Block interface {
	isGenericSignedBeaconBlock_Block()
}

type GenericSignedBeaconBlock_Zond struct {
	Zond *SignedBeaconBlockZond `protobuf:"bytes,1,opt,name=zond,proto3,oneof"`
}

type GenericSignedBeaconBlock_BlindedZond struct {
	BlindedZond *SignedBlindedBeaconBlockZond `protobuf:"bytes,2,opt,name=blinded_zond,json=blindedZond,proto3,oneof"`
}

func (*GenericSignedBeaconBlock_Zond) isGenericSignedBeaconBlock_Block() {}

func (*GenericSignedBeaconBlock_BlindedZond) isGenericSignedBeaconBlock_Block() {}

type GenericBeaconBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Block:
	//
	//	*GenericBeaconBlock_Zond
	//	*GenericBeaconBlock_BlindedZond
	Block         isGenericBeaconBlock_Block `protobuf_oneof:"block"`
	IsBlinded     bool                       `protobuf:"varint,100,opt,name=is_blinded,json=isBlinded,proto3" json:"is_blinded,omitempty"`
	PayloadValue  uint64                     `protobuf:"varint,101,opt,name=payload_value,json=payloadValue,proto3" json:"payload_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericBeaconBlock) Reset() {
	*x = GenericBeaconBlock{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericBeaconBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericBeaconBlock) ProtoMessage() {}

func (x *GenericBeaconBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericBeaconBlock.ProtoReflect.Descriptor instead.
func (*GenericBeaconBlock) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{1}
}

func (x *GenericBeaconBlock) GetBlock() isGenericBeaconBlock_Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *GenericBeaconBlock) GetZond() *BeaconBlockZond {
	if x != nil {
		if x, ok := x.Block.(*GenericBeaconBlock_Zond); ok {
			return x.Zond
		}
	}
	return nil
}

func (x *GenericBeaconBlock) GetBlindedZond() *BlindedBeaconBlockZond {
	if x != nil {
		if x, ok := x.Block.(*GenericBeaconBlock_BlindedZond); ok {
			return x.BlindedZond
		}
	}
	return nil
}

func (x *GenericBeaconBlock) GetIsBlinded() bool {
	if x != nil {
		return x.IsBlinded
	}
	return false
}

func (x *GenericBeaconBlock) GetPayloadValue() uint64 {
	if x != nil {
		return x.PayloadValue
	}
	return 0
}

type isGenericBeaconBlock_Block interface {
	isGenericBeaconBlock_Block()
}

type GenericBeaconBlock_Zond struct {
	Zond *BeaconBlockZond `protobuf:"bytes,1,opt,name=zond,proto3,oneof"`
}

type GenericBeaconBlock_BlindedZond struct {
	BlindedZond *BlindedBeaconBlockZond `protobuf:"bytes,2,opt,name=blinded_zond,json=blindedZond,proto3,oneof"`
}

func (*GenericBeaconBlock_Zond) isGenericBeaconBlock_Block() {}

func (*GenericBeaconBlock_BlindedZond) isGenericBeaconBlock_Block() {}

type ProposerSlashing struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Header_1      *SignedBeaconBlockHeader `protobuf:"bytes,1,opt,name=header_1,json=header1,proto3" json:"header_1,omitempty"`
	Header_2      *SignedBeaconBlockHeader `protobuf:"bytes,2,opt,name=header_2,json=header2,proto3" json:"header_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposerSlashing) Reset() {
	*x = ProposerSlashing{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposerSlashing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposerSlashing) ProtoMessage() {}

func (x *ProposerSlashing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposerSlashing.ProtoReflect.Descriptor instead.
func (*ProposerSlashing) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{2}
}

func (x *ProposerSlashing) GetHeader_1() *SignedBeaconBlockHeader {
	if x != nil {
		return x.Header_1
	}
	return nil
}

func (x *ProposerSlashing) GetHeader_2() *SignedBeaconBlockHeader {
	if x != nil {
		return x.Header_2
	}
	return nil
}

type AttesterSlashing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attestation_1 *IndexedAttestation    `protobuf:"bytes,1,opt,name=attestation_1,json=attestation1,proto3" json:"attestation_1,omitempty"`
	Attestation_2 *IndexedAttestation    `protobuf:"bytes,2,opt,name=attestation_2,json=attestation2,proto3" json:"attestation_2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttesterSlashing) Reset() {
	*x = AttesterSlashing{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttesterSlashing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttesterSlashing) ProtoMessage() {}

func (x *AttesterSlashing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttesterSlashing.ProtoReflect.Descriptor instead.
func (*AttesterSlashing) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{3}
}

func (x *AttesterSlashing) GetAttestation_1() *IndexedAttestation {
	if x != nil {
		return x.Attestation_1
	}
	return nil
}

func (x *AttesterSlashing) GetAttestation_2() *IndexedAttestation {
	if x != nil {
		return x.Attestation_2
	}
	return nil
}

type Deposit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         [][]byte               `protobuf:"bytes,1,rep,name=proof,proto3" json:"proof,omitempty" ssz-size:"33,32"`
	Data          *Deposit_Data          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deposit) Reset() {
	*x = Deposit{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deposit) ProtoMessage() {}

func (x *Deposit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deposit.ProtoReflect.Descriptor instead.
func (*Deposit) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{4}
}

func (x *Deposit) GetProof() [][]byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *Deposit) GetData() *Deposit_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type VoluntaryExit struct {
	state          protoimpl.MessageState                                            `protogen:"open.v1"`
	Epoch          github_com_theQRL_qrysm_consensus_types_primitives.Epoch          `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	ValidatorIndex github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,2,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VoluntaryExit) Reset() {
	*x = VoluntaryExit{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoluntaryExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoluntaryExit) ProtoMessage() {}

func (x *VoluntaryExit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoluntaryExit.ProtoReflect.Descriptor instead.
func (*VoluntaryExit) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{5}
}

func (x *VoluntaryExit) GetEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.Epoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

func (x *VoluntaryExit) GetValidatorIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.ValidatorIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

type SignedVoluntaryExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exit          *VoluntaryExit         `protobuf:"bytes,1,opt,name=exit,proto3" json:"exit,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty" ssz-size:"4627"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedVoluntaryExit) Reset() {
	*x = SignedVoluntaryExit{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedVoluntaryExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedVoluntaryExit) ProtoMessage() {}

func (x *SignedVoluntaryExit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedVoluntaryExit.ProtoReflect.Descriptor instead.
func (*SignedVoluntaryExit) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{6}
}

func (x *SignedVoluntaryExit) GetExit() *VoluntaryExit {
	if x != nil {
		return x.Exit
	}
	return nil
}

func (x *SignedVoluntaryExit) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ExecutionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepositRoot   []byte                 `protobuf:"bytes,1,opt,name=deposit_root,json=depositRoot,proto3" json:"deposit_root,omitempty" ssz-size:"32"`
	DepositCount  uint64                 `protobuf:"varint,2,opt,name=deposit_count,json=depositCount,proto3" json:"deposit_count,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty" ssz-size:"32"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionData) Reset() {
	*x = ExecutionData{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionData) ProtoMessage() {}

func (x *ExecutionData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionData.ProtoReflect.Descriptor instead.
func (*ExecutionData) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{7}
}

func (x *ExecutionData) GetDepositRoot() []byte {
	if x != nil {
		return x.DepositRoot
	}
	return nil
}

func (x *ExecutionData) GetDepositCount() uint64 {
	if x != nil {
		return x.DepositCount
	}
	return 0
}

func (x *ExecutionData) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

type BeaconBlockHeader struct {
	state         protoimpl.MessageState                                            `protogen:"open.v1"`
	Slot          github_com_theQRL_qrysm_consensus_types_primitives.Slot           `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	ProposerIndex github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,2,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	ParentRoot    []byte                                                            `protobuf:"bytes,3,opt,name=parent_root,json=parentRoot,proto3" json:"parent_root,omitempty" ssz-size:"32"`
	StateRoot     []byte                                                            `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty" ssz-size:"32"`
	BodyRoot      []byte                                                            `protobuf:"bytes,5,opt,name=body_root,json=bodyRoot,proto3" json:"body_root,omitempty" ssz-size:"32"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconBlockHeader) Reset() {
	*x = BeaconBlockHeader{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconBlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconBlockHeader) ProtoMessage() {}

func (x *BeaconBlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconBlockHeader.ProtoReflect.Descriptor instead.
func (*BeaconBlockHeader) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{8}
}

func (x *BeaconBlockHeader) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *BeaconBlockHeader) GetProposerIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.ProposerIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

func (x *BeaconBlockHeader) GetParentRoot() []byte {
	if x != nil {
		return x.ParentRoot
	}
	return nil
}

func (x *BeaconBlockHeader) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BeaconBlockHeader) GetBodyRoot() []byte {
	if x != nil {
		return x.BodyRoot
	}
	return nil
}

type SignedBeaconBlockHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *BeaconBlockHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty" ssz-size:"4627"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedBeaconBlockHeader) Reset() {
	*x = SignedBeaconBlockHeader{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedBeaconBlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBeaconBlockHeader) ProtoMessage() {}

func (x *SignedBeaconBlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBeaconBlockHeader.ProtoReflect.Descriptor instead.
func (*SignedBeaconBlockHeader) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{9}
}

func (x *SignedBeaconBlockHeader) GetHeader() *BeaconBlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SignedBeaconBlockHeader) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type IndexedAttestation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AttestingIndices []uint64               `protobuf:"varint,1,rep,packed,name=attesting_indices,json=attestingIndices,proto3" json:"attesting_indices,omitempty" ssz-max:"32"`
	Data             *AttestationData       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Signatures       [][]byte               `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty" ssz-max:"32" ssz-size:"?,4627"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IndexedAttestation) Reset() {
	*x = IndexedAttestation{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexedAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexedAttestation) ProtoMessage() {}

func (x *IndexedAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexedAttestation.ProtoReflect.Descriptor instead.
func (*IndexedAttestation) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{10}
}

func (x *IndexedAttestation) GetAttestingIndices() []uint64 {
	if x != nil {
		return x.AttestingIndices
	}
	return nil
}

func (x *IndexedAttestation) GetData() *AttestationData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *IndexedAttestation) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type SyncAggregate struct {
	state                   protoimpl.MessageState                     `protogen:"open.v1"`
	SyncCommitteeBits       github_com_theQRL_go_bitfield.Bitvector128 `protobuf:"bytes,1,opt,name=sync_committee_bits,json=syncCommitteeBits,proto3" json:"sync_committee_bits,omitempty" cast-type:"github.com/theQRL/go-bitfield.Bitvector128" ssz-size:"16"`
	SyncCommitteeSignatures [][]byte                                   `protobuf:"bytes,2,rep,name=sync_committee_signatures,json=syncCommitteeSignatures,proto3" json:"sync_committee_signatures,omitempty" ssz-max:"128" ssz-size:"?,4627"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SyncAggregate) Reset() {
	*x = SyncAggregate{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAggregate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAggregate) ProtoMessage() {}

func (x *SyncAggregate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAggregate.ProtoReflect.Descriptor instead.
func (*SyncAggregate) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{11}
}

func (x *SyncAggregate) GetSyncCommitteeBits() github_com_theQRL_go_bitfield.Bitvector128 {
	if x != nil {
		return x.SyncCommitteeBits
	}
	return github_com_theQRL_go_bitfield.Bitvector128(nil)
}

func (x *SyncAggregate) GetSyncCommitteeSignatures() [][]byte {
	if x != nil {
		return x.SyncCommitteeSignatures
	}
	return nil
}

type SignedBeaconBlockZond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Block         *BeaconBlockZond       `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty" ssz-size:"4627"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedBeaconBlockZond) Reset() {
	*x = SignedBeaconBlockZond{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedBeaconBlockZond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBeaconBlockZond) ProtoMessage() {}

func (x *SignedBeaconBlockZond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBeaconBlockZond.ProtoReflect.Descriptor instead.
func (*SignedBeaconBlockZond) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{12}
}

func (x *SignedBeaconBlockZond) GetBlock() *BeaconBlockZond {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *SignedBeaconBlockZond) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type BeaconBlockZond struct {
	state         protoimpl.MessageState                                            `protogen:"open.v1"`
	Slot          github_com_theQRL_qrysm_consensus_types_primitives.Slot           `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	ProposerIndex github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,2,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	ParentRoot    []byte                                                            `protobuf:"bytes,3,opt,name=parent_root,json=parentRoot,proto3" json:"parent_root,omitempty" ssz-size:"32"`
	StateRoot     []byte                                                            `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty" ssz-size:"32"`
	Body          *BeaconBlockBodyZond                                              `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconBlockZond) Reset() {
	*x = BeaconBlockZond{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconBlockZond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconBlockZond) ProtoMessage() {}

func (x *BeaconBlockZond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconBlockZond.ProtoReflect.Descriptor instead.
func (*BeaconBlockZond) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{13}
}

func (x *BeaconBlockZond) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *BeaconBlockZond) GetProposerIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.ProposerIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

func (x *BeaconBlockZond) GetParentRoot() []byte {
	if x != nil {
		return x.ParentRoot
	}
	return nil
}

func (x *BeaconBlockZond) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BeaconBlockZond) GetBody() *BeaconBlockBodyZond {
	if x != nil {
		return x.Body
	}
	return nil
}

type BeaconBlockBodyZond struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	RandaoReveal      []byte                   `protobuf:"bytes,1,opt,name=randao_reveal,json=randaoReveal,proto3" json:"randao_reveal,omitempty" ssz-size:"32"`
	ExecutionData     *ExecutionData           `protobuf:"bytes,2,opt,name=execution_data,json=executionData,proto3" json:"execution_data,omitempty"`
	Graffiti          []byte                   `protobuf:"bytes,3,opt,name=graffiti,proto3" json:"graffiti,omitempty" ssz-size:"32"`
	ProposerSlashings []*ProposerSlashing      `protobuf:"bytes,4,rep,name=proposer_slashings,json=proposerSlashings,proto3" json:"proposer_slashings,omitempty" ssz-max:"16"`
	AttesterSlashings []*AttesterSlashing      `protobuf:"bytes,5,rep,name=attester_slashings,json=attesterSlashings,proto3" json:"attester_slashings,omitempty" ssz-max:"2"`
	Attestations      []*Attestation           `protobuf:"bytes,6,rep,name=attestations,proto3" json:"attestations,omitempty" ssz-max:"4"`
	Deposits          []*Deposit               `protobuf:"bytes,7,rep,name=deposits,proto3" json:"deposits,omitempty" ssz-max:"16"`
	VoluntaryExits    []*SignedVoluntaryExit   `protobuf:"bytes,8,rep,name=voluntary_exits,json=voluntaryExits,proto3" json:"voluntary_exits,omitempty" ssz-max:"16"`
	SyncAggregate     *SyncAggregate           `protobuf:"bytes,9,opt,name=sync_aggregate,json=syncAggregate,proto3" json:"sync_aggregate,omitempty"`
	ExecutionPayload  *v1.ExecutionPayloadZond `protobuf:"bytes,10,opt,name=execution_payload,json=executionPayload,proto3" json:"execution_payload,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BeaconBlockBodyZond) Reset() {
	*x = BeaconBlockBodyZond{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconBlockBodyZond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconBlockBodyZond) ProtoMessage() {}

func (x *BeaconBlockBodyZond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconBlockBodyZond.ProtoReflect.Descriptor instead.
func (*BeaconBlockBodyZond) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{14}
}

func (x *BeaconBlockBodyZond) GetRandaoReveal() []byte {
	if x != nil {
		return x.RandaoReveal
	}
	return nil
}

func (x *BeaconBlockBodyZond) GetExecutionData() *ExecutionData {
	if x != nil {
		return x.ExecutionData
	}
	return nil
}

func (x *BeaconBlockBodyZond) GetGraffiti() []byte {
	if x != nil {
		return x.Graffiti
	}
	return nil
}

func (x *BeaconBlockBodyZond) GetProposerSlashings() []*ProposerSlashing {
	if x != nil {
		return x.ProposerSlashings
	}
	return nil
}

func (x *BeaconBlockBodyZond) GetAttesterSlashings() []*AttesterSlashing {
	if x != nil {
		return x.AttesterSlashings
	}
	return nil
}

func (x *BeaconBlockBodyZond) GetAttestations() []*Attestation {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *BeaconBlockBodyZond) GetDeposits() []*Deposit {
	if x != nil {
		return x.Deposits
	}
	return nil
}

func (x *BeaconBlockBodyZond) GetVoluntaryExits() []*SignedVoluntaryExit {
	if x != nil {
		return x.VoluntaryExits
	}
	return nil
}

func (x *BeaconBlockBodyZond) GetSyncAggregate() *SyncAggregate {
	if x != nil {
		return x.SyncAggregate
	}
	return nil
}

func (x *BeaconBlockBodyZond) GetExecutionPayload() *v1.ExecutionPayloadZond {
	if x != nil {
		return x.ExecutionPayload
	}
	return nil
}

type SignedBlindedBeaconBlockZond struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Block         *BlindedBeaconBlockZond `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Signature     []byte                  `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty" ssz-size:"4627"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedBlindedBeaconBlockZond) Reset() {
	*x = SignedBlindedBeaconBlockZond{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedBlindedBeaconBlockZond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBlindedBeaconBlockZond) ProtoMessage() {}

func (x *SignedBlindedBeaconBlockZond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBlindedBeaconBlockZond.ProtoReflect.Descriptor instead.
func (*SignedBlindedBeaconBlockZond) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{15}
}

func (x *SignedBlindedBeaconBlockZond) GetBlock() *BlindedBeaconBlockZond {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *SignedBlindedBeaconBlockZond) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type BlindedBeaconBlockZond struct {
	state         protoimpl.MessageState                                            `protogen:"open.v1"`
	Slot          github_com_theQRL_qrysm_consensus_types_primitives.Slot           `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	ProposerIndex github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,2,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	ParentRoot    []byte                                                            `protobuf:"bytes,3,opt,name=parent_root,json=parentRoot,proto3" json:"parent_root,omitempty" ssz-size:"32"`
	StateRoot     []byte                                                            `protobuf:"bytes,4,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty" ssz-size:"32"`
	Body          *BlindedBeaconBlockBodyZond                                       `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlindedBeaconBlockZond) Reset() {
	*x = BlindedBeaconBlockZond{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlindedBeaconBlockZond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindedBeaconBlockZond) ProtoMessage() {}

func (x *BlindedBeaconBlockZond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindedBeaconBlockZond.ProtoReflect.Descriptor instead.
func (*BlindedBeaconBlockZond) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{16}
}

func (x *BlindedBeaconBlockZond) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *BlindedBeaconBlockZond) GetProposerIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.ProposerIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

func (x *BlindedBeaconBlockZond) GetParentRoot() []byte {
	if x != nil {
		return x.ParentRoot
	}
	return nil
}

func (x *BlindedBeaconBlockZond) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *BlindedBeaconBlockZond) GetBody() *BlindedBeaconBlockBodyZond {
	if x != nil {
		return x.Body
	}
	return nil
}

type BlindedBeaconBlockBodyZond struct {
	state                  protoimpl.MessageState         `protogen:"open.v1"`
	RandaoReveal           []byte                         `protobuf:"bytes,1,opt,name=randao_reveal,json=randaoReveal,proto3" json:"randao_reveal,omitempty" ssz-size:"32"`
	ExecutionData          *ExecutionData                 `protobuf:"bytes,2,opt,name=execution_data,json=executionData,proto3" json:"execution_data,omitempty"`
	Graffiti               []byte                         `protobuf:"bytes,3,opt,name=graffiti,proto3" json:"graffiti,omitempty" ssz-size:"32"`
	ProposerSlashings      []*ProposerSlashing            `protobuf:"bytes,4,rep,name=proposer_slashings,json=proposerSlashings,proto3" json:"proposer_slashings,omitempty" ssz-max:"16"`
	AttesterSlashings      []*AttesterSlashing            `protobuf:"bytes,5,rep,name=attester_slashings,json=attesterSlashings,proto3" json:"attester_slashings,omitempty" ssz-max:"2"`
	Attestations           []*Attestation                 `protobuf:"bytes,6,rep,name=attestations,proto3" json:"attestations,omitempty" ssz-max:"4"`
	Deposits               []*Deposit                     `protobuf:"bytes,7,rep,name=deposits,proto3" json:"deposits,omitempty" ssz-max:"16"`
	VoluntaryExits         []*SignedVoluntaryExit         `protobuf:"bytes,8,rep,name=voluntary_exits,json=voluntaryExits,proto3" json:"voluntary_exits,omitempty" ssz-max:"16"`
	SyncAggregate          *SyncAggregate                 `protobuf:"bytes,9,opt,name=sync_aggregate,json=syncAggregate,proto3" json:"sync_aggregate,omitempty"`
	ExecutionPayloadHeader *v1.ExecutionPayloadHeaderZond `protobuf:"bytes,10,opt,name=execution_payload_header,json=executionPayloadHeader,proto3" json:"execution_payload_header,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BlindedBeaconBlockBodyZond) Reset() {
	*x = BlindedBeaconBlockBodyZond{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlindedBeaconBlockBodyZond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindedBeaconBlockBodyZond) ProtoMessage() {}

func (x *BlindedBeaconBlockBodyZond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindedBeaconBlockBodyZond.ProtoReflect.Descriptor instead.
func (*BlindedBeaconBlockBodyZond) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{17}
}

func (x *BlindedBeaconBlockBodyZond) GetRandaoReveal() []byte {
	if x != nil {
		return x.RandaoReveal
	}
	return nil
}

func (x *BlindedBeaconBlockBodyZond) GetExecutionData() *ExecutionData {
	if x != nil {
		return x.ExecutionData
	}
	return nil
}

func (x *BlindedBeaconBlockBodyZond) GetGraffiti() []byte {
	if x != nil {
		return x.Graffiti
	}
	return nil
}

func (x *BlindedBeaconBlockBodyZond) GetProposerSlashings() []*ProposerSlashing {
	if x != nil {
		return x.ProposerSlashings
	}
	return nil
}

func (x *BlindedBeaconBlockBodyZond) GetAttesterSlashings() []*AttesterSlashing {
	if x != nil {
		return x.AttesterSlashings
	}
	return nil
}

func (x *BlindedBeaconBlockBodyZond) GetAttestations() []*Attestation {
	if x != nil {
		return x.Attestations
	}
	return nil
}

func (x *BlindedBeaconBlockBodyZond) GetDeposits() []*Deposit {
	if x != nil {
		return x.Deposits
	}
	return nil
}

func (x *BlindedBeaconBlockBodyZond) GetVoluntaryExits() []*SignedVoluntaryExit {
	if x != nil {
		return x.VoluntaryExits
	}
	return nil
}

func (x *BlindedBeaconBlockBodyZond) GetSyncAggregate() *SyncAggregate {
	if x != nil {
		return x.SyncAggregate
	}
	return nil
}

func (x *BlindedBeaconBlockBodyZond) GetExecutionPayloadHeader() *v1.ExecutionPayloadHeaderZond {
	if x != nil {
		return x.ExecutionPayloadHeader
	}
	return nil
}

type ValidatorRegistrationV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeeRecipient  []byte                 `protobuf:"bytes,1,opt,name=fee_recipient,json=feeRecipient,proto3" json:"fee_recipient,omitempty" ssz-size:"64"`
	GasLimit      uint64                 `protobuf:"varint,2,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Pubkey        []byte                 `protobuf:"bytes,4,opt,name=pubkey,proto3" json:"pubkey,omitempty" ssz-size:"2592"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatorRegistrationV1) Reset() {
	*x = ValidatorRegistrationV1{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatorRegistrationV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatorRegistrationV1) ProtoMessage() {}

func (x *ValidatorRegistrationV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatorRegistrationV1.ProtoReflect.Descriptor instead.
func (*ValidatorRegistrationV1) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{18}
}

func (x *ValidatorRegistrationV1) GetFeeRecipient() []byte {
	if x != nil {
		return x.FeeRecipient
	}
	return nil
}

func (x *ValidatorRegistrationV1) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ValidatorRegistrationV1) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ValidatorRegistrationV1) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type SignedValidatorRegistrationsV1 struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Messages      []*SignedValidatorRegistrationV1 `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedValidatorRegistrationsV1) Reset() {
	*x = SignedValidatorRegistrationsV1{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedValidatorRegistrationsV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedValidatorRegistrationsV1) ProtoMessage() {}

func (x *SignedValidatorRegistrationsV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedValidatorRegistrationsV1.ProtoReflect.Descriptor instead.
func (*SignedValidatorRegistrationsV1) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{19}
}

func (x *SignedValidatorRegistrationsV1) GetMessages() []*SignedValidatorRegistrationV1 {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SignedValidatorRegistrationV1 struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Message       *ValidatorRegistrationV1 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty" ssz-size:"4627"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedValidatorRegistrationV1) Reset() {
	*x = SignedValidatorRegistrationV1{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedValidatorRegistrationV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedValidatorRegistrationV1) ProtoMessage() {}

func (x *SignedValidatorRegistrationV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedValidatorRegistrationV1.ProtoReflect.Descriptor instead.
func (*SignedValidatorRegistrationV1) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{20}
}

func (x *SignedValidatorRegistrationV1) GetMessage() *ValidatorRegistrationV1 {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedValidatorRegistrationV1) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type BuilderBidZond struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Header        *v1.ExecutionPayloadHeaderZond `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Value         []byte                         `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty" ssz-size:"32"`
	Pubkey        []byte                         `protobuf:"bytes,3,opt,name=pubkey,proto3" json:"pubkey,omitempty" ssz-size:"2592"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuilderBidZond) Reset() {
	*x = BuilderBidZond{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuilderBidZond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuilderBidZond) ProtoMessage() {}

func (x *BuilderBidZond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuilderBidZond.ProtoReflect.Descriptor instead.
func (*BuilderBidZond) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{21}
}

func (x *BuilderBidZond) GetHeader() *v1.ExecutionPayloadHeaderZond {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BuilderBidZond) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *BuilderBidZond) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

type SignedBuilderBidZond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *BuilderBidZond        `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty" ssz-size:"4627"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedBuilderBidZond) Reset() {
	*x = SignedBuilderBidZond{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedBuilderBidZond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBuilderBidZond) ProtoMessage() {}

func (x *SignedBuilderBidZond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBuilderBidZond.ProtoReflect.Descriptor instead.
func (*SignedBuilderBidZond) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{22}
}

func (x *SignedBuilderBidZond) GetMessage() *BuilderBidZond {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedBuilderBidZond) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Deposit_Data struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PublicKey           []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty" spec-name:"pubkey" ssz-size:"2592"`
	WithdrawalRecipient []byte                 `protobuf:"bytes,2,opt,name=withdrawal_recipient,json=withdrawalRecipient,proto3" json:"withdrawal_recipient,omitempty" ssz-size:"64"`
	Amount              uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	RandaoCommitment    []byte                 `protobuf:"bytes,5,opt,name=randao_commitment,json=randaoCommitment,proto3" json:"randao_commitment,omitempty" ssz-size:"32"`
	Signature           []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty" ssz-size:"4627"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Deposit_Data) Reset() {
	*x = Deposit_Data{}
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deposit_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deposit_Data) ProtoMessage() {}

func (x *Deposit_Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deposit_Data.ProtoReflect.Descriptor instead.
func (*Deposit_Data) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Deposit_Data) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Deposit_Data) GetWithdrawalRecipient() []byte {
	if x != nil {
		return x.WithdrawalRecipient
	}
	return nil
}

func (x *Deposit_Data) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Deposit_Data) GetRandaoCommitment() []byte {
	if x != nil {
		return x.RandaoCommitment
	}
	return nil
}

func (x *Deposit_Data) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_proto_qrysm_v1alpha1_beacon_block_proto protoreflect.FileDescriptor

const file_proto_qrysm_v1alpha1_beacon_block_proto_rawDesc = "" +
	"\n" +
	"'proto/qrysm/v1alpha1/beacon_block.proto\x12\x13theqrl.qrl.v1alpha1\x1a\x1bproto/qrl/ext/options.proto\x1a&proto/qrysm/v1alpha1/attestation.proto\x1a&proto/engine/v1/execution_engine.proto\"\x81\x02\n" +
	"\x18GenericSignedBeaconBlock\x12@\n" +
	"\x04zond\x18\x01 \x01(\v2*.theqrl.qrl.v1alpha1.SignedBeaconBlockZondH\x00R\x04zond\x12V\n" +
	"\fblinded_zond\x18\x02 \x01(\v21.theqrl.qrl.v1alpha1.SignedBlindedBeaconBlockZondH\x00R\vblindedZond\x12\x1d\n" +
	"\n" +
	"is_blinded\x18d \x01(\bR\tisBlinded\x12#\n" +
	"\rpayload_value\x18e \x01(\x04R\fpayloadValueB\a\n" +
	"\x05block\"\xef\x01\n" +
	"\x12GenericBeaconBlock\x12:\n" +
	"\x04zond\x18\x01 \x01(\v2$.theqrl.qrl.v1alpha1.BeaconBlockZondH\x00R\x04zond\x12P\n" +
	"\fblinded_zond\x18\x02 \x01(\v2+.theqrl.qrl.v1alpha1.BlindedBeaconBlockZondH\x00R\vblindedZond\x12\x1d\n" +
	"\n" +
	"is_blinded\x18d \x01(\bR\tisBlinded\x12#\n" +
	"\rpayload_value\x18e \x01(\x04R\fpayloadValueB\a\n" +
	"\x05block\"\xa4\x01\n" +
	"\x10ProposerSlashing\x12G\n" +
	"\bheader_1\x18\x01 \x01(\v2,.theqrl.qrl.v1alpha1.SignedBeaconBlockHeaderR\aheader1\x12G\n" +
	"\bheader_2\x18\x02 \x01(\v2,.theqrl.qrl.v1alpha1.SignedBeaconBlockHeaderR\aheader2\"\xae\x01\n" +
	"\x10AttesterSlashing\x12L\n" +
	"\rattestation_1\x18\x01 \x01(\v2'.theqrl.qrl.v1alpha1.IndexedAttestationR\fattestation1\x12L\n" +
	"\rattestation_2\x18\x02 \x01(\v2'.theqrl.qrl.v1alpha1.IndexedAttestationR\fattestation2\"\xcd\x02\n" +
	"\aDeposit\x12\x1f\n" +
	"\x05proof\x18\x01 \x03(\fB\t\x8a\xb5\x18\x0533,32R\x05proof\x125\n" +
	"\x04data\x18\x02 \x01(\v2!.theqrl.qrl.v1alpha1.Deposit.DataR\x04data\x1a\xe9\x01\n" +
	"\x04Data\x121\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fB\x12\x8a\xb5\x18\x042592\x9a\xb5\x18\x06pubkeyR\tpublicKey\x129\n" +
	"\x14withdrawal_recipient\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0264R\x13withdrawalRecipient\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x123\n" +
	"\x11randao_commitment\x18\x05 \x01(\fB\x06\x8a\xb5\x18\x0232R\x10randaoCommitment\x12&\n" +
	"\tsignature\x18\x04 \x01(\fB\b\x8a\xb5\x18\x044627R\tsignature\"\xd3\x01\n" +
	"\rVoluntaryExit\x12R\n" +
	"\x05epoch\x18\x01 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x05epoch\x12n\n" +
	"\x0fvalidator_index\x18\x02 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\x0evalidatorIndex\"u\n" +
	"\x13SignedVoluntaryExit\x126\n" +
	"\x04exit\x18\x01 \x01(\v2\".theqrl.qrl.v1alpha1.VoluntaryExitR\x04exit\x12&\n" +
	"\tsignature\x18\x02 \x01(\fB\b\x8a\xb5\x18\x044627R\tsignature\"\x86\x01\n" +
	"\rExecutionData\x12)\n" +
	"\fdeposit_root\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\vdepositRoot\x12#\n" +
	"\rdeposit_count\x18\x02 \x01(\x04R\fdepositCount\x12%\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\tblockHash\"\xc7\x02\n" +
	"\x11BeaconBlockHeader\x12O\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12l\n" +
	"\x0eproposer_index\x18\x02 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\rproposerIndex\x12'\n" +
	"\vparent_root\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"parentRoot\x12%\n" +
	"\n" +
	"state_root\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\tstateRoot\x12#\n" +
	"\tbody_root\x18\x05 \x01(\fB\x06\x8a\xb5\x18\x0232R\bbodyRoot\"\x81\x01\n" +
	"\x17SignedBeaconBlockHeader\x12>\n" +
	"\x06header\x18\x01 \x01(\v2&.theqrl.qrl.v1alpha1.BeaconBlockHeaderR\x06header\x12&\n" +
	"\tsignature\x18\x02 \x01(\fB\b\x8a\xb5\x18\x044627R\tsignature\"\xb5\x01\n" +
	"\x12IndexedAttestation\x123\n" +
	"\x11attesting_indices\x18\x01 \x03(\x04B\x06\x92\xb5\x18\x0232R\x10attestingIndices\x128\n" +
	"\x04data\x18\x02 \x01(\v2$.theqrl.qrl.v1alpha1.AttestationDataR\x04data\x120\n" +
	"\n" +
	"signatures\x18\x03 \x03(\fB\x10\x8a\xb5\x18\x06?,4627\x92\xb5\x18\x0232R\n" +
	"signatures\"\xc4\x01\n" +
	"\rSyncAggregate\x12d\n" +
	"\x13sync_committee_bits\x18\x01 \x01(\fB4\x82\xb5\x18*github.com/theQRL/go-bitfield.Bitvector128\x8a\xb5\x18\x0216R\x11syncCommitteeBits\x12M\n" +
	"\x19sync_committee_signatures\x18\x02 \x03(\fB\x11\x8a\xb5\x18\x06?,4627\x92\xb5\x18\x03128R\x17syncCommitteeSignatures\"{\n" +
	"\x15SignedBeaconBlockZond\x12:\n" +
	"\x05block\x18\x01 \x01(\v2$.theqrl.qrl.v1alpha1.BeaconBlockZondR\x05block\x12&\n" +
	"\tsignature\x18\x02 \x01(\fB\b\x8a\xb5\x18\x044627R\tsignature\"\xde\x02\n" +
	"\x0fBeaconBlockZond\x12O\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12l\n" +
	"\x0eproposer_index\x18\x02 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\rproposerIndex\x12'\n" +
	"\vparent_root\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"parentRoot\x12%\n" +
	"\n" +
	"state_root\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\tstateRoot\x12<\n" +
	"\x04body\x18\x05 \x01(\v2(.theqrl.qrl.v1alpha1.BeaconBlockBodyZondR\x04body\"\xf6\x05\n" +
	"\x13BeaconBlockBodyZond\x12+\n" +
	"\rrandao_reveal\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\frandaoReveal\x12I\n" +
	"\x0eexecution_data\x18\x02 \x01(\v2\".theqrl.qrl.v1alpha1.ExecutionDataR\rexecutionData\x12\"\n" +
	"\bgraffiti\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\bgraffiti\x12\\\n" +
	"\x12proposer_slashings\x18\x04 \x03(\v2%.theqrl.qrl.v1alpha1.ProposerSlashingB\x06\x92\xb5\x18\x0216R\x11proposerSlashings\x12[\n" +
	"\x12attester_slashings\x18\x05 \x03(\v2%.theqrl.qrl.v1alpha1.AttesterSlashingB\x05\x92\xb5\x18\x012R\x11attesterSlashings\x12K\n" +
	"\fattestations\x18\x06 \x03(\v2 .theqrl.qrl.v1alpha1.AttestationB\x05\x92\xb5\x18\x014R\fattestations\x12@\n" +
	"\bdeposits\x18\a \x03(\v2\x1c.theqrl.qrl.v1alpha1.DepositB\x06\x92\xb5\x18\x0216R\bdeposits\x12Y\n" +
	"\x0fvoluntary_exits\x18\b \x03(\v2(.theqrl.qrl.v1alpha1.SignedVoluntaryExitB\x06\x92\xb5\x18\x0216R\x0evoluntaryExits\x12I\n" +
	"\x0esync_aggregate\x18\t \x01(\v2\".theqrl.qrl.v1alpha1.SyncAggregateR\rsyncAggregate\x12S\n" +
	"\x11execution_payload\x18\n" +
	" \x01(\v2&.theqrl.engine.v1.ExecutionPayloadZondR\x10executionPayload\"\x89\x01\n" +
	"\x1cSignedBlindedBeaconBlockZond\x12A\n" +
	"\x05block\x18\x01 \x01(\v2+.theqrl.qrl.v1alpha1.BlindedBeaconBlockZondR\x05block\x12&\n" +
	"\tsignature\x18\x02 \x01(\fB\b\x8a\xb5\x18\x044627R\tsignature\"\xec\x02\n" +
	"\x16BlindedBeaconBlockZond\x12O\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12l\n" +
	"\x0eproposer_index\x18\x02 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\rproposerIndex\x12'\n" +
	"\vparent_root\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"parentRoot\x12%\n" +
	"\n" +
	"state_root\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\tstateRoot\x12C\n" +
	"\x04body\x18\x05 \x01(\v2/.theqrl.qrl.v1alpha1.BlindedBeaconBlockBodyZondR\x04body\"\x90\x06\n" +
	"\x1aBlindedBeaconBlockBodyZond\x12+\n" +
	"\rrandao_reveal\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\frandaoReveal\x12I\n" +
	"\x0eexecution_data\x18\x02 \x01(\v2\".theqrl.qrl.v1alpha1.ExecutionDataR\rexecutionData\x12\"\n" +
	"\bgraffiti\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\bgraffiti\x12\\\n" +
	"\x12proposer_slashings\x18\x04 \x03(\v2%.theqrl.qrl.v1alpha1.ProposerSlashingB\x06\x92\xb5\x18\x0216R\x11proposerSlashings\x12[\n" +
	"\x12attester_slashings\x18\x05 \x03(\v2%.theqrl.qrl.v1alpha1.AttesterSlashingB\x05\x92\xb5\x18\x012R\x11attesterSlashings\x12K\n" +
	"\fattestations\x18\x06 \x03(\v2 .theqrl.qrl.v1alpha1.AttestationB\x05\x92\xb5\x18\x014R\fattestations\x12@\n" +
	"\bdeposits\x18\a \x03(\v2\x1c.theqrl.qrl.v1alpha1.DepositB\x06\x92\xb5\x18\x0216R\bdeposits\x12Y\n" +
	"\x0fvoluntary_exits\x18\b \x03(\v2(.theqrl.qrl.v1alpha1.SignedVoluntaryExitB\x06\x92\xb5\x18\x0216R\x0evoluntaryExits\x12I\n" +
	"\x0esync_aggregate\x18\t \x01(\v2\".theqrl.qrl.v1alpha1.SyncAggregateR\rsyncAggregate\x12f\n" +
	"\x18execution_payload_header\x18\n" +
	" \x01(\v2,.theqrl.engine.v1.ExecutionPayloadHeaderZondR\x16executionPayloadHeader\"\xa3\x01\n" +
	"\x17ValidatorRegistrationV1\x12+\n" +
	"\rfee_recipient\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0264R\ffeeRecipient\x12\x1b\n" +
	"\tgas_limit\x18\x02 \x01(\x04R\bgasLimit\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12 \n" +
	"\x06pubkey\x18\x04 \x01(\fB\b\x8a\xb5\x18\x042592R\x06pubkey\"p\n" +
	"\x1eSignedValidatorRegistrationsV1\x12N\n" +
	"\bmessages\x18\x01 \x03(\v22.theqrl.qrl.v1alpha1.SignedValidatorRegistrationV1R\bmessages\"\x8f\x01\n" +
	"\x1dSignedValidatorRegistrationV1\x12F\n" +
	"\amessage\x18\x01 \x01(\v2,.theqrl.qrl.v1alpha1.ValidatorRegistrationV1R\amessage\x12&\n" +
	"\tsignature\x18\x02 \x01(\fB\b\x8a\xb5\x18\x044627R\tsignature\"\x96\x01\n" +
	"\x0eBuilderBidZond\x12D\n" +
	"\x06header\x18\x01 \x01(\v2,.theqrl.engine.v1.ExecutionPayloadHeaderZondR\x06header\x12\x1c\n" +
	"\x05value\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\x05value\x12 \n" +
	"\x06pubkey\x18\x03 \x01(\fB\b\x8a\xb5\x18\x042592R\x06pubkey\"}\n" +
	"\x14SignedBuilderBidZond\x12=\n" +
	"\amessage\x18\x01 \x01(\v2#.theqrl.qrl.v1alpha1.BuilderBidZondR\amessage\x12&\n" +
	"\tsignature\x18\x02 \x01(\fB\b\x8a\xb5\x18\x044627R\tsignatureB\x8b\x01\n" +
	"\x17org.theqrl.qrl.v1alpha1B\x10BeaconBlockProtoP\x01Z0github.com/theQRL/qrysm/proto/qrysm/v1alpha1;qrl\xaa\x02\x13TheQRL.QRL.v1alpha1\xca\x02\x13TheQRL\\QRL\\v1alpha1b\x06proto3"

var (
	file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescOnce sync.Once
	file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescData []byte
)

func file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescGZIP() []byte {
	file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescOnce.Do(func() {
		file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_beacon_block_proto_rawDesc), len(file_proto_qrysm_v1alpha1_beacon_block_proto_rawDesc)))
	})
	return file_proto_qrysm_v1alpha1_beacon_block_proto_rawDescData
}

var file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_qrysm_v1alpha1_beacon_block_proto_goTypes = []any{
	(*GenericSignedBeaconBlock)(nil),       // 0: theqrl.qrl.v1alpha1.GenericSignedBeaconBlock
	(*GenericBeaconBlock)(nil),             // 1: theqrl.qrl.v1alpha1.GenericBeaconBlock
	(*ProposerSlashing)(nil),               // 2: theqrl.qrl.v1alpha1.ProposerSlashing
	(*AttesterSlashing)(nil),               // 3: theqrl.qrl.v1alpha1.AttesterSlashing
	(*Deposit)(nil),                        // 4: theqrl.qrl.v1alpha1.Deposit
	(*VoluntaryExit)(nil),                  // 5: theqrl.qrl.v1alpha1.VoluntaryExit
	(*SignedVoluntaryExit)(nil),            // 6: theqrl.qrl.v1alpha1.SignedVoluntaryExit
	(*ExecutionData)(nil),                  // 7: theqrl.qrl.v1alpha1.ExecutionData
	(*BeaconBlockHeader)(nil),              // 8: theqrl.qrl.v1alpha1.BeaconBlockHeader
	(*SignedBeaconBlockHeader)(nil),        // 9: theqrl.qrl.v1alpha1.SignedBeaconBlockHeader
	(*IndexedAttestation)(nil),             // 10: theqrl.qrl.v1alpha1.IndexedAttestation
	(*SyncAggregate)(nil),                  // 11: theqrl.qrl.v1alpha1.SyncAggregate
	(*SignedBeaconBlockZond)(nil),          // 12: theqrl.qrl.v1alpha1.SignedBeaconBlockZond
	(*BeaconBlockZond)(nil),                // 13: theqrl.qrl.v1alpha1.BeaconBlockZond
	(*BeaconBlockBodyZond)(nil),            // 14: theqrl.qrl.v1alpha1.BeaconBlockBodyZond
	(*SignedBlindedBeaconBlockZond)(nil),   // 15: theqrl.qrl.v1alpha1.SignedBlindedBeaconBlockZond
	(*BlindedBeaconBlockZond)(nil),         // 16: theqrl.qrl.v1alpha1.BlindedBeaconBlockZond
	(*BlindedBeaconBlockBodyZond)(nil),     // 17: theqrl.qrl.v1alpha1.BlindedBeaconBlockBodyZond
	(*ValidatorRegistrationV1)(nil),        // 18: theqrl.qrl.v1alpha1.ValidatorRegistrationV1
	(*SignedValidatorRegistrationsV1)(nil), // 19: theqrl.qrl.v1alpha1.SignedValidatorRegistrationsV1
	(*SignedValidatorRegistrationV1)(nil),  // 20: theqrl.qrl.v1alpha1.SignedValidatorRegistrationV1
	(*BuilderBidZond)(nil),                 // 21: theqrl.qrl.v1alpha1.BuilderBidZond
	(*SignedBuilderBidZond)(nil),           // 22: theqrl.qrl.v1alpha1.SignedBuilderBidZond
	(*Deposit_Data)(nil),                   // 23: theqrl.qrl.v1alpha1.Deposit.Data
	(*AttestationData)(nil),                // 24: theqrl.qrl.v1alpha1.AttestationData
	(*Attestation)(nil),                    // 25: theqrl.qrl.v1alpha1.Attestation
	(*v1.ExecutionPayloadZond)(nil),        // 26: theqrl.engine.v1.ExecutionPayloadZond
	(*v1.ExecutionPayloadHeaderZond)(nil),  // 27: theqrl.engine.v1.ExecutionPayloadHeaderZond
}
var file_proto_qrysm_v1alpha1_beacon_block_proto_depIdxs = []int32{
	12, // 0: theqrl.qrl.v1alpha1.GenericSignedBeaconBlock.zond:type_name -> theqrl.qrl.v1alpha1.SignedBeaconBlockZond
	15, // 1: theqrl.qrl.v1alpha1.GenericSignedBeaconBlock.blinded_zond:type_name -> theqrl.qrl.v1alpha1.SignedBlindedBeaconBlockZond
	13, // 2: theqrl.qrl.v1alpha1.GenericBeaconBlock.zond:type_name -> theqrl.qrl.v1alpha1.BeaconBlockZond
	16, // 3: theqrl.qrl.v1alpha1.GenericBeaconBlock.blinded_zond:type_name -> theqrl.qrl.v1alpha1.BlindedBeaconBlockZond
	9,  // 4: theqrl.qrl.v1alpha1.ProposerSlashing.header_1:type_name -> theqrl.qrl.v1alpha1.SignedBeaconBlockHeader
	9,  // 5: theqrl.qrl.v1alpha1.ProposerSlashing.header_2:type_name -> theqrl.qrl.v1alpha1.SignedBeaconBlockHeader
	10, // 6: theqrl.qrl.v1alpha1.AttesterSlashing.attestation_1:type_name -> theqrl.qrl.v1alpha1.IndexedAttestation
	10, // 7: theqrl.qrl.v1alpha1.AttesterSlashing.attestation_2:type_name -> theqrl.qrl.v1alpha1.IndexedAttestation
	23, // 8: theqrl.qrl.v1alpha1.Deposit.data:type_name -> theqrl.qrl.v1alpha1.Deposit.Data
	5,  // 9: theqrl.qrl.v1alpha1.SignedVoluntaryExit.exit:type_name -> theqrl.qrl.v1alpha1.VoluntaryExit
	8,  // 10: theqrl.qrl.v1alpha1.SignedBeaconBlockHeader.header:type_name -> theqrl.qrl.v1alpha1.BeaconBlockHeader
	24, // 11: theqrl.qrl.v1alpha1.IndexedAttestation.data:type_name -> theqrl.qrl.v1alpha1.AttestationData
	13, // 12: theqrl.qrl.v1alpha1.SignedBeaconBlockZond.block:type_name -> theqrl.qrl.v1alpha1.BeaconBlockZond
	14, // 13: theqrl.qrl.v1alpha1.BeaconBlockZond.body:type_name -> theqrl.qrl.v1alpha1.BeaconBlockBodyZond
	7,  // 14: theqrl.qrl.v1alpha1.BeaconBlockBodyZond.execution_data:type_name -> theqrl.qrl.v1alpha1.ExecutionData
	2,  // 15: theqrl.qrl.v1alpha1.BeaconBlockBodyZond.proposer_slashings:type_name -> theqrl.qrl.v1alpha1.ProposerSlashing
	3,  // 16: theqrl.qrl.v1alpha1.BeaconBlockBodyZond.attester_slashings:type_name -> theqrl.qrl.v1alpha1.AttesterSlashing
	25, // 17: theqrl.qrl.v1alpha1.BeaconBlockBodyZond.attestations:type_name -> theqrl.qrl.v1alpha1.Attestation
	4,  // 18: theqrl.qrl.v1alpha1.BeaconBlockBodyZond.deposits:type_name -> theqrl.qrl.v1alpha1.Deposit
	6,  // 19: theqrl.qrl.v1alpha1.BeaconBlockBodyZond.voluntary_exits:type_name -> theqrl.qrl.v1alpha1.SignedVoluntaryExit
	11, // 20: theqrl.qrl.v1alpha1.BeaconBlockBodyZond.sync_aggregate:type_name -> theqrl.qrl.v1alpha1.SyncAggregate
	26, // 21: theqrl.qrl.v1alpha1.BeaconBlockBodyZond.execution_payload:type_name -> theqrl.engine.v1.ExecutionPayloadZond
	16, // 22: theqrl.qrl.v1alpha1.SignedBlindedBeaconBlockZond.block:type_name -> theqrl.qrl.v1alpha1.BlindedBeaconBlockZond
	17, // 23: theqrl.qrl.v1alpha1.BlindedBeaconBlockZond.body:type_name -> theqrl.qrl.v1alpha1.BlindedBeaconBlockBodyZond
	7,  // 24: theqrl.qrl.v1alpha1.BlindedBeaconBlockBodyZond.execution_data:type_name -> theqrl.qrl.v1alpha1.ExecutionData
	2,  // 25: theqrl.qrl.v1alpha1.BlindedBeaconBlockBodyZond.proposer_slashings:type_name -> theqrl.qrl.v1alpha1.ProposerSlashing
	3,  // 26: theqrl.qrl.v1alpha1.BlindedBeaconBlockBodyZond.attester_slashings:type_name -> theqrl.qrl.v1alpha1.AttesterSlashing
	25, // 27: theqrl.qrl.v1alpha1.BlindedBeaconBlockBodyZond.attestations:type_name -> theqrl.qrl.v1alpha1.Attestation
	4,  // 28: theqrl.qrl.v1alpha1.BlindedBeaconBlockBodyZond.deposits:type_name -> theqrl.qrl.v1alpha1.Deposit
	6,  // 29: theqrl.qrl.v1alpha1.BlindedBeaconBlockBodyZond.voluntary_exits:type_name -> theqrl.qrl.v1alpha1.SignedVoluntaryExit
	11, // 30: theqrl.qrl.v1alpha1.BlindedBeaconBlockBodyZond.sync_aggregate:type_name -> theqrl.qrl.v1alpha1.SyncAggregate
	27, // 31: theqrl.qrl.v1alpha1.BlindedBeaconBlockBodyZond.execution_payload_header:type_name -> theqrl.engine.v1.ExecutionPayloadHeaderZond
	20, // 32: theqrl.qrl.v1alpha1.SignedValidatorRegistrationsV1.messages:type_name -> theqrl.qrl.v1alpha1.SignedValidatorRegistrationV1
	18, // 33: theqrl.qrl.v1alpha1.SignedValidatorRegistrationV1.message:type_name -> theqrl.qrl.v1alpha1.ValidatorRegistrationV1
	27, // 34: theqrl.qrl.v1alpha1.BuilderBidZond.header:type_name -> theqrl.engine.v1.ExecutionPayloadHeaderZond
	21, // 35: theqrl.qrl.v1alpha1.SignedBuilderBidZond.message:type_name -> theqrl.qrl.v1alpha1.BuilderBidZond
	36, // [36:36] is the sub-list for method output_type
	36, // [36:36] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_proto_qrysm_v1alpha1_beacon_block_proto_init() }
func file_proto_qrysm_v1alpha1_beacon_block_proto_init() {
	if File_proto_qrysm_v1alpha1_beacon_block_proto != nil {
		return
	}
	file_proto_qrysm_v1alpha1_attestation_proto_init()
	file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[0].OneofWrappers = []any{
		(*GenericSignedBeaconBlock_Zond)(nil),
		(*GenericSignedBeaconBlock_BlindedZond)(nil),
	}
	file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes[1].OneofWrappers = []any{
		(*GenericBeaconBlock_Zond)(nil),
		(*GenericBeaconBlock_BlindedZond)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_beacon_block_proto_rawDesc), len(file_proto_qrysm_v1alpha1_beacon_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrysm_v1alpha1_beacon_block_proto_goTypes,
		DependencyIndexes: file_proto_qrysm_v1alpha1_beacon_block_proto_depIdxs,
		MessageInfos:      file_proto_qrysm_v1alpha1_beacon_block_proto_msgTypes,
	}.Build()
	File_proto_qrysm_v1alpha1_beacon_block_proto = out.File
	file_proto_qrysm_v1alpha1_beacon_block_proto_goTypes = nil
	file_proto_qrysm_v1alpha1_beacon_block_proto_depIdxs = nil
}
