// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrysm/v1alpha1/debug.proto

package qrl

import (
	context "context"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_qrysm_consensus_types_primitives "github.com/theQRL/qrysm/consensus-types/primitives"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoggingLevelRequest_Level int32

const (
	LoggingLevelRequest_INFO  LoggingLevelRequest_Level = 0
	LoggingLevelRequest_DEBUG LoggingLevelRequest_Level = 1
	LoggingLevelRequest_TRACE LoggingLevelRequest_Level = 2
)

// Enum value maps for LoggingLevelRequest_Level.
var (
	LoggingLevelRequest_Level_name = map[int32]string{
		0: "INFO",
		1: "DEBUG",
		2: "TRACE",
	}
	LoggingLevelRequest_Level_value = map[string]int32{
		"INFO":  0,
		"DEBUG": 1,
		"TRACE": 2,
	}
)

func (x LoggingLevelRequest_Level) Enum() *LoggingLevelRequest_Level {
	p := new(LoggingLevelRequest_Level)
	*p = x
	return p
}

func (x LoggingLevelRequest_Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoggingLevelRequest_Level) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_qrysm_v1alpha1_debug_proto_enumTypes[0].Descriptor()
}

func (LoggingLevelRequest_Level) Type() protoreflect.EnumType {
	return &file_proto_qrysm_v1alpha1_debug_proto_enumTypes[0]
}

func (x LoggingLevelRequest_Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoggingLevelRequest_Level.Descriptor instead.
func (LoggingLevelRequest_Level) EnumDescriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_debug_proto_rawDescGZIP(), []int{3, 0}
}

type BeaconStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to QueryFilter:
	//
	//	*BeaconStateRequest_Slot
	//	*BeaconStateRequest_BlockRoot
	QueryFilter   isBeaconStateRequest_QueryFilter `protobuf_oneof:"query_filter"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconStateRequest) Reset() {
	*x = BeaconStateRequest{}
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconStateRequest) ProtoMessage() {}

func (x *BeaconStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconStateRequest.ProtoReflect.Descriptor instead.
func (*BeaconStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_debug_proto_rawDescGZIP(), []int{0}
}

func (x *BeaconStateRequest) GetQueryFilter() isBeaconStateRequest_QueryFilter {
	if x != nil {
		return x.QueryFilter
	}
	return nil
}

func (x *BeaconStateRequest) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		if x, ok := x.QueryFilter.(*BeaconStateRequest_Slot); ok {
			return x.Slot
		}
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *BeaconStateRequest) GetBlockRoot() []byte {
	if x != nil {
		if x, ok := x.QueryFilter.(*BeaconStateRequest_BlockRoot); ok {
			return x.BlockRoot
		}
	}
	return nil
}

type isBeaconStateRequest_QueryFilter interface {
	isBeaconStateRequest_QueryFilter()
}

type BeaconStateRequest_Slot struct {
	Slot github_com_theQRL_qrysm_consensus_types_primitives.Slot `protobuf:"varint,1,opt,name=slot,proto3,oneof" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
}

type BeaconStateRequest_BlockRoot struct {
	BlockRoot []byte `protobuf:"bytes,2,opt,name=block_root,json=blockRoot,proto3,oneof"`
}

func (*BeaconStateRequest_Slot) isBeaconStateRequest_QueryFilter() {}

func (*BeaconStateRequest_BlockRoot) isBeaconStateRequest_QueryFilter() {}

type BlockRequestByRoot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockRoot     []byte                 `protobuf:"bytes,1,opt,name=block_root,json=blockRoot,proto3" json:"block_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockRequestByRoot) Reset() {
	*x = BlockRequestByRoot{}
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockRequestByRoot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockRequestByRoot) ProtoMessage() {}

func (x *BlockRequestByRoot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockRequestByRoot.ProtoReflect.Descriptor instead.
func (*BlockRequestByRoot) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_debug_proto_rawDescGZIP(), []int{1}
}

func (x *BlockRequestByRoot) GetBlockRoot() []byte {
	if x != nil {
		return x.BlockRoot
	}
	return nil
}

type SSZResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Encoded       []byte                 `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSZResponse) Reset() {
	*x = SSZResponse{}
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSZResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSZResponse) ProtoMessage() {}

func (x *SSZResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSZResponse.ProtoReflect.Descriptor instead.
func (*SSZResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_debug_proto_rawDescGZIP(), []int{2}
}

func (x *SSZResponse) GetEncoded() []byte {
	if x != nil {
		return x.Encoded
	}
	return nil
}

type LoggingLevelRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Level         LoggingLevelRequest_Level `protobuf:"varint,1,opt,name=level,proto3,enum=theqrl.qrl.v1alpha1.LoggingLevelRequest_Level" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoggingLevelRequest) Reset() {
	*x = LoggingLevelRequest{}
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoggingLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoggingLevelRequest) ProtoMessage() {}

func (x *LoggingLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoggingLevelRequest.ProtoReflect.Descriptor instead.
func (*LoggingLevelRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_debug_proto_rawDescGZIP(), []int{3}
}

func (x *LoggingLevelRequest) GetLevel() LoggingLevelRequest_Level {
	if x != nil {
		return x.Level
	}
	return LoggingLevelRequest_INFO
}

type DebugPeerResponses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*DebugPeerResponse   `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugPeerResponses) Reset() {
	*x = DebugPeerResponses{}
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugPeerResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugPeerResponses) ProtoMessage() {}

func (x *DebugPeerResponses) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugPeerResponses.ProtoReflect.Descriptor instead.
func (*DebugPeerResponses) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_debug_proto_rawDescGZIP(), []int{4}
}

func (x *DebugPeerResponses) GetResponses() []*DebugPeerResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type DebugPeerResponse struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	ListeningAddresses []string                    `protobuf:"bytes,1,rep,name=listening_addresses,json=listeningAddresses,proto3" json:"listening_addresses,omitempty"`
	Direction          PeerDirection               `protobuf:"varint,2,opt,name=direction,proto3,enum=theqrl.qrl.v1alpha1.PeerDirection" json:"direction,omitempty"`
	ConnectionState    ConnectionState             `protobuf:"varint,3,opt,name=connection_state,json=connectionState,proto3,enum=theqrl.qrl.v1alpha1.ConnectionState" json:"connection_state,omitempty"`
	PeerId             string                      `protobuf:"bytes,4,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Qnr                string                      `protobuf:"bytes,5,opt,name=qnr,proto3" json:"qnr,omitempty"`
	PeerInfo           *DebugPeerResponse_PeerInfo `protobuf:"bytes,6,opt,name=peer_info,json=peerInfo,proto3" json:"peer_info,omitempty"`
	PeerStatus         *Status                     `protobuf:"bytes,7,opt,name=peer_status,json=peerStatus,proto3" json:"peer_status,omitempty"`
	LastUpdated        uint64                      `protobuf:"varint,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	ScoreInfo          *ScoreInfo                  `protobuf:"bytes,9,opt,name=score_info,json=scoreInfo,proto3" json:"score_info,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DebugPeerResponse) Reset() {
	*x = DebugPeerResponse{}
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugPeerResponse) ProtoMessage() {}

func (x *DebugPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugPeerResponse.ProtoReflect.Descriptor instead.
func (*DebugPeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_debug_proto_rawDescGZIP(), []int{5}
}

func (x *DebugPeerResponse) GetListeningAddresses() []string {
	if x != nil {
		return x.ListeningAddresses
	}
	return nil
}

func (x *DebugPeerResponse) GetDirection() PeerDirection {
	if x != nil {
		return x.Direction
	}
	return PeerDirection_UNKNOWN
}

func (x *DebugPeerResponse) GetConnectionState() ConnectionState {
	if x != nil {
		return x.ConnectionState
	}
	return ConnectionState_DISCONNECTED
}

func (x *DebugPeerResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *DebugPeerResponse) GetQnr() string {
	if x != nil {
		return x.Qnr
	}
	return ""
}

func (x *DebugPeerResponse) GetPeerInfo() *DebugPeerResponse_PeerInfo {
	if x != nil {
		return x.PeerInfo
	}
	return nil
}

func (x *DebugPeerResponse) GetPeerStatus() *Status {
	if x != nil {
		return x.PeerStatus
	}
	return nil
}

func (x *DebugPeerResponse) GetLastUpdated() uint64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *DebugPeerResponse) GetScoreInfo() *ScoreInfo {
	if x != nil {
		return x.ScoreInfo
	}
	return nil
}

type ScoreInfo struct {
	state              protoimpl.MessageState         `protogen:"open.v1"`
	OverallScore       float32                        `protobuf:"fixed32,1,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	ProcessedBlocks    uint64                         `protobuf:"varint,2,opt,name=processed_blocks,json=processedBlocks,proto3" json:"processed_blocks,omitempty"`
	BlockProviderScore float32                        `protobuf:"fixed32,3,opt,name=block_provider_score,json=blockProviderScore,proto3" json:"block_provider_score,omitempty"`
	TopicScores        map[string]*TopicScoreSnapshot `protobuf:"bytes,4,rep,name=topic_scores,json=topicScores,proto3" json:"topic_scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GossipScore        float32                        `protobuf:"fixed32,5,opt,name=gossip_score,json=gossipScore,proto3" json:"gossip_score,omitempty"`
	BehaviourPenalty   float32                        `protobuf:"fixed32,6,opt,name=behaviour_penalty,json=behaviourPenalty,proto3" json:"behaviour_penalty,omitempty"`
	ValidationError    string                         `protobuf:"bytes,7,opt,name=validation_error,json=validationError,proto3" json:"validation_error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScoreInfo) Reset() {
	*x = ScoreInfo{}
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreInfo) ProtoMessage() {}

func (x *ScoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreInfo.ProtoReflect.Descriptor instead.
func (*ScoreInfo) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_debug_proto_rawDescGZIP(), []int{6}
}

func (x *ScoreInfo) GetOverallScore() float32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *ScoreInfo) GetProcessedBlocks() uint64 {
	if x != nil {
		return x.ProcessedBlocks
	}
	return 0
}

func (x *ScoreInfo) GetBlockProviderScore() float32 {
	if x != nil {
		return x.BlockProviderScore
	}
	return 0
}

func (x *ScoreInfo) GetTopicScores() map[string]*TopicScoreSnapshot {
	if x != nil {
		return x.TopicScores
	}
	return nil
}

func (x *ScoreInfo) GetGossipScore() float32 {
	if x != nil {
		return x.GossipScore
	}
	return 0
}

func (x *ScoreInfo) GetBehaviourPenalty() float32 {
	if x != nil {
		return x.BehaviourPenalty
	}
	return 0
}

func (x *ScoreInfo) GetValidationError() string {
	if x != nil {
		return x.ValidationError
	}
	return ""
}

type TopicScoreSnapshot struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TimeInMesh               uint64                 `protobuf:"varint,1,opt,name=time_in_mesh,json=timeInMesh,proto3" json:"time_in_mesh,omitempty"`
	FirstMessageDeliveries   float32                `protobuf:"fixed32,2,opt,name=first_message_deliveries,json=firstMessageDeliveries,proto3" json:"first_message_deliveries,omitempty"`
	MeshMessageDeliveries    float32                `protobuf:"fixed32,3,opt,name=mesh_message_deliveries,json=meshMessageDeliveries,proto3" json:"mesh_message_deliveries,omitempty"`
	InvalidMessageDeliveries float32                `protobuf:"fixed32,4,opt,name=invalid_message_deliveries,json=invalidMessageDeliveries,proto3" json:"invalid_message_deliveries,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TopicScoreSnapshot) Reset() {
	*x = TopicScoreSnapshot{}
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicScoreSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicScoreSnapshot) ProtoMessage() {}

func (x *TopicScoreSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicScoreSnapshot.ProtoReflect.Descriptor instead.
func (*TopicScoreSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_debug_proto_rawDescGZIP(), []int{7}
}

func (x *TopicScoreSnapshot) GetTimeInMesh() uint64 {
	if x != nil {
		return x.TimeInMesh
	}
	return 0
}

func (x *TopicScoreSnapshot) GetFirstMessageDeliveries() float32 {
	if x != nil {
		return x.FirstMessageDeliveries
	}
	return 0
}

func (x *TopicScoreSnapshot) GetMeshMessageDeliveries() float32 {
	if x != nil {
		return x.MeshMessageDeliveries
	}
	return 0
}

func (x *TopicScoreSnapshot) GetInvalidMessageDeliveries() float32 {
	if x != nil {
		return x.InvalidMessageDeliveries
	}
	return 0
}

type DebugPeerResponse_PeerInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MetadataV1      *MetaDataV1            `protobuf:"bytes,1,opt,name=metadataV1,proto3" json:"metadataV1,omitempty"`
	Protocols       []string               `protobuf:"bytes,2,rep,name=protocols,proto3" json:"protocols,omitempty"`
	FaultCount      uint64                 `protobuf:"varint,3,opt,name=fault_count,json=faultCount,proto3" json:"fault_count,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	PeerLatency     uint64                 `protobuf:"varint,6,opt,name=peer_latency,json=peerLatency,proto3" json:"peer_latency,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DebugPeerResponse_PeerInfo) Reset() {
	*x = DebugPeerResponse_PeerInfo{}
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugPeerResponse_PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugPeerResponse_PeerInfo) ProtoMessage() {}

func (x *DebugPeerResponse_PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_debug_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugPeerResponse_PeerInfo.ProtoReflect.Descriptor instead.
func (*DebugPeerResponse_PeerInfo) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_debug_proto_rawDescGZIP(), []int{5, 0}
}

func (x *DebugPeerResponse_PeerInfo) GetMetadataV1() *MetaDataV1 {
	if x != nil {
		return x.MetadataV1
	}
	return nil
}

func (x *DebugPeerResponse_PeerInfo) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *DebugPeerResponse_PeerInfo) GetFaultCount() uint64 {
	if x != nil {
		return x.FaultCount
	}
	return 0
}

func (x *DebugPeerResponse_PeerInfo) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *DebugPeerResponse_PeerInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *DebugPeerResponse_PeerInfo) GetPeerLatency() uint64 {
	if x != nil {
		return x.PeerLatency
	}
	return 0
}

var File_proto_qrysm_v1alpha1_debug_proto protoreflect.FileDescriptor

const file_proto_qrysm_v1alpha1_debug_proto_rawDesc = "" +
	"\n" +
	" proto/qrysm/v1alpha1/debug.proto\x12\x13theqrl.qrl.v1alpha1\x1a\x1bproto/qrl/ext/options.proto\x1a\x1fproto/qrysm/v1alpha1/node.proto\x1a'proto/qrysm/v1alpha1/p2p_messages.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x98\x01\n" +
	"\x12BeaconStateRequest\x12Q\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotH\x00R\x04slot\x12\x1f\n" +
	"\n" +
	"block_root\x18\x02 \x01(\fH\x00R\tblockRootB\x0e\n" +
	"\fquery_filter\"3\n" +
	"\x12BlockRequestByRoot\x12\x1d\n" +
	"\n" +
	"block_root\x18\x01 \x01(\fR\tblockRoot\"'\n" +
	"\vSSZResponse\x12\x18\n" +
	"\aencoded\x18\x01 \x01(\fR\aencoded\"\x84\x01\n" +
	"\x13LoggingLevelRequest\x12D\n" +
	"\x05level\x18\x01 \x01(\x0e2..theqrl.qrl.v1alpha1.LoggingLevelRequest.LevelR\x05level\"'\n" +
	"\x05Level\x12\b\n" +
	"\x04INFO\x10\x00\x12\t\n" +
	"\x05DEBUG\x10\x01\x12\t\n" +
	"\x05TRACE\x10\x02\"Z\n" +
	"\x12DebugPeerResponses\x12D\n" +
	"\tresponses\x18\x01 \x03(\v2&.theqrl.qrl.v1alpha1.DebugPeerResponseR\tresponses\"\xf0\x05\n" +
	"\x11DebugPeerResponse\x12/\n" +
	"\x13listening_addresses\x18\x01 \x03(\tR\x12listeningAddresses\x12@\n" +
	"\tdirection\x18\x02 \x01(\x0e2\".theqrl.qrl.v1alpha1.PeerDirectionR\tdirection\x12O\n" +
	"\x10connection_state\x18\x03 \x01(\x0e2$.theqrl.qrl.v1alpha1.ConnectionStateR\x0fconnectionState\x12\x17\n" +
	"\apeer_id\x18\x04 \x01(\tR\x06peerId\x12\x10\n" +
	"\x03qnr\x18\x05 \x01(\tR\x03qnr\x12L\n" +
	"\tpeer_info\x18\x06 \x01(\v2/.theqrl.qrl.v1alpha1.DebugPeerResponse.PeerInfoR\bpeerInfo\x12<\n" +
	"\vpeer_status\x18\a \x01(\v2\x1b.theqrl.qrl.v1alpha1.StatusR\n" +
	"peerStatus\x12!\n" +
	"\flast_updated\x18\b \x01(\x04R\vlastUpdated\x12=\n" +
	"\n" +
	"score_info\x18\t \x01(\v2\x1e.theqrl.qrl.v1alpha1.ScoreInfoR\tscoreInfo\x1a\xfd\x01\n" +
	"\bPeerInfo\x12?\n" +
	"\n" +
	"metadataV1\x18\x01 \x01(\v2\x1f.theqrl.qrl.v1alpha1.MetaDataV1R\n" +
	"metadataV1\x12\x1c\n" +
	"\tprotocols\x18\x02 \x03(\tR\tprotocols\x12\x1f\n" +
	"\vfault_count\x18\x03 \x01(\x04R\n" +
	"faultCount\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\tR\x0fprotocolVersion\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12!\n" +
	"\fpeer_latency\x18\x06 \x01(\x04R\vpeerLatency\"\xc5\x03\n" +
	"\tScoreInfo\x12#\n" +
	"\roverall_score\x18\x01 \x01(\x02R\foverallScore\x12)\n" +
	"\x10processed_blocks\x18\x02 \x01(\x04R\x0fprocessedBlocks\x120\n" +
	"\x14block_provider_score\x18\x03 \x01(\x02R\x12blockProviderScore\x12R\n" +
	"\ftopic_scores\x18\x04 \x03(\v2/.theqrl.qrl.v1alpha1.ScoreInfo.TopicScoresEntryR\vtopicScores\x12!\n" +
	"\fgossip_score\x18\x05 \x01(\x02R\vgossipScore\x12+\n" +
	"\x11behaviour_penalty\x18\x06 \x01(\x02R\x10behaviourPenalty\x12)\n" +
	"\x10validation_error\x18\a \x01(\tR\x0fvalidationError\x1ag\n" +
	"\x10TopicScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12=\n" +
	"\x05value\x18\x02 \x01(\v2'.theqrl.qrl.v1alpha1.TopicScoreSnapshotR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x12TopicScoreSnapshot\x12 \n" +
	"\ftime_in_mesh\x18\x01 \x01(\x04R\n" +
	"timeInMesh\x128\n" +
	"\x18first_message_deliveries\x18\x02 \x01(\x02R\x16firstMessageDeliveries\x126\n" +
	"\x17mesh_message_deliveries\x18\x03 \x01(\x02R\x15meshMessageDeliveries\x12<\n" +
	"\x1ainvalid_message_deliveries\x18\x04 \x01(\x02R\x18invalidMessageDeliveries2\xe3\x04\n" +
	"\x05Debug\x12~\n" +
	"\x0eGetBeaconState\x12'.theqrl.qrl.v1alpha1.BeaconStateRequest\x1a .theqrl.qrl.v1alpha1.SSZResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/qrl/v1alpha1/debug/state\x12x\n" +
	"\bGetBlock\x12'.theqrl.qrl.v1alpha1.BlockRequestByRoot\x1a .theqrl.qrl.v1alpha1.SSZResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/qrl/v1alpha1/debug/block\x12x\n" +
	"\x0fSetLoggingLevel\x12(.theqrl.qrl.v1alpha1.LoggingLevelRequest\x1a\x16.google.protobuf.Empty\"#\x82\xd3\xe4\x93\x02\x1d\"\x1b/qrl/v1alpha1/debug/logging\x12o\n" +
	"\tListPeers\x12\x16.google.protobuf.Empty\x1a'.theqrl.qrl.v1alpha1.DebugPeerResponses\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/qrl/v1alpha1/debug/peers\x12u\n" +
	"\aGetPeer\x12 .theqrl.qrl.v1alpha1.PeerRequest\x1a&.theqrl.qrl.v1alpha1.DebugPeerResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/qrl/v1alpha1/debug/peerB\x85\x01\n" +
	"\x17org.theqrl.qrl.v1alpha1B\n" +
	"DebugProtoP\x01Z0github.com/theQRL/qrysm/proto/qrysm/v1alpha1;qrl\xaa\x02\x13TheQRL.QRL.V1alpha1\xca\x02\x13TheQRL\\QRL\\v1alpha1b\x06proto3"

var (
	file_proto_qrysm_v1alpha1_debug_proto_rawDescOnce sync.Once
	file_proto_qrysm_v1alpha1_debug_proto_rawDescData []byte
)

func file_proto_qrysm_v1alpha1_debug_proto_rawDescGZIP() []byte {
	file_proto_qrysm_v1alpha1_debug_proto_rawDescOnce.Do(func() {
		file_proto_qrysm_v1alpha1_debug_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_debug_proto_rawDesc), len(file_proto_qrysm_v1alpha1_debug_proto_rawDesc)))
	})
	return file_proto_qrysm_v1alpha1_debug_proto_rawDescData
}

var file_proto_qrysm_v1alpha1_debug_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_qrysm_v1alpha1_debug_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_qrysm_v1alpha1_debug_proto_goTypes = []any{
	(LoggingLevelRequest_Level)(0),     // 0: theqrl.qrl.v1alpha1.LoggingLevelRequest.Level
	(*BeaconStateRequest)(nil),         // 1: theqrl.qrl.v1alpha1.BeaconStateRequest
	(*BlockRequestByRoot)(nil),         // 2: theqrl.qrl.v1alpha1.BlockRequestByRoot
	(*SSZResponse)(nil),                // 3: theqrl.qrl.v1alpha1.SSZResponse
	(*LoggingLevelRequest)(nil),        // 4: theqrl.qrl.v1alpha1.LoggingLevelRequest
	(*DebugPeerResponses)(nil),         // 5: theqrl.qrl.v1alpha1.DebugPeerResponses
	(*DebugPeerResponse)(nil),          // 6: theqrl.qrl.v1alpha1.DebugPeerResponse
	(*ScoreInfo)(nil),                  // 7: theqrl.qrl.v1alpha1.ScoreInfo
	(*TopicScoreSnapshot)(nil),         // 8: theqrl.qrl.v1alpha1.TopicScoreSnapshot
	(*DebugPeerResponse_PeerInfo)(nil), // 9: theqrl.qrl.v1alpha1.DebugPeerResponse.PeerInfo
	nil,                                // 10: theqrl.qrl.v1alpha1.ScoreInfo.TopicScoresEntry
	(PeerDirection)(0),                 // 11: theqrl.qrl.v1alpha1.PeerDirection
	(ConnectionState)(0),               // 12: theqrl.qrl.v1alpha1.ConnectionState
	(*Status)(nil),                     // 13: theqrl.qrl.v1alpha1.Status
	(*MetaDataV1)(nil),                 // 14: theqrl.qrl.v1alpha1.MetaDataV1
	(*emptypb.Empty)(nil),              // 15: google.protobuf.Empty
	(*PeerRequest)(nil),                // 16: theqrl.qrl.v1alpha1.PeerRequest
}
var file_proto_qrysm_v1alpha1_debug_proto_depIdxs = []int32{
	0,  // 0: theqrl.qrl.v1alpha1.LoggingLevelRequest.level:type_name -> theqrl.qrl.v1alpha1.LoggingLevelRequest.Level
	6,  // 1: theqrl.qrl.v1alpha1.DebugPeerResponses.responses:type_name -> theqrl.qrl.v1alpha1.DebugPeerResponse
	11, // 2: theqrl.qrl.v1alpha1.DebugPeerResponse.direction:type_name -> theqrl.qrl.v1alpha1.PeerDirection
	12, // 3: theqrl.qrl.v1alpha1.DebugPeerResponse.connection_state:type_name -> theqrl.qrl.v1alpha1.ConnectionState
	9,  // 4: theqrl.qrl.v1alpha1.DebugPeerResponse.peer_info:type_name -> theqrl.qrl.v1alpha1.DebugPeerResponse.PeerInfo
	13, // 5: theqrl.qrl.v1alpha1.DebugPeerResponse.peer_status:type_name -> theqrl.qrl.v1alpha1.Status
	7,  // 6: theqrl.qrl.v1alpha1.DebugPeerResponse.score_info:type_name -> theqrl.qrl.v1alpha1.ScoreInfo
	10, // 7: theqrl.qrl.v1alpha1.ScoreInfo.topic_scores:type_name -> theqrl.qrl.v1alpha1.ScoreInfo.TopicScoresEntry
	14, // 8: theqrl.qrl.v1alpha1.DebugPeerResponse.PeerInfo.metadataV1:type_name -> theqrl.qrl.v1alpha1.MetaDataV1
	8,  // 9: theqrl.qrl.v1alpha1.ScoreInfo.TopicScoresEntry.value:type_name -> theqrl.qrl.v1alpha1.TopicScoreSnapshot
	1,  // 10: theqrl.qrl.v1alpha1.Debug.GetBeaconState:input_type -> theqrl.qrl.v1alpha1.BeaconStateRequest
	2,  // 11: theqrl.qrl.v1alpha1.Debug.GetBlock:input_type -> theqrl.qrl.v1alpha1.BlockRequestByRoot
	4,  // 12: theqrl.qrl.v1alpha1.Debug.SetLoggingLevel:input_type -> theqrl.qrl.v1alpha1.LoggingLevelRequest
	15, // 13: theqrl.qrl.v1alpha1.Debug.ListPeers:input_type -> google.protobuf.Empty
	16, // 14: theqrl.qrl.v1alpha1.Debug.GetPeer:input_type -> theqrl.qrl.v1alpha1.PeerRequest
	3,  // 15: theqrl.qrl.v1alpha1.Debug.GetBeaconState:output_type -> theqrl.qrl.v1alpha1.SSZResponse
	3,  // 16: theqrl.qrl.v1alpha1.Debug.GetBlock:output_type -> theqrl.qrl.v1alpha1.SSZResponse
	15, // 17: theqrl.qrl.v1alpha1.Debug.SetLoggingLevel:output_type -> google.protobuf.Empty
	5,  // 18: theqrl.qrl.v1alpha1.Debug.ListPeers:output_type -> theqrl.qrl.v1alpha1.DebugPeerResponses
	6,  // 19: theqrl.qrl.v1alpha1.Debug.GetPeer:output_type -> theqrl.qrl.v1alpha1.DebugPeerResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_qrysm_v1alpha1_debug_proto_init() }
func file_proto_qrysm_v1alpha1_debug_proto_init() {
	if File_proto_qrysm_v1alpha1_debug_proto != nil {
		return
	}
	file_proto_qrysm_v1alpha1_node_proto_init()
	file_proto_qrysm_v1alpha1_p2p_messages_proto_init()
	file_proto_qrysm_v1alpha1_debug_proto_msgTypes[0].OneofWrappers = []any{
		(*BeaconStateRequest_Slot)(nil),
		(*BeaconStateRequest_BlockRoot)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_debug_proto_rawDesc), len(file_proto_qrysm_v1alpha1_debug_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_qrysm_v1alpha1_debug_proto_goTypes,
		DependencyIndexes: file_proto_qrysm_v1alpha1_debug_proto_depIdxs,
		EnumInfos:         file_proto_qrysm_v1alpha1_debug_proto_enumTypes,
		MessageInfos:      file_proto_qrysm_v1alpha1_debug_proto_msgTypes,
	}.Build()
	File_proto_qrysm_v1alpha1_debug_proto = out.File
	file_proto_qrysm_v1alpha1_debug_proto_goTypes = nil
	file_proto_qrysm_v1alpha1_debug_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DebugClient is the client API for Debug service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DebugClient interface {
	GetBeaconState(ctx context.Context, in *BeaconStateRequest, opts ...grpc.CallOption) (*SSZResponse, error)
	GetBlock(ctx context.Context, in *BlockRequestByRoot, opts ...grpc.CallOption) (*SSZResponse, error)
	SetLoggingLevel(ctx context.Context, in *LoggingLevelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListPeers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DebugPeerResponses, error)
	GetPeer(ctx context.Context, in *PeerRequest, opts ...grpc.CallOption) (*DebugPeerResponse, error)
}

type debugClient struct {
	cc grpc.ClientConnInterface
}

func NewDebugClient(cc grpc.ClientConnInterface) DebugClient {
	return &debugClient{cc}
}

func (c *debugClient) GetBeaconState(ctx context.Context, in *BeaconStateRequest, opts ...grpc.CallOption) (*SSZResponse, error) {
	out := new(SSZResponse)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.v1alpha1.Debug/GetBeaconState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugClient) GetBlock(ctx context.Context, in *BlockRequestByRoot, opts ...grpc.CallOption) (*SSZResponse, error) {
	out := new(SSZResponse)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.v1alpha1.Debug/GetBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugClient) SetLoggingLevel(ctx context.Context, in *LoggingLevelRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.v1alpha1.Debug/SetLoggingLevel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugClient) ListPeers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DebugPeerResponses, error) {
	out := new(DebugPeerResponses)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.v1alpha1.Debug/ListPeers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *debugClient) GetPeer(ctx context.Context, in *PeerRequest, opts ...grpc.CallOption) (*DebugPeerResponse, error) {
	out := new(DebugPeerResponse)
	err := c.cc.Invoke(ctx, "/theqrl.qrl.v1alpha1.Debug/GetPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DebugServer is the server API for Debug service.
type DebugServer interface {
	GetBeaconState(context.Context, *BeaconStateRequest) (*SSZResponse, error)
	GetBlock(context.Context, *BlockRequestByRoot) (*SSZResponse, error)
	SetLoggingLevel(context.Context, *LoggingLevelRequest) (*emptypb.Empty, error)
	ListPeers(context.Context, *emptypb.Empty) (*DebugPeerResponses, error)
	GetPeer(context.Context, *PeerRequest) (*DebugPeerResponse, error)
}

// UnimplementedDebugServer can be embedded to have forward compatible implementations.
type UnimplementedDebugServer struct {
}

func (*UnimplementedDebugServer) GetBeaconState(context.Context, *BeaconStateRequest) (*SSZResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBeaconState not implemented")
}
func (*UnimplementedDebugServer) GetBlock(context.Context, *BlockRequestByRoot) (*SSZResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlock not implemented")
}
func (*UnimplementedDebugServer) SetLoggingLevel(context.Context, *LoggingLevelRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetLoggingLevel not implemented")
}
func (*UnimplementedDebugServer) ListPeers(context.Context, *emptypb.Empty) (*DebugPeerResponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPeers not implemented")
}
func (*UnimplementedDebugServer) GetPeer(context.Context, *PeerRequest) (*DebugPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeer not implemented")
}

func RegisterDebugServer(s *grpc.Server, srv DebugServer) {
	s.RegisterService(&_Debug_serviceDesc, srv)
}

func _Debug_GetBeaconState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeaconStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).GetBeaconState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.v1alpha1.Debug/GetBeaconState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).GetBeaconState(ctx, req.(*BeaconStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Debug_GetBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockRequestByRoot)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).GetBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.v1alpha1.Debug/GetBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).GetBlock(ctx, req.(*BlockRequestByRoot))
	}
	return interceptor(ctx, in, info, handler)
}

func _Debug_SetLoggingLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoggingLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).SetLoggingLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.v1alpha1.Debug/SetLoggingLevel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).SetLoggingLevel(ctx, req.(*LoggingLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Debug_ListPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).ListPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.v1alpha1.Debug/ListPeers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).ListPeers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Debug_GetPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DebugServer).GetPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/theqrl.qrl.v1alpha1.Debug/GetPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DebugServer).GetPeer(ctx, req.(*PeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Debug_serviceDesc = grpc.ServiceDesc{
	ServiceName: "theqrl.qrl.v1alpha1.Debug",
	HandlerType: (*DebugServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBeaconState",
			Handler:    _Debug_GetBeaconState_Handler,
		},
		{
			MethodName: "GetBlock",
			Handler:    _Debug_GetBlock_Handler,
		},
		{
			MethodName: "SetLoggingLevel",
			Handler:    _Debug_SetLoggingLevel_Handler,
		},
		{
			MethodName: "ListPeers",
			Handler:    _Debug_ListPeers_Handler,
		},
		{
			MethodName: "GetPeer",
			Handler:    _Debug_GetPeer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/qrysm/v1alpha1/debug.proto",
}
