// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrysm/v1alpha1/finalized_block_root_container.proto

package qrl

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FinalizedBlockRootContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentRoot    []byte                 `protobuf:"bytes,1,opt,name=parent_root,json=parentRoot,proto3" json:"parent_root,omitempty"`
	ChildRoot     []byte                 `protobuf:"bytes,2,opt,name=child_root,json=childRoot,proto3" json:"child_root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizedBlockRootContainer) Reset() {
	*x = FinalizedBlockRootContainer{}
	mi := &file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizedBlockRootContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizedBlockRootContainer) ProtoMessage() {}

func (x *FinalizedBlockRootContainer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizedBlockRootContainer.ProtoReflect.Descriptor instead.
func (*FinalizedBlockRootContainer) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_rawDescGZIP(), []int{0}
}

func (x *FinalizedBlockRootContainer) GetParentRoot() []byte {
	if x != nil {
		return x.ParentRoot
	}
	return nil
}

func (x *FinalizedBlockRootContainer) GetChildRoot() []byte {
	if x != nil {
		return x.ChildRoot
	}
	return nil
}

var File_proto_qrysm_v1alpha1_finalized_block_root_container_proto protoreflect.FileDescriptor

const file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_rawDesc = "" +
	"\n" +
	"9proto/qrysm/v1alpha1/finalized_block_root_container.proto\x12\x13theqrl.qrl.v1alpha1\"]\n" +
	"\x1bFinalizedBlockRootContainer\x12\x1f\n" +
	"\vparent_root\x18\x01 \x01(\fR\n" +
	"parentRoot\x12\x1d\n" +
	"\n" +
	"child_root\x18\x02 \x01(\fR\tchildRootB\x9b\x01\n" +
	"\x17org.theqrl.qrl.v1alpha1B FinalizedBlockRootContainerProtoP\x01Z0github.com/theQRL/qrysm/proto/qrysm/v1alpha1;qrl\xaa\x02\x13TheQRL.QRL.v1alpha1\xca\x02\x13TheQRL\\QRL\\v1alpha1b\x06proto3"

var (
	file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_rawDescOnce sync.Once
	file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_rawDescData []byte
)

func file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_rawDescGZIP() []byte {
	file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_rawDescOnce.Do(func() {
		file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_rawDesc), len(file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_rawDesc)))
	})
	return file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_rawDescData
}

var file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_goTypes = []any{
	(*FinalizedBlockRootContainer)(nil), // 0: theqrl.qrl.v1alpha1.FinalizedBlockRootContainer
}
var file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_init() }
func file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_init() {
	if File_proto_qrysm_v1alpha1_finalized_block_root_container_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_rawDesc), len(file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_goTypes,
		DependencyIndexes: file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_depIdxs,
		MessageInfos:      file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_msgTypes,
	}.Build()
	File_proto_qrysm_v1alpha1_finalized_block_root_container_proto = out.File
	file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_goTypes = nil
	file_proto_qrysm_v1alpha1_finalized_block_root_container_proto_depIdxs = nil
}
