// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrysm/v1alpha1/p2p_messages.proto

package qrl

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_go_bitfield "github.com/theQRL/go-bitfield"
	github_com_theQRL_qrysm_consensus_types_primitives "github.com/theQRL/qrysm/consensus-types/primitives"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status struct {
	state          protoimpl.MessageState                                   `protogen:"open.v1"`
	ForkDigest     []byte                                                   `protobuf:"bytes,1,opt,name=fork_digest,json=forkDigest,proto3" json:"fork_digest,omitempty" ssz-size:"4"`
	FinalizedRoot  []byte                                                   `protobuf:"bytes,2,opt,name=finalized_root,json=finalizedRoot,proto3" json:"finalized_root,omitempty" ssz-size:"32"`
	FinalizedEpoch github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,3,opt,name=finalized_epoch,json=finalizedEpoch,proto3" json:"finalized_epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	HeadRoot       []byte                                                   `protobuf:"bytes,4,opt,name=head_root,json=headRoot,proto3" json:"head_root,omitempty" ssz-size:"32"`
	HeadSlot       github_com_theQRL_qrysm_consensus_types_primitives.Slot  `protobuf:"varint,5,opt,name=head_slot,json=headSlot,proto3" json:"head_slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_qrysm_v1alpha1_p2p_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_p2p_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetForkDigest() []byte {
	if x != nil {
		return x.ForkDigest
	}
	return nil
}

func (x *Status) GetFinalizedRoot() []byte {
	if x != nil {
		return x.FinalizedRoot
	}
	return nil
}

func (x *Status) GetFinalizedEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.FinalizedEpoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

func (x *Status) GetHeadRoot() []byte {
	if x != nil {
		return x.HeadRoot
	}
	return nil
}

func (x *Status) GetHeadSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.HeadSlot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

type BeaconBlocksByRangeRequest struct {
	state         protoimpl.MessageState                                  `protogen:"open.v1"`
	StartSlot     github_com_theQRL_qrysm_consensus_types_primitives.Slot `protobuf:"varint,1,opt,name=start_slot,json=startSlot,proto3" json:"start_slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	Count         uint64                                                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Step          uint64                                                  `protobuf:"varint,3,opt,name=step,proto3" json:"step,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeaconBlocksByRangeRequest) Reset() {
	*x = BeaconBlocksByRangeRequest{}
	mi := &file_proto_qrysm_v1alpha1_p2p_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeaconBlocksByRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeaconBlocksByRangeRequest) ProtoMessage() {}

func (x *BeaconBlocksByRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_p2p_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeaconBlocksByRangeRequest.ProtoReflect.Descriptor instead.
func (*BeaconBlocksByRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDescGZIP(), []int{1}
}

func (x *BeaconBlocksByRangeRequest) GetStartSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.StartSlot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *BeaconBlocksByRangeRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *BeaconBlocksByRangeRequest) GetStep() uint64 {
	if x != nil {
		return x.Step
	}
	return 0
}

type QNRForkID struct {
	state             protoimpl.MessageState                                   `protogen:"open.v1"`
	CurrentForkDigest []byte                                                   `protobuf:"bytes,1,opt,name=current_fork_digest,json=currentForkDigest,proto3" json:"current_fork_digest,omitempty" ssz-size:"4"`
	NextForkVersion   []byte                                                   `protobuf:"bytes,2,opt,name=next_fork_version,json=nextForkVersion,proto3" json:"next_fork_version,omitempty" ssz-size:"4"`
	NextForkEpoch     github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,3,opt,name=next_fork_epoch,json=nextForkEpoch,proto3" json:"next_fork_epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QNRForkID) Reset() {
	*x = QNRForkID{}
	mi := &file_proto_qrysm_v1alpha1_p2p_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QNRForkID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QNRForkID) ProtoMessage() {}

func (x *QNRForkID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_p2p_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QNRForkID.ProtoReflect.Descriptor instead.
func (*QNRForkID) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDescGZIP(), []int{2}
}

func (x *QNRForkID) GetCurrentForkDigest() []byte {
	if x != nil {
		return x.CurrentForkDigest
	}
	return nil
}

func (x *QNRForkID) GetNextForkVersion() []byte {
	if x != nil {
		return x.NextForkVersion
	}
	return nil
}

func (x *QNRForkID) GetNextForkEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.NextForkEpoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

type MetaDataV1 struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	SeqNumber     uint64                                    `protobuf:"varint,1,opt,name=seq_number,json=seqNumber,proto3" json:"seq_number,omitempty"`
	Attnets       github_com_theQRL_go_bitfield.Bitvector64 `protobuf:"bytes,2,opt,name=attnets,proto3" json:"attnets,omitempty" cast-type:"github.com/theQRL/go-bitfield.Bitvector64" ssz-size:"8"`
	Syncnets      github_com_theQRL_go_bitfield.Bitvector4  `protobuf:"bytes,3,opt,name=syncnets,proto3" json:"syncnets,omitempty" cast-type:"github.com/theQRL/go-bitfield.Bitvector4" ssz-size:"1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaDataV1) Reset() {
	*x = MetaDataV1{}
	mi := &file_proto_qrysm_v1alpha1_p2p_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaDataV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaDataV1) ProtoMessage() {}

func (x *MetaDataV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_p2p_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaDataV1.ProtoReflect.Descriptor instead.
func (*MetaDataV1) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDescGZIP(), []int{3}
}

func (x *MetaDataV1) GetSeqNumber() uint64 {
	if x != nil {
		return x.SeqNumber
	}
	return 0
}

func (x *MetaDataV1) GetAttnets() github_com_theQRL_go_bitfield.Bitvector64 {
	if x != nil {
		return x.Attnets
	}
	return github_com_theQRL_go_bitfield.Bitvector64(nil)
}

func (x *MetaDataV1) GetSyncnets() github_com_theQRL_go_bitfield.Bitvector4 {
	if x != nil {
		return x.Syncnets
	}
	return github_com_theQRL_go_bitfield.Bitvector4(nil)
}

var File_proto_qrysm_v1alpha1_p2p_messages_proto protoreflect.FileDescriptor

const file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDesc = "" +
	"\n" +
	"'proto/qrysm/v1alpha1/p2p_messages.proto\x12\x13theqrl.qrl.v1alpha1\x1a google/protobuf/descriptor.proto\x1a\x1bproto/qrl/ext/options.proto\"\xc5\x02\n" +
	"\x06Status\x12&\n" +
	"\vfork_digest\x18\x01 \x01(\fB\x05\x8a\xb5\x18\x014R\n" +
	"forkDigest\x12-\n" +
	"\x0efinalized_root\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\rfinalizedRoot\x12e\n" +
	"\x0ffinalized_epoch\x18\x03 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x0efinalizedEpoch\x12#\n" +
	"\thead_root\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\bheadRoot\x12X\n" +
	"\thead_slot\x18\x05 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\bheadSlot\"\xa2\x01\n" +
	"\x1aBeaconBlocksByRangeRequest\x12Z\n" +
	"\n" +
	"start_slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\tstartSlot\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12\x12\n" +
	"\x04step\x18\x03 \x01(\x04R\x04step\"\xdb\x01\n" +
	"\tQNRForkID\x125\n" +
	"\x13current_fork_digest\x18\x01 \x01(\fB\x05\x8a\xb5\x18\x014R\x11currentForkDigest\x121\n" +
	"\x11next_fork_version\x18\x02 \x01(\fB\x05\x8a\xb5\x18\x014R\x0fnextForkVersion\x12d\n" +
	"\x0fnext_fork_epoch\x18\x03 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\rnextForkEpoch\"\xc8\x01\n" +
	"\n" +
	"MetaDataV1\x12\x1d\n" +
	"\n" +
	"seq_number\x18\x01 \x01(\x04R\tseqNumber\x12L\n" +
	"\aattnets\x18\x02 \x01(\fB2\x82\xb5\x18)github.com/theQRL/go-bitfield.Bitvector64\x8a\xb5\x18\x018R\aattnets\x12M\n" +
	"\bsyncnets\x18\x03 \x01(\fB1\x82\xb5\x18(github.com/theQRL/go-bitfield.Bitvector4\x8a\xb5\x18\x011R\bsyncnetsB\x8b\x01\n" +
	"\x17org.theqrl.qrl.v1alpha1B\x10P2PMessagesProtoP\x01Z0github.com/theQRL/qrysm/proto/qrysm/v1alpha1;qrl\xaa\x02\x13TheQRL.QRL.V1alpha1\xca\x02\x13TheQRL\\QRL\\v1alpha1b\x06proto3"

var (
	file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDescOnce sync.Once
	file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDescData []byte
)

func file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDescGZIP() []byte {
	file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDescOnce.Do(func() {
		file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDesc), len(file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDesc)))
	})
	return file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDescData
}

var file_proto_qrysm_v1alpha1_p2p_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_qrysm_v1alpha1_p2p_messages_proto_goTypes = []any{
	(*Status)(nil),                     // 0: theqrl.qrl.v1alpha1.Status
	(*BeaconBlocksByRangeRequest)(nil), // 1: theqrl.qrl.v1alpha1.BeaconBlocksByRangeRequest
	(*QNRForkID)(nil),                  // 2: theqrl.qrl.v1alpha1.QNRForkID
	(*MetaDataV1)(nil),                 // 3: theqrl.qrl.v1alpha1.MetaDataV1
}
var file_proto_qrysm_v1alpha1_p2p_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_qrysm_v1alpha1_p2p_messages_proto_init() }
func file_proto_qrysm_v1alpha1_p2p_messages_proto_init() {
	if File_proto_qrysm_v1alpha1_p2p_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDesc), len(file_proto_qrysm_v1alpha1_p2p_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrysm_v1alpha1_p2p_messages_proto_goTypes,
		DependencyIndexes: file_proto_qrysm_v1alpha1_p2p_messages_proto_depIdxs,
		MessageInfos:      file_proto_qrysm_v1alpha1_p2p_messages_proto_msgTypes,
	}.Build()
	File_proto_qrysm_v1alpha1_p2p_messages_proto = out.File
	file_proto_qrysm_v1alpha1_p2p_messages_proto_goTypes = nil
	file_proto_qrysm_v1alpha1_p2p_messages_proto_depIdxs = nil
}
