// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrysm/v1alpha1/slasher.proto

package qrl

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_qrysm_consensus_types_primitives "github.com/theQRL/qrysm/consensus-types/primitives"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HighestAttestation struct {
	state              protoimpl.MessageState                                   `protogen:"open.v1"`
	ValidatorIndex     uint64                                                   `protobuf:"varint,1,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty"`
	HighestSourceEpoch github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,2,opt,name=highest_source_epoch,json=highestSourceEpoch,proto3" json:"highest_source_epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	HighestTargetEpoch github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,3,opt,name=highest_target_epoch,json=highestTargetEpoch,proto3" json:"highest_target_epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HighestAttestation) Reset() {
	*x = HighestAttestation{}
	mi := &file_proto_qrysm_v1alpha1_slasher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HighestAttestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HighestAttestation) ProtoMessage() {}

func (x *HighestAttestation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_slasher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HighestAttestation.ProtoReflect.Descriptor instead.
func (*HighestAttestation) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_slasher_proto_rawDescGZIP(), []int{0}
}

func (x *HighestAttestation) GetValidatorIndex() uint64 {
	if x != nil {
		return x.ValidatorIndex
	}
	return 0
}

func (x *HighestAttestation) GetHighestSourceEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.HighestSourceEpoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

func (x *HighestAttestation) GetHighestTargetEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.HighestTargetEpoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

var File_proto_qrysm_v1alpha1_slasher_proto protoreflect.FileDescriptor

const file_proto_qrysm_v1alpha1_slasher_proto_rawDesc = "" +
	"\n" +
	"\"proto/qrysm/v1alpha1/slasher.proto\x12\x13theqrl.qrl.v1alpha1\x1a\x1bproto/qrl/ext/options.proto\"\x9d\x02\n" +
	"\x12HighestAttestation\x12'\n" +
	"\x0fvalidator_index\x18\x01 \x01(\x04R\x0evalidatorIndex\x12n\n" +
	"\x14highest_source_epoch\x18\x02 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x12highestSourceEpoch\x12n\n" +
	"\x14highest_target_epoch\x18\x03 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x12highestTargetEpochB\x87\x01\n" +
	"\x17org.theqrl.qrl.v1alpha1B\fSlasherProtoP\x01Z0github.com/theQRL/qrysm/proto/qrysm/v1alpha1;qrl\xaa\x02\x13TheQRL.QRL.V1alpha1\xca\x02\x13TheQRL\\QRL\\v1alpha1b\x06proto3"

var (
	file_proto_qrysm_v1alpha1_slasher_proto_rawDescOnce sync.Once
	file_proto_qrysm_v1alpha1_slasher_proto_rawDescData []byte
)

func file_proto_qrysm_v1alpha1_slasher_proto_rawDescGZIP() []byte {
	file_proto_qrysm_v1alpha1_slasher_proto_rawDescOnce.Do(func() {
		file_proto_qrysm_v1alpha1_slasher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_slasher_proto_rawDesc), len(file_proto_qrysm_v1alpha1_slasher_proto_rawDesc)))
	})
	return file_proto_qrysm_v1alpha1_slasher_proto_rawDescData
}

var file_proto_qrysm_v1alpha1_slasher_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_qrysm_v1alpha1_slasher_proto_goTypes = []any{
	(*HighestAttestation)(nil), // 0: theqrl.qrl.v1alpha1.HighestAttestation
}
var file_proto_qrysm_v1alpha1_slasher_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_qrysm_v1alpha1_slasher_proto_init() }
func file_proto_qrysm_v1alpha1_slasher_proto_init() {
	if File_proto_qrysm_v1alpha1_slasher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_slasher_proto_rawDesc), len(file_proto_qrysm_v1alpha1_slasher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrysm_v1alpha1_slasher_proto_goTypes,
		DependencyIndexes: file_proto_qrysm_v1alpha1_slasher_proto_depIdxs,
		MessageInfos:      file_proto_qrysm_v1alpha1_slasher_proto_msgTypes,
	}.Build()
	File_proto_qrysm_v1alpha1_slasher_proto = out.File
	file_proto_qrysm_v1alpha1_slasher_proto_goTypes = nil
	file_proto_qrysm_v1alpha1_slasher_proto_depIdxs = nil
}
