// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrysm/v1alpha1/sync_committee.proto

package qrl

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_go_bitfield "github.com/theQRL/go-bitfield"
	github_com_theQRL_qrysm_consensus_types_primitives "github.com/theQRL/qrysm/consensus-types/primitives"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncCommitteeMessage struct {
	state          protoimpl.MessageState                                            `protogen:"open.v1"`
	Slot           github_com_theQRL_qrysm_consensus_types_primitives.Slot           `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	BlockRoot      []byte                                                            `protobuf:"bytes,2,opt,name=block_root,json=blockRoot,proto3" json:"block_root,omitempty" ssz-size:"32"`
	ValidatorIndex github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,3,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	Signature      []byte                                                            `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty" ssz-size:"4627"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncCommitteeMessage) Reset() {
	*x = SyncCommitteeMessage{}
	mi := &file_proto_qrysm_v1alpha1_sync_committee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCommitteeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCommitteeMessage) ProtoMessage() {}

func (x *SyncCommitteeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_sync_committee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCommitteeMessage.ProtoReflect.Descriptor instead.
func (*SyncCommitteeMessage) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_sync_committee_proto_rawDescGZIP(), []int{0}
}

func (x *SyncCommitteeMessage) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *SyncCommitteeMessage) GetBlockRoot() []byte {
	if x != nil {
		return x.BlockRoot
	}
	return nil
}

func (x *SyncCommitteeMessage) GetValidatorIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.ValidatorIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

func (x *SyncCommitteeMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SyncCommitteeContribution struct {
	state             protoimpl.MessageState                                  `protogen:"open.v1"`
	Slot              github_com_theQRL_qrysm_consensus_types_primitives.Slot `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	BlockRoot         []byte                                                  `protobuf:"bytes,2,opt,name=block_root,json=blockRoot,proto3" json:"block_root,omitempty" ssz-size:"32"`
	SubcommitteeIndex uint64                                                  `protobuf:"varint,3,opt,name=subcommittee_index,json=subcommitteeIndex,proto3" json:"subcommittee_index,omitempty"`
	AggregationBits   github_com_theQRL_go_bitfield.Bitvector128              `protobuf:"bytes,4,opt,name=aggregation_bits,json=aggregationBits,proto3" json:"aggregation_bits,omitempty" cast-type:"github.com/theQRL/go-bitfield.Bitvector128" ssz-size:"16"`
	Signatures        [][]byte                                                `protobuf:"bytes,5,rep,name=signatures,proto3" json:"signatures,omitempty" ssz-max:"128" ssz-size:"?,4627"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncCommitteeContribution) Reset() {
	*x = SyncCommitteeContribution{}
	mi := &file_proto_qrysm_v1alpha1_sync_committee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCommitteeContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCommitteeContribution) ProtoMessage() {}

func (x *SyncCommitteeContribution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_sync_committee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCommitteeContribution.ProtoReflect.Descriptor instead.
func (*SyncCommitteeContribution) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_sync_committee_proto_rawDescGZIP(), []int{1}
}

func (x *SyncCommitteeContribution) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *SyncCommitteeContribution) GetBlockRoot() []byte {
	if x != nil {
		return x.BlockRoot
	}
	return nil
}

func (x *SyncCommitteeContribution) GetSubcommitteeIndex() uint64 {
	if x != nil {
		return x.SubcommitteeIndex
	}
	return 0
}

func (x *SyncCommitteeContribution) GetAggregationBits() github_com_theQRL_go_bitfield.Bitvector128 {
	if x != nil {
		return x.AggregationBits
	}
	return github_com_theQRL_go_bitfield.Bitvector128(nil)
}

func (x *SyncCommitteeContribution) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type ContributionAndProof struct {
	state           protoimpl.MessageState                                            `protogen:"open.v1"`
	AggregatorIndex github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,1,opt,name=aggregator_index,json=aggregatorIndex,proto3" json:"aggregator_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	Contribution    *SyncCommitteeContribution                                        `protobuf:"bytes,2,opt,name=contribution,proto3" json:"contribution,omitempty"`
	SelectionProof  []byte                                                            `protobuf:"bytes,3,opt,name=selection_proof,json=selectionProof,proto3" json:"selection_proof,omitempty" ssz-size:"4627"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContributionAndProof) Reset() {
	*x = ContributionAndProof{}
	mi := &file_proto_qrysm_v1alpha1_sync_committee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContributionAndProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionAndProof) ProtoMessage() {}

func (x *ContributionAndProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_sync_committee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionAndProof.ProtoReflect.Descriptor instead.
func (*ContributionAndProof) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_sync_committee_proto_rawDescGZIP(), []int{2}
}

func (x *ContributionAndProof) GetAggregatorIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.AggregatorIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

func (x *ContributionAndProof) GetContribution() *SyncCommitteeContribution {
	if x != nil {
		return x.Contribution
	}
	return nil
}

func (x *ContributionAndProof) GetSelectionProof() []byte {
	if x != nil {
		return x.SelectionProof
	}
	return nil
}

type SignedContributionAndProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ContributionAndProof  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty" ssz-size:"4627"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedContributionAndProof) Reset() {
	*x = SignedContributionAndProof{}
	mi := &file_proto_qrysm_v1alpha1_sync_committee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedContributionAndProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedContributionAndProof) ProtoMessage() {}

func (x *SignedContributionAndProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrysm_v1alpha1_sync_committee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedContributionAndProof.ProtoReflect.Descriptor instead.
func (*SignedContributionAndProof) Descriptor() ([]byte, []int) {
	return file_proto_qrysm_v1alpha1_sync_committee_proto_rawDescGZIP(), []int{3}
}

func (x *SignedContributionAndProof) GetMessage() *ContributionAndProof {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedContributionAndProof) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_proto_qrysm_v1alpha1_sync_committee_proto protoreflect.FileDescriptor

const file_proto_qrysm_v1alpha1_sync_committee_proto_rawDesc = "" +
	"\n" +
	")proto/qrysm/v1alpha1/sync_committee.proto\x12\x13theqrl.qrl.v1alpha1\x1a\x1bproto/qrl/ext/options.proto\"\xa6\x02\n" +
	"\x14SyncCommitteeMessage\x12O\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12%\n" +
	"\n" +
	"block_root\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\tblockRoot\x12n\n" +
	"\x0fvalidator_index\x18\x03 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\x0evalidatorIndex\x12&\n" +
	"\tsignature\x18\x04 \x01(\fB\b\x8a\xb5\x18\x044627R\tsignature\"\xd6\x02\n" +
	"\x19SyncCommitteeContribution\x12O\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12%\n" +
	"\n" +
	"block_root\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\tblockRoot\x12-\n" +
	"\x12subcommittee_index\x18\x03 \x01(\x04R\x11subcommitteeIndex\x12_\n" +
	"\x10aggregation_bits\x18\x04 \x01(\fB4\x82\xb5\x18*github.com/theQRL/go-bitfield.Bitvector128\x8a\xb5\x18\x0216R\x0faggregationBits\x121\n" +
	"\n" +
	"signatures\x18\x05 \x03(\fB\x11\x8a\xb5\x18\x06?,4627\x92\xb5\x18\x03128R\n" +
	"signatures\"\x8f\x02\n" +
	"\x14ContributionAndProof\x12p\n" +
	"\x10aggregator_index\x18\x01 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\x0faggregatorIndex\x12R\n" +
	"\fcontribution\x18\x02 \x01(\v2..theqrl.qrl.v1alpha1.SyncCommitteeContributionR\fcontribution\x121\n" +
	"\x0fselection_proof\x18\x03 \x01(\fB\b\x8a\xb5\x18\x044627R\x0eselectionProof\"\x89\x01\n" +
	"\x1aSignedContributionAndProof\x12C\n" +
	"\amessage\x18\x01 \x01(\v2).theqrl.qrl.v1alpha1.ContributionAndProofR\amessage\x12&\n" +
	"\tsignature\x18\x02 \x01(\fB\b\x8a\xb5\x18\x044627R\tsignatureB\x87\x01\n" +
	"\x17org.theqrl.qrl.v1alpha1B\x12SyncCommitteeProtoP\x01Z0github.com/theQRL/qrysm/proto/qrysm/v1alpha1;qrl\xaa\x02\rTheQRL.QRL.V1\xca\x02\x13TheQRL\\QRL\\v1alpha1b\x06proto3"

var (
	file_proto_qrysm_v1alpha1_sync_committee_proto_rawDescOnce sync.Once
	file_proto_qrysm_v1alpha1_sync_committee_proto_rawDescData []byte
)

func file_proto_qrysm_v1alpha1_sync_committee_proto_rawDescGZIP() []byte {
	file_proto_qrysm_v1alpha1_sync_committee_proto_rawDescOnce.Do(func() {
		file_proto_qrysm_v1alpha1_sync_committee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_sync_committee_proto_rawDesc), len(file_proto_qrysm_v1alpha1_sync_committee_proto_rawDesc)))
	})
	return file_proto_qrysm_v1alpha1_sync_committee_proto_rawDescData
}

var file_proto_qrysm_v1alpha1_sync_committee_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_qrysm_v1alpha1_sync_committee_proto_goTypes = []any{
	(*SyncCommitteeMessage)(nil),       // 0: theqrl.qrl.v1alpha1.SyncCommitteeMessage
	(*SyncCommitteeContribution)(nil),  // 1: theqrl.qrl.v1alpha1.SyncCommitteeContribution
	(*ContributionAndProof)(nil),       // 2: theqrl.qrl.v1alpha1.ContributionAndProof
	(*SignedContributionAndProof)(nil), // 3: theqrl.qrl.v1alpha1.SignedContributionAndProof
}
var file_proto_qrysm_v1alpha1_sync_committee_proto_depIdxs = []int32{
	1, // 0: theqrl.qrl.v1alpha1.ContributionAndProof.contribution:type_name -> theqrl.qrl.v1alpha1.SyncCommitteeContribution
	2, // 1: theqrl.qrl.v1alpha1.SignedContributionAndProof.message:type_name -> theqrl.qrl.v1alpha1.ContributionAndProof
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_qrysm_v1alpha1_sync_committee_proto_init() }
func file_proto_qrysm_v1alpha1_sync_committee_proto_init() {
	if File_proto_qrysm_v1alpha1_sync_committee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrysm_v1alpha1_sync_committee_proto_rawDesc), len(file_proto_qrysm_v1alpha1_sync_committee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrysm_v1alpha1_sync_committee_proto_goTypes,
		DependencyIndexes: file_proto_qrysm_v1alpha1_sync_committee_proto_depIdxs,
		MessageInfos:      file_proto_qrysm_v1alpha1_sync_committee_proto_msgTypes,
	}.Build()
	File_proto_qrysm_v1alpha1_sync_committee_proto = out.File
	file_proto_qrysm_v1alpha1_sync_committee_proto_goTypes = nil
	file_proto_qrysm_v1alpha1_sync_committee_proto_depIdxs = nil
}
