package util

import (
	"context"
	"sync"
	"testing"

	"github.com/pkg/errors"
	"github.com/theQRL/qrysm/beacon-chain/core/helpers"
	"github.com/theQRL/qrysm/beacon-chain/core/signing"
	"github.com/theQRL/qrysm/beacon-chain/core/time"
	"github.com/theQRL/qrysm/beacon-chain/core/transition"
	"github.com/theQRL/qrysm/beacon-chain/state"
	fieldparams "github.com/theQRL/qrysm/config/fieldparams"
	"github.com/theQRL/qrysm/config/params"
	"github.com/theQRL/qrysm/consensus-types/blocks"
	"github.com/theQRL/qrysm/consensus-types/interfaces"
	"github.com/theQRL/qrysm/consensus-types/primitives"
	"github.com/theQRL/qrysm/crypto/ml_dsa_87"
	"github.com/theQRL/qrysm/crypto/rand"
	"github.com/theQRL/qrysm/crypto/randao"
	"github.com/theQRL/qrysm/encoding/bytesutil"
	qrysmpb "github.com/theQRL/qrysm/proto/qrysm/v1alpha1"
)

// TestRandaoOnionLayers is the RANDAO hash-onion length used for deposits
// generated by this package. It is deliberately short: the state transition
// only checks one hash per block, so the length is a validator-side choice,
// and short onions keep test genesis generation cheap.
const TestRandaoOnionLayers uint64 = 256

// randaoOnions caches test onions by (seed, layers).
var randaoOnions sync.Map

type randaoOnionKey struct {
	seed   [fieldparams.MLDSA87SeedLength]byte
	layers uint64
}

// TestRandaoOnion returns the cached hash onion of the given length for key.
func TestRandaoOnion(key ml_dsa_87.MLDSA87Key, layers uint64) (*randao.Onion, error) {
	k := randaoOnionKey{seed: bytesutil.ToBytes48(key.Marshal()), layers: layers}
	if o, ok := randaoOnions.Load(k); ok {
		return o.(*randao.Onion), nil
	}
	o, err := randao.NewOnion(k.seed[:], layers)
	if err != nil {
		return nil, err
	}
	actual, _ := randaoOnions.LoadOrStore(k, o)
	return actual.(*randao.Onion), nil
}

// TestRandaoCommitment returns the deposit commitment for key: the top of a
// TestRandaoOnionLayers-long onion.
func TestRandaoCommitment(key ml_dsa_87.MLDSA87Key) [fieldparams.RandaoCommitmentLength]byte {
	o, err := TestRandaoOnion(key, TestRandaoOnionLayers)
	if err != nil {
		panic(err) // lint:nopanic -- layers > 0, cannot fail
	}
	return o.Commitment()
}

// RandaoRevealForKey returns the pre-image of commitment in key's hash onion.
// It tries the test-length onion first and falls back to the default length
// used by runtime/interop genesis and the validator client.
func RandaoRevealForKey(key ml_dsa_87.MLDSA87Key, commitment [fieldparams.RandaoCommitmentLength]byte) ([]byte, error) {
	var lastErr error
	for _, layers := range []uint64{TestRandaoOnionLayers, randao.DefaultLayers} {
		o, err := TestRandaoOnion(key, layers)
		if err != nil {
			return nil, err
		}
		reveal, err := o.Reveal(commitment)
		if err == nil {
			return reveal[:], nil
		}
		lastErr = err
		if !errors.Is(err, randao.ErrUnknownCommitment) {
			break
		}
	}
	return nil, errors.Wrap(lastErr, "could not derive randao reveal for validator key")
}

// RandaoReveal returns the RANDAO reveal for the beacon proposer of the
// state's current slot: the pre-image of its randao commitment, derived from
// the proposer's private key. The epoch argument is kept for call-site
// compatibility; the reveal no longer depends on it.
func RandaoReveal(beaconState state.ReadOnlyBeaconState, _ primitives.Epoch, privKeys []ml_dsa_87.MLDSA87Key) ([]byte, error) {
	// We fetch the proposer's index as that is whom the RANDAO will be verified against.
	proposerIdx, err := helpers.BeaconProposerIndex(context.Background(), beaconState)
	if err != nil {
		return []byte{}, errors.Wrap(err, "could not get beacon proposer index")
	}
	if uint64(proposerIdx) >= uint64(len(privKeys)) {
		return nil, errors.Errorf("no private key for proposer index %d", proposerIdx)
	}
	proposer, err := beaconState.ValidatorAtIndexReadOnly(proposerIdx)
	if err != nil {
		return nil, errors.Wrap(err, "could not get proposer")
	}
	return RandaoRevealForKey(privKeys[proposerIdx], proposer.RandaoCommitment())
}

// BlockSignature calculates the post-state root of the block and returns the signature.
func BlockSignature(
	bState state.BeaconState,
	block any,
	privKeys []ml_dsa_87.MLDSA87Key,
) (ml_dsa_87.Signature, error) {
	var wsb interfaces.ReadOnlySignedBeaconBlock
	var err error
	// copy the state since we need to process slots
	bState = bState.Copy()
	switch b := block.(type) {
	case *qrysmpb.BeaconBlockZond:
		wsb, err = blocks.NewSignedBeaconBlock(&qrysmpb.SignedBeaconBlockZond{Block: b})
	default:
		return nil, errors.New("unsupported block type")
	}
	if err != nil {
		return nil, errors.Wrap(err, "could not wrap block")
	}
	s, err := transition.CalculateStateRoot(context.Background(), bState, wsb)
	if err != nil {
		return nil, errors.Wrap(err, "could not calculate state root")
	}

	switch b := block.(type) {
	case *qrysmpb.BeaconBlockZond:
		b.StateRoot = s[:]
	}

	// Temporarily increasing the beacon state slot here since BeaconProposerIndex is a
	// function deterministic on beacon state slot.
	var blockSlot primitives.Slot
	switch b := block.(type) {
	case *qrysmpb.BeaconBlockZond:
		blockSlot = b.Slot
	}

	// process slots to get the right fork
	bState, err = transition.ProcessSlots(context.Background(), bState, blockSlot)
	if err != nil {
		return nil, err
	}

	domain, err := signing.Domain(bState.Fork(), time.CurrentEpoch(bState), params.BeaconConfig().DomainBeaconProposer, bState.GenesisValidatorsRoot())
	if err != nil {
		return nil, err
	}

	var blockRoot [32]byte
	switch b := block.(type) {
	case *qrysmpb.BeaconBlockZond:
		blockRoot, err = signing.ComputeSigningRoot(b, domain)
	}
	if err != nil {
		return nil, err
	}

	proposerIdx, err := helpers.BeaconProposerIndex(context.Background(), bState)
	if err != nil {
		return nil, err
	}
	return privKeys[proposerIdx].Sign(blockRoot[:])
}

// Random32Bytes generates a random 32 byte slice.
func Random32Bytes(t *testing.T) []byte {
	b := make([]byte, 32)
	_, err := rand.NewDeterministicGenerator().Read(b)
	if err != nil {
		t.Fatal(err)
	}
	return b
}
