// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrl/v1/attestation.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_go_bitfield "github.com/theQRL/go-bitfield"
	github_com_theQRL_qrysm_consensus_types_primitives "github.com/theQRL/qrysm/consensus-types/primitives"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attestation struct {
	state           protoimpl.MessageState                `protogen:"open.v1"`
	AggregationBits github_com_theQRL_go_bitfield.Bitlist `protobuf:"bytes,1,opt,name=aggregation_bits,json=aggregationBits,proto3" json:"aggregation_bits,omitempty" cast-type:"github.com/theQRL/go-bitfield.Bitlist" ssz-max:"32"`
	Data            *AttestationData                      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Signatures      [][]byte                              `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty" ssz-max:"32" ssz-size:"?,4627"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Attestation) Reset() {
	*x = Attestation{}
	mi := &file_proto_qrl_v1_attestation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attestation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attestation) ProtoMessage() {}

func (x *Attestation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_attestation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attestation.ProtoReflect.Descriptor instead.
func (*Attestation) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_attestation_proto_rawDescGZIP(), []int{0}
}

func (x *Attestation) GetAggregationBits() github_com_theQRL_go_bitfield.Bitlist {
	if x != nil {
		return x.AggregationBits
	}
	return github_com_theQRL_go_bitfield.Bitlist(nil)
}

func (x *Attestation) GetData() *AttestationData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Attestation) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type AggregateAttestationAndProof struct {
	state           protoimpl.MessageState                                            `protogen:"open.v1"`
	AggregatorIndex github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,1,opt,name=aggregator_index,json=aggregatorIndex,proto3" json:"aggregator_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	Aggregate       *Attestation                                                      `protobuf:"bytes,3,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	SelectionProof  []byte                                                            `protobuf:"bytes,2,opt,name=selection_proof,json=selectionProof,proto3" json:"selection_proof,omitempty" ssz-size:"4627"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AggregateAttestationAndProof) Reset() {
	*x = AggregateAttestationAndProof{}
	mi := &file_proto_qrl_v1_attestation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregateAttestationAndProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateAttestationAndProof) ProtoMessage() {}

func (x *AggregateAttestationAndProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_attestation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateAttestationAndProof.ProtoReflect.Descriptor instead.
func (*AggregateAttestationAndProof) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_attestation_proto_rawDescGZIP(), []int{1}
}

func (x *AggregateAttestationAndProof) GetAggregatorIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.AggregatorIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

func (x *AggregateAttestationAndProof) GetAggregate() *Attestation {
	if x != nil {
		return x.Aggregate
	}
	return nil
}

func (x *AggregateAttestationAndProof) GetSelectionProof() []byte {
	if x != nil {
		return x.SelectionProof
	}
	return nil
}

type SignedAggregateAttestationAndProof struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Message       *AggregateAttestationAndProof `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                        `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty" ssz-size:"4627"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedAggregateAttestationAndProof) Reset() {
	*x = SignedAggregateAttestationAndProof{}
	mi := &file_proto_qrl_v1_attestation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedAggregateAttestationAndProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedAggregateAttestationAndProof) ProtoMessage() {}

func (x *SignedAggregateAttestationAndProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_attestation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedAggregateAttestationAndProof.ProtoReflect.Descriptor instead.
func (*SignedAggregateAttestationAndProof) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_attestation_proto_rawDescGZIP(), []int{2}
}

func (x *SignedAggregateAttestationAndProof) GetMessage() *AggregateAttestationAndProof {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedAggregateAttestationAndProof) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type AttestationData struct {
	state           protoimpl.MessageState                                            `protogen:"open.v1"`
	Slot            github_com_theQRL_qrysm_consensus_types_primitives.Slot           `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	Index           github_com_theQRL_qrysm_consensus_types_primitives.CommitteeIndex `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.CommitteeIndex"`
	BeaconBlockRoot []byte                                                            `protobuf:"bytes,3,opt,name=beacon_block_root,json=beaconBlockRoot,proto3" json:"beacon_block_root,omitempty" ssz-size:"32"`
	Source          *Checkpoint                                                       `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Target          *Checkpoint                                                       `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttestationData) Reset() {
	*x = AttestationData{}
	mi := &file_proto_qrl_v1_attestation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationData) ProtoMessage() {}

func (x *AttestationData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_attestation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationData.ProtoReflect.Descriptor instead.
func (*AttestationData) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_attestation_proto_rawDescGZIP(), []int{3}
}

func (x *AttestationData) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *AttestationData) GetIndex() github_com_theQRL_qrysm_consensus_types_primitives.CommitteeIndex {
	if x != nil {
		return x.Index
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.CommitteeIndex(0)
}

func (x *AttestationData) GetBeaconBlockRoot() []byte {
	if x != nil {
		return x.BeaconBlockRoot
	}
	return nil
}

func (x *AttestationData) GetSource() *Checkpoint {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *AttestationData) GetTarget() *Checkpoint {
	if x != nil {
		return x.Target
	}
	return nil
}

type Checkpoint struct {
	state         protoimpl.MessageState                                   `protogen:"open.v1"`
	Epoch         github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	Root          []byte                                                   `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty" ssz-size:"32"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_proto_qrl_v1_attestation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_attestation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_attestation_proto_rawDescGZIP(), []int{4}
}

func (x *Checkpoint) GetEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.Epoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

func (x *Checkpoint) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

var File_proto_qrl_v1_attestation_proto protoreflect.FileDescriptor

const file_proto_qrl_v1_attestation_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/qrl/v1/attestation.proto\x12\rtheqrl.qrl.v1\x1a google/protobuf/descriptor.proto\x1a\x1bproto/qrl/ext/options.proto\"\xcf\x01\n" +
	"\vAttestation\x12Z\n" +
	"\x10aggregation_bits\x18\x01 \x01(\fB/\x82\xb5\x18%github.com/theQRL/go-bitfield.Bitlist\x92\xb5\x18\x0232R\x0faggregationBits\x122\n" +
	"\x04data\x18\x02 \x01(\v2\x1e.theqrl.qrl.v1.AttestationDataR\x04data\x120\n" +
	"\n" +
	"signatures\x18\x03 \x03(\fB\x10\x8a\xb5\x18\x06?,4627\x92\xb5\x18\x0232R\n" +
	"signatures\"\xfd\x01\n" +
	"\x1cAggregateAttestationAndProof\x12p\n" +
	"\x10aggregator_index\x18\x01 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\x0faggregatorIndex\x128\n" +
	"\taggregate\x18\x03 \x01(\v2\x1a.theqrl.qrl.v1.AttestationR\taggregate\x121\n" +
	"\x0fselection_proof\x18\x02 \x01(\fB\b\x8a\xb5\x18\x044627R\x0eselectionProof\"\x93\x01\n" +
	"\"SignedAggregateAttestationAndProof\x12E\n" +
	"\amessage\x18\x01 \x01(\v2+.theqrl.qrl.v1.AggregateAttestationAndProofR\amessage\x12&\n" +
	"\tsignature\x18\x02 \x01(\fB\b\x8a\xb5\x18\x044627R\tsignature\"\xd9\x02\n" +
	"\x0fAttestationData\x12O\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12[\n" +
	"\x05index\x18\x02 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.CommitteeIndexR\x05index\x122\n" +
	"\x11beacon_block_root\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\x0fbeaconBlockRoot\x121\n" +
	"\x06source\x18\x04 \x01(\v2\x19.theqrl.qrl.v1.CheckpointR\x06source\x121\n" +
	"\x06target\x18\x05 \x01(\v2\x19.theqrl.qrl.v1.CheckpointR\x06target\"|\n" +
	"\n" +
	"Checkpoint\x12R\n" +
	"\x05epoch\x18\x01 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x05epoch\x12\x1a\n" +
	"\x04root\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\x04rootBm\n" +
	"\x11org.theqrl.qrl.v1B\x10AttestationProtoP\x01Z$github.com/theQRL/qrysm/proto/qrl/v1\xaa\x02\rTheQRL.QRL.V1\xca\x02\rTheQRL\\QRL\\v1b\x06proto3"

var (
	file_proto_qrl_v1_attestation_proto_rawDescOnce sync.Once
	file_proto_qrl_v1_attestation_proto_rawDescData []byte
)

func file_proto_qrl_v1_attestation_proto_rawDescGZIP() []byte {
	file_proto_qrl_v1_attestation_proto_rawDescOnce.Do(func() {
		file_proto_qrl_v1_attestation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_attestation_proto_rawDesc), len(file_proto_qrl_v1_attestation_proto_rawDesc)))
	})
	return file_proto_qrl_v1_attestation_proto_rawDescData
}

var file_proto_qrl_v1_attestation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_qrl_v1_attestation_proto_goTypes = []any{
	(*Attestation)(nil),                        // 0: theqrl.qrl.v1.Attestation
	(*AggregateAttestationAndProof)(nil),       // 1: theqrl.qrl.v1.AggregateAttestationAndProof
	(*SignedAggregateAttestationAndProof)(nil), // 2: theqrl.qrl.v1.SignedAggregateAttestationAndProof
	(*AttestationData)(nil),                    // 3: theqrl.qrl.v1.AttestationData
	(*Checkpoint)(nil),                         // 4: theqrl.qrl.v1.Checkpoint
}
var file_proto_qrl_v1_attestation_proto_depIdxs = []int32{
	3, // 0: theqrl.qrl.v1.Attestation.data:type_name -> theqrl.qrl.v1.AttestationData
	0, // 1: theqrl.qrl.v1.AggregateAttestationAndProof.aggregate:type_name -> theqrl.qrl.v1.Attestation
	1, // 2: theqrl.qrl.v1.SignedAggregateAttestationAndProof.message:type_name -> theqrl.qrl.v1.AggregateAttestationAndProof
	4, // 3: theqrl.qrl.v1.AttestationData.source:type_name -> theqrl.qrl.v1.Checkpoint
	4, // 4: theqrl.qrl.v1.AttestationData.target:type_name -> theqrl.qrl.v1.Checkpoint
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_qrl_v1_attestation_proto_init() }
func file_proto_qrl_v1_attestation_proto_init() {
	if File_proto_qrl_v1_attestation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_attestation_proto_rawDesc), len(file_proto_qrl_v1_attestation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrl_v1_attestation_proto_goTypes,
		DependencyIndexes: file_proto_qrl_v1_attestation_proto_depIdxs,
		MessageInfos:      file_proto_qrl_v1_attestation_proto_msgTypes,
	}.Build()
	File_proto_qrl_v1_attestation_proto = out.File
	file_proto_qrl_v1_attestation_proto_goTypes = nil
	file_proto_qrl_v1_attestation_proto_depIdxs = nil
}
