// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrl/v1/beacon_lightclient.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_qrysm_consensus_types_primitives "github.com/theQRL/qrysm/consensus-types/primitives"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LightClientBootstrap struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Header                     *BeaconBlockHeader     `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CurrentSyncCommittee       *SyncCommittee         `protobuf:"bytes,2,opt,name=current_sync_committee,json=currentSyncCommittee,proto3" json:"current_sync_committee,omitempty"`
	CurrentSyncCommitteeBranch [][]byte               `protobuf:"bytes,3,rep,name=current_sync_committee_branch,json=currentSyncCommitteeBranch,proto3" json:"current_sync_committee_branch,omitempty" ssz-size:"current_sync_committee_branch.depth,32"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *LightClientBootstrap) Reset() {
	*x = LightClientBootstrap{}
	mi := &file_proto_qrl_v1_beacon_lightclient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightClientBootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightClientBootstrap) ProtoMessage() {}

func (x *LightClientBootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_lightclient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightClientBootstrap.ProtoReflect.Descriptor instead.
func (*LightClientBootstrap) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_lightclient_proto_rawDescGZIP(), []int{0}
}

func (x *LightClientBootstrap) GetHeader() *BeaconBlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LightClientBootstrap) GetCurrentSyncCommittee() *SyncCommittee {
	if x != nil {
		return x.CurrentSyncCommittee
	}
	return nil
}

func (x *LightClientBootstrap) GetCurrentSyncCommitteeBranch() [][]byte {
	if x != nil {
		return x.CurrentSyncCommitteeBranch
	}
	return nil
}

type LightClientUpdate struct {
	state                   protoimpl.MessageState                                  `protogen:"open.v1"`
	AttestedHeader          *BeaconBlockHeader                                      `protobuf:"bytes,1,opt,name=attested_header,json=attestedHeader,proto3" json:"attested_header,omitempty"`
	NextSyncCommittee       *SyncCommittee                                          `protobuf:"bytes,2,opt,name=next_sync_committee,json=nextSyncCommittee,proto3" json:"next_sync_committee,omitempty"`
	NextSyncCommitteeBranch [][]byte                                                `protobuf:"bytes,3,rep,name=next_sync_committee_branch,json=nextSyncCommitteeBranch,proto3" json:"next_sync_committee_branch,omitempty" ssz-size:"next_sync_committee_branch.depth,32"`
	FinalizedHeader         *BeaconBlockHeader                                      `protobuf:"bytes,4,opt,name=finalized_header,json=finalizedHeader,proto3" json:"finalized_header,omitempty"`
	FinalityBranch          [][]byte                                                `protobuf:"bytes,5,rep,name=finality_branch,json=finalityBranch,proto3" json:"finality_branch,omitempty" ssz-size:"finality_branch.depth,32"`
	SyncAggregate           *SyncAggregate                                          `protobuf:"bytes,6,opt,name=sync_aggregate,json=syncAggregate,proto3" json:"sync_aggregate,omitempty"`
	SignatureSlot           github_com_theQRL_qrysm_consensus_types_primitives.Slot `protobuf:"varint,7,opt,name=signature_slot,json=signatureSlot,proto3" json:"signature_slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LightClientUpdate) Reset() {
	*x = LightClientUpdate{}
	mi := &file_proto_qrl_v1_beacon_lightclient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightClientUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightClientUpdate) ProtoMessage() {}

func (x *LightClientUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_lightclient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightClientUpdate.ProtoReflect.Descriptor instead.
func (*LightClientUpdate) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_lightclient_proto_rawDescGZIP(), []int{1}
}

func (x *LightClientUpdate) GetAttestedHeader() *BeaconBlockHeader {
	if x != nil {
		return x.AttestedHeader
	}
	return nil
}

func (x *LightClientUpdate) GetNextSyncCommittee() *SyncCommittee {
	if x != nil {
		return x.NextSyncCommittee
	}
	return nil
}

func (x *LightClientUpdate) GetNextSyncCommitteeBranch() [][]byte {
	if x != nil {
		return x.NextSyncCommitteeBranch
	}
	return nil
}

func (x *LightClientUpdate) GetFinalizedHeader() *BeaconBlockHeader {
	if x != nil {
		return x.FinalizedHeader
	}
	return nil
}

func (x *LightClientUpdate) GetFinalityBranch() [][]byte {
	if x != nil {
		return x.FinalityBranch
	}
	return nil
}

func (x *LightClientUpdate) GetSyncAggregate() *SyncAggregate {
	if x != nil {
		return x.SyncAggregate
	}
	return nil
}

func (x *LightClientUpdate) GetSignatureSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.SignatureSlot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

type LightClientFinalityUpdateWithVersion struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Version       Version                    `protobuf:"varint,1,opt,name=version,proto3,enum=theqrl.qrl.v1.Version" json:"version,omitempty"`
	Data          *LightClientFinalityUpdate `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightClientFinalityUpdateWithVersion) Reset() {
	*x = LightClientFinalityUpdateWithVersion{}
	mi := &file_proto_qrl_v1_beacon_lightclient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightClientFinalityUpdateWithVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightClientFinalityUpdateWithVersion) ProtoMessage() {}

func (x *LightClientFinalityUpdateWithVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_lightclient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightClientFinalityUpdateWithVersion.ProtoReflect.Descriptor instead.
func (*LightClientFinalityUpdateWithVersion) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_lightclient_proto_rawDescGZIP(), []int{2}
}

func (x *LightClientFinalityUpdateWithVersion) GetVersion() Version {
	if x != nil {
		return x.Version
	}
	return Version_ZOND
}

func (x *LightClientFinalityUpdateWithVersion) GetData() *LightClientFinalityUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

type LightClientFinalityUpdate struct {
	state           protoimpl.MessageState                                  `protogen:"open.v1"`
	AttestedHeader  *BeaconBlockHeader                                      `protobuf:"bytes,1,opt,name=attested_header,json=attestedHeader,proto3" json:"attested_header,omitempty"`
	FinalizedHeader *BeaconBlockHeader                                      `protobuf:"bytes,2,opt,name=finalized_header,json=finalizedHeader,proto3" json:"finalized_header,omitempty"`
	FinalityBranch  [][]byte                                                `protobuf:"bytes,3,rep,name=finality_branch,json=finalityBranch,proto3" json:"finality_branch,omitempty" ssz-size:"finality_branch.depth,32"`
	SyncAggregate   *SyncAggregate                                          `protobuf:"bytes,4,opt,name=sync_aggregate,json=syncAggregate,proto3" json:"sync_aggregate,omitempty"`
	SignatureSlot   github_com_theQRL_qrysm_consensus_types_primitives.Slot `protobuf:"varint,5,opt,name=signature_slot,json=signatureSlot,proto3" json:"signature_slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LightClientFinalityUpdate) Reset() {
	*x = LightClientFinalityUpdate{}
	mi := &file_proto_qrl_v1_beacon_lightclient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightClientFinalityUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightClientFinalityUpdate) ProtoMessage() {}

func (x *LightClientFinalityUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_lightclient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightClientFinalityUpdate.ProtoReflect.Descriptor instead.
func (*LightClientFinalityUpdate) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_lightclient_proto_rawDescGZIP(), []int{3}
}

func (x *LightClientFinalityUpdate) GetAttestedHeader() *BeaconBlockHeader {
	if x != nil {
		return x.AttestedHeader
	}
	return nil
}

func (x *LightClientFinalityUpdate) GetFinalizedHeader() *BeaconBlockHeader {
	if x != nil {
		return x.FinalizedHeader
	}
	return nil
}

func (x *LightClientFinalityUpdate) GetFinalityBranch() [][]byte {
	if x != nil {
		return x.FinalityBranch
	}
	return nil
}

func (x *LightClientFinalityUpdate) GetSyncAggregate() *SyncAggregate {
	if x != nil {
		return x.SyncAggregate
	}
	return nil
}

func (x *LightClientFinalityUpdate) GetSignatureSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.SignatureSlot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

type LightClientOptimisticUpdateWithVersion struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Version       Version                      `protobuf:"varint,1,opt,name=version,proto3,enum=theqrl.qrl.v1.Version" json:"version,omitempty"`
	Data          *LightClientOptimisticUpdate `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightClientOptimisticUpdateWithVersion) Reset() {
	*x = LightClientOptimisticUpdateWithVersion{}
	mi := &file_proto_qrl_v1_beacon_lightclient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightClientOptimisticUpdateWithVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightClientOptimisticUpdateWithVersion) ProtoMessage() {}

func (x *LightClientOptimisticUpdateWithVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_lightclient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightClientOptimisticUpdateWithVersion.ProtoReflect.Descriptor instead.
func (*LightClientOptimisticUpdateWithVersion) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_lightclient_proto_rawDescGZIP(), []int{4}
}

func (x *LightClientOptimisticUpdateWithVersion) GetVersion() Version {
	if x != nil {
		return x.Version
	}
	return Version_ZOND
}

func (x *LightClientOptimisticUpdateWithVersion) GetData() *LightClientOptimisticUpdate {
	if x != nil {
		return x.Data
	}
	return nil
}

type LightClientOptimisticUpdate struct {
	state          protoimpl.MessageState                                  `protogen:"open.v1"`
	AttestedHeader *BeaconBlockHeader                                      `protobuf:"bytes,1,opt,name=attested_header,json=attestedHeader,proto3" json:"attested_header,omitempty"`
	SyncAggregate  *SyncAggregate                                          `protobuf:"bytes,2,opt,name=sync_aggregate,json=syncAggregate,proto3" json:"sync_aggregate,omitempty"`
	SignatureSlot  github_com_theQRL_qrysm_consensus_types_primitives.Slot `protobuf:"varint,3,opt,name=signature_slot,json=signatureSlot,proto3" json:"signature_slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LightClientOptimisticUpdate) Reset() {
	*x = LightClientOptimisticUpdate{}
	mi := &file_proto_qrl_v1_beacon_lightclient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightClientOptimisticUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightClientOptimisticUpdate) ProtoMessage() {}

func (x *LightClientOptimisticUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_beacon_lightclient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightClientOptimisticUpdate.ProtoReflect.Descriptor instead.
func (*LightClientOptimisticUpdate) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_beacon_lightclient_proto_rawDescGZIP(), []int{5}
}

func (x *LightClientOptimisticUpdate) GetAttestedHeader() *BeaconBlockHeader {
	if x != nil {
		return x.AttestedHeader
	}
	return nil
}

func (x *LightClientOptimisticUpdate) GetSyncAggregate() *SyncAggregate {
	if x != nil {
		return x.SyncAggregate
	}
	return nil
}

func (x *LightClientOptimisticUpdate) GetSignatureSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.SignatureSlot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

var File_proto_qrl_v1_beacon_lightclient_proto protoreflect.FileDescriptor

const file_proto_qrl_v1_beacon_lightclient_proto_rawDesc = "" +
	"\n" +
	"%proto/qrl/v1/beacon_lightclient.proto\x12\rtheqrl.qrl.v1\x1a\x1bproto/qrl/ext/options.proto\x1a\x1fproto/qrl/v1/beacon_block.proto\x1a\x1aproto/qrl/v1/version.proto\x1a!proto/qrl/v1/sync_committee.proto\"\x93\x02\n" +
	"\x14LightClientBootstrap\x128\n" +
	"\x06header\x18\x01 \x01(\v2 .theqrl.qrl.v1.BeaconBlockHeaderR\x06header\x12R\n" +
	"\x16current_sync_committee\x18\x02 \x01(\v2\x1c.theqrl.qrl.v1.SyncCommitteeR\x14currentSyncCommittee\x12m\n" +
	"\x1dcurrent_sync_committee_branch\x18\x03 \x03(\fB*\x8a\xb5\x18&current_sync_committee_branch.depth,32R\x1acurrentSyncCommitteeBranch\"\xcf\x04\n" +
	"\x11LightClientUpdate\x12I\n" +
	"\x0fattested_header\x18\x01 \x01(\v2 .theqrl.qrl.v1.BeaconBlockHeaderR\x0eattestedHeader\x12L\n" +
	"\x13next_sync_committee\x18\x02 \x01(\v2\x1c.theqrl.qrl.v1.SyncCommitteeR\x11nextSyncCommittee\x12d\n" +
	"\x1anext_sync_committee_branch\x18\x03 \x03(\fB'\x8a\xb5\x18#next_sync_committee_branch.depth,32R\x17nextSyncCommitteeBranch\x12K\n" +
	"\x10finalized_header\x18\x04 \x01(\v2 .theqrl.qrl.v1.BeaconBlockHeaderR\x0ffinalizedHeader\x12E\n" +
	"\x0ffinality_branch\x18\x05 \x03(\fB\x1c\x8a\xb5\x18\x18finality_branch.depth,32R\x0efinalityBranch\x12C\n" +
	"\x0esync_aggregate\x18\x06 \x01(\v2\x1c.theqrl.qrl.v1.SyncAggregateR\rsyncAggregate\x12b\n" +
	"\x0esignature_slot\x18\a \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\rsignatureSlot\"\x96\x01\n" +
	"$LightClientFinalityUpdateWithVersion\x120\n" +
	"\aversion\x18\x01 \x01(\x0e2\x16.theqrl.qrl.v1.VersionR\aversion\x12<\n" +
	"\x04data\x18\x02 \x01(\v2(.theqrl.qrl.v1.LightClientFinalityUpdateR\x04data\"\xa3\x03\n" +
	"\x19LightClientFinalityUpdate\x12I\n" +
	"\x0fattested_header\x18\x01 \x01(\v2 .theqrl.qrl.v1.BeaconBlockHeaderR\x0eattestedHeader\x12K\n" +
	"\x10finalized_header\x18\x02 \x01(\v2 .theqrl.qrl.v1.BeaconBlockHeaderR\x0ffinalizedHeader\x12E\n" +
	"\x0ffinality_branch\x18\x03 \x03(\fB\x1c\x8a\xb5\x18\x18finality_branch.depth,32R\x0efinalityBranch\x12C\n" +
	"\x0esync_aggregate\x18\x04 \x01(\v2\x1c.theqrl.qrl.v1.SyncAggregateR\rsyncAggregate\x12b\n" +
	"\x0esignature_slot\x18\x05 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\rsignatureSlot\"\x9a\x01\n" +
	"&LightClientOptimisticUpdateWithVersion\x120\n" +
	"\aversion\x18\x01 \x01(\x0e2\x16.theqrl.qrl.v1.VersionR\aversion\x12>\n" +
	"\x04data\x18\x02 \x01(\v2*.theqrl.qrl.v1.LightClientOptimisticUpdateR\x04data\"\x91\x02\n" +
	"\x1bLightClientOptimisticUpdate\x12I\n" +
	"\x0fattested_header\x18\x01 \x01(\v2 .theqrl.qrl.v1.BeaconBlockHeaderR\x0eattestedHeader\x12C\n" +
	"\x0esync_aggregate\x18\x02 \x01(\v2\x1c.theqrl.qrl.v1.SyncAggregateR\rsyncAggregate\x12b\n" +
	"\x0esignature_slot\x18\x03 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\rsignatureSlotBo\n" +
	"\x11org.theqrl.qrl.v1B\x12SyncCommitteeProtoP\x01Z$github.com/theQRL/qrysm/proto/qrl/v1\xaa\x02\rTheQRL.QRL.V1\xca\x02\rTheQRL\\QRL\\v1b\x06proto3"

var (
	file_proto_qrl_v1_beacon_lightclient_proto_rawDescOnce sync.Once
	file_proto_qrl_v1_beacon_lightclient_proto_rawDescData []byte
)

func file_proto_qrl_v1_beacon_lightclient_proto_rawDescGZIP() []byte {
	file_proto_qrl_v1_beacon_lightclient_proto_rawDescOnce.Do(func() {
		file_proto_qrl_v1_beacon_lightclient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_beacon_lightclient_proto_rawDesc), len(file_proto_qrl_v1_beacon_lightclient_proto_rawDesc)))
	})
	return file_proto_qrl_v1_beacon_lightclient_proto_rawDescData
}

var file_proto_qrl_v1_beacon_lightclient_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_qrl_v1_beacon_lightclient_proto_goTypes = []any{
	(*LightClientBootstrap)(nil),                   // 0: theqrl.qrl.v1.LightClientBootstrap
	(*LightClientUpdate)(nil),                      // 1: theqrl.qrl.v1.LightClientUpdate
	(*LightClientFinalityUpdateWithVersion)(nil),   // 2: theqrl.qrl.v1.LightClientFinalityUpdateWithVersion
	(*LightClientFinalityUpdate)(nil),              // 3: theqrl.qrl.v1.LightClientFinalityUpdate
	(*LightClientOptimisticUpdateWithVersion)(nil), // 4: theqrl.qrl.v1.LightClientOptimisticUpdateWithVersion
	(*LightClientOptimisticUpdate)(nil),            // 5: theqrl.qrl.v1.LightClientOptimisticUpdate
	(*BeaconBlockHeader)(nil),                      // 6: theqrl.qrl.v1.BeaconBlockHeader
	(*SyncCommittee)(nil),                          // 7: theqrl.qrl.v1.SyncCommittee
	(*SyncAggregate)(nil),                          // 8: theqrl.qrl.v1.SyncAggregate
	(Version)(0),                                   // 9: theqrl.qrl.v1.Version
}
var file_proto_qrl_v1_beacon_lightclient_proto_depIdxs = []int32{
	6,  // 0: theqrl.qrl.v1.LightClientBootstrap.header:type_name -> theqrl.qrl.v1.BeaconBlockHeader
	7,  // 1: theqrl.qrl.v1.LightClientBootstrap.current_sync_committee:type_name -> theqrl.qrl.v1.SyncCommittee
	6,  // 2: theqrl.qrl.v1.LightClientUpdate.attested_header:type_name -> theqrl.qrl.v1.BeaconBlockHeader
	7,  // 3: theqrl.qrl.v1.LightClientUpdate.next_sync_committee:type_name -> theqrl.qrl.v1.SyncCommittee
	6,  // 4: theqrl.qrl.v1.LightClientUpdate.finalized_header:type_name -> theqrl.qrl.v1.BeaconBlockHeader
	8,  // 5: theqrl.qrl.v1.LightClientUpdate.sync_aggregate:type_name -> theqrl.qrl.v1.SyncAggregate
	9,  // 6: theqrl.qrl.v1.LightClientFinalityUpdateWithVersion.version:type_name -> theqrl.qrl.v1.Version
	3,  // 7: theqrl.qrl.v1.LightClientFinalityUpdateWithVersion.data:type_name -> theqrl.qrl.v1.LightClientFinalityUpdate
	6,  // 8: theqrl.qrl.v1.LightClientFinalityUpdate.attested_header:type_name -> theqrl.qrl.v1.BeaconBlockHeader
	6,  // 9: theqrl.qrl.v1.LightClientFinalityUpdate.finalized_header:type_name -> theqrl.qrl.v1.BeaconBlockHeader
	8,  // 10: theqrl.qrl.v1.LightClientFinalityUpdate.sync_aggregate:type_name -> theqrl.qrl.v1.SyncAggregate
	9,  // 11: theqrl.qrl.v1.LightClientOptimisticUpdateWithVersion.version:type_name -> theqrl.qrl.v1.Version
	5,  // 12: theqrl.qrl.v1.LightClientOptimisticUpdateWithVersion.data:type_name -> theqrl.qrl.v1.LightClientOptimisticUpdate
	6,  // 13: theqrl.qrl.v1.LightClientOptimisticUpdate.attested_header:type_name -> theqrl.qrl.v1.BeaconBlockHeader
	8,  // 14: theqrl.qrl.v1.LightClientOptimisticUpdate.sync_aggregate:type_name -> theqrl.qrl.v1.SyncAggregate
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_qrl_v1_beacon_lightclient_proto_init() }
func file_proto_qrl_v1_beacon_lightclient_proto_init() {
	if File_proto_qrl_v1_beacon_lightclient_proto != nil {
		return
	}
	file_proto_qrl_v1_beacon_block_proto_init()
	file_proto_qrl_v1_version_proto_init()
	file_proto_qrl_v1_sync_committee_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_beacon_lightclient_proto_rawDesc), len(file_proto_qrl_v1_beacon_lightclient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrl_v1_beacon_lightclient_proto_goTypes,
		DependencyIndexes: file_proto_qrl_v1_beacon_lightclient_proto_depIdxs,
		MessageInfos:      file_proto_qrl_v1_beacon_lightclient_proto_msgTypes,
	}.Build()
	File_proto_qrl_v1_beacon_lightclient_proto = out.File
	file_proto_qrl_v1_beacon_lightclient_proto_goTypes = nil
	file_proto_qrl_v1_beacon_lightclient_proto_depIdxs = nil
}
