// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrl/v1/events.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_qrysm_consensus_types_primitives "github.com/theQRL/qrysm/consensus-types/primitives"
	v1 "github.com/theQRL/qrysm/proto/engine/v1"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []string               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_qrl_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *StreamEventsRequest) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

type EventHead struct {
	state                     protoimpl.MessageState                                  `protogen:"open.v1"`
	Slot                      github_com_theQRL_qrysm_consensus_types_primitives.Slot `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	Block                     []byte                                                  `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty" ssz-size:"32"`
	State                     []byte                                                  `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty" ssz-size:"32"`
	EpochTransition           bool                                                    `protobuf:"varint,4,opt,name=epoch_transition,json=epochTransition,proto3" json:"epoch_transition,omitempty"`
	PreviousDutyDependentRoot []byte                                                  `protobuf:"bytes,5,opt,name=previous_duty_dependent_root,json=previousDutyDependentRoot,proto3" json:"previous_duty_dependent_root,omitempty" ssz-size:"32"`
	CurrentDutyDependentRoot  []byte                                                  `protobuf:"bytes,6,opt,name=current_duty_dependent_root,json=currentDutyDependentRoot,proto3" json:"current_duty_dependent_root,omitempty" ssz-size:"32"`
	ExecutionOptimistic       bool                                                    `protobuf:"varint,7,opt,name=execution_optimistic,json=executionOptimistic,proto3" json:"execution_optimistic,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *EventHead) Reset() {
	*x = EventHead{}
	mi := &file_proto_qrl_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventHead) ProtoMessage() {}

func (x *EventHead) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventHead.ProtoReflect.Descriptor instead.
func (*EventHead) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventHead) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *EventHead) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *EventHead) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *EventHead) GetEpochTransition() bool {
	if x != nil {
		return x.EpochTransition
	}
	return false
}

func (x *EventHead) GetPreviousDutyDependentRoot() []byte {
	if x != nil {
		return x.PreviousDutyDependentRoot
	}
	return nil
}

func (x *EventHead) GetCurrentDutyDependentRoot() []byte {
	if x != nil {
		return x.CurrentDutyDependentRoot
	}
	return nil
}

func (x *EventHead) GetExecutionOptimistic() bool {
	if x != nil {
		return x.ExecutionOptimistic
	}
	return false
}

type EventBlock struct {
	state               protoimpl.MessageState                                  `protogen:"open.v1"`
	Slot                github_com_theQRL_qrysm_consensus_types_primitives.Slot `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	Block               []byte                                                  `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty" ssz-size:"32"`
	ExecutionOptimistic bool                                                    `protobuf:"varint,3,opt,name=execution_optimistic,json=executionOptimistic,proto3" json:"execution_optimistic,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventBlock) Reset() {
	*x = EventBlock{}
	mi := &file_proto_qrl_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBlock) ProtoMessage() {}

func (x *EventBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBlock.ProtoReflect.Descriptor instead.
func (*EventBlock) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *EventBlock) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *EventBlock) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *EventBlock) GetExecutionOptimistic() bool {
	if x != nil {
		return x.ExecutionOptimistic
	}
	return false
}

type EventChainReorg struct {
	state               protoimpl.MessageState                                   `protogen:"open.v1"`
	Slot                github_com_theQRL_qrysm_consensus_types_primitives.Slot  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	Depth               uint64                                                   `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	OldHeadBlock        []byte                                                   `protobuf:"bytes,3,opt,name=old_head_block,json=oldHeadBlock,proto3" json:"old_head_block,omitempty" ssz-size:"32"`
	NewHeadBlock        []byte                                                   `protobuf:"bytes,4,opt,name=new_head_block,json=newHeadBlock,proto3" json:"new_head_block,omitempty" ssz-size:"32"`
	OldHeadState        []byte                                                   `protobuf:"bytes,5,opt,name=old_head_state,json=oldHeadState,proto3" json:"old_head_state,omitempty" ssz-size:"32"`
	NewHeadState        []byte                                                   `protobuf:"bytes,6,opt,name=new_head_state,json=newHeadState,proto3" json:"new_head_state,omitempty" ssz-size:"32"`
	Epoch               github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	ExecutionOptimistic bool                                                     `protobuf:"varint,8,opt,name=execution_optimistic,json=executionOptimistic,proto3" json:"execution_optimistic,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventChainReorg) Reset() {
	*x = EventChainReorg{}
	mi := &file_proto_qrl_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventChainReorg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventChainReorg) ProtoMessage() {}

func (x *EventChainReorg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventChainReorg.ProtoReflect.Descriptor instead.
func (*EventChainReorg) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *EventChainReorg) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *EventChainReorg) GetDepth() uint64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *EventChainReorg) GetOldHeadBlock() []byte {
	if x != nil {
		return x.OldHeadBlock
	}
	return nil
}

func (x *EventChainReorg) GetNewHeadBlock() []byte {
	if x != nil {
		return x.NewHeadBlock
	}
	return nil
}

func (x *EventChainReorg) GetOldHeadState() []byte {
	if x != nil {
		return x.OldHeadState
	}
	return nil
}

func (x *EventChainReorg) GetNewHeadState() []byte {
	if x != nil {
		return x.NewHeadState
	}
	return nil
}

func (x *EventChainReorg) GetEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.Epoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

func (x *EventChainReorg) GetExecutionOptimistic() bool {
	if x != nil {
		return x.ExecutionOptimistic
	}
	return false
}

type EventFinalizedCheckpoint struct {
	state               protoimpl.MessageState                                   `protogen:"open.v1"`
	Block               []byte                                                   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty" ssz-size:"32"`
	State               []byte                                                   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty" ssz-size:"32"`
	Epoch               github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	ExecutionOptimistic bool                                                     `protobuf:"varint,4,opt,name=execution_optimistic,json=executionOptimistic,proto3" json:"execution_optimistic,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EventFinalizedCheckpoint) Reset() {
	*x = EventFinalizedCheckpoint{}
	mi := &file_proto_qrl_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFinalizedCheckpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFinalizedCheckpoint) ProtoMessage() {}

func (x *EventFinalizedCheckpoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFinalizedCheckpoint.ProtoReflect.Descriptor instead.
func (*EventFinalizedCheckpoint) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *EventFinalizedCheckpoint) GetBlock() []byte {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *EventFinalizedCheckpoint) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *EventFinalizedCheckpoint) GetEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.Epoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

func (x *EventFinalizedCheckpoint) GetExecutionOptimistic() bool {
	if x != nil {
		return x.ExecutionOptimistic
	}
	return false
}

type EventPayloadAttributeV2 struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Version       string                                        `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Data          *EventPayloadAttributeV2_BasePayloadAttribute `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPayloadAttributeV2) Reset() {
	*x = EventPayloadAttributeV2{}
	mi := &file_proto_qrl_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPayloadAttributeV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPayloadAttributeV2) ProtoMessage() {}

func (x *EventPayloadAttributeV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPayloadAttributeV2.ProtoReflect.Descriptor instead.
func (*EventPayloadAttributeV2) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *EventPayloadAttributeV2) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EventPayloadAttributeV2) GetData() *EventPayloadAttributeV2_BasePayloadAttribute {
	if x != nil {
		return x.Data
	}
	return nil
}

type EventPayloadAttributeV2_BasePayloadAttribute struct {
	state             protoimpl.MessageState                                            `protogen:"open.v1"`
	ProposalSlot      github_com_theQRL_qrysm_consensus_types_primitives.Slot           `protobuf:"varint,3,opt,name=proposal_slot,json=proposalSlot,proto3" json:"proposal_slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	ParentBlockNumber uint64                                                            `protobuf:"varint,4,opt,name=parent_block_number,json=parentBlockNumber,proto3" json:"parent_block_number,omitempty"`
	ParentBlockRoot   []byte                                                            `protobuf:"bytes,5,opt,name=parent_block_root,json=parentBlockRoot,proto3" json:"parent_block_root,omitempty" ssz-size:"32"`
	ParentBlockHash   []byte                                                            `protobuf:"bytes,6,opt,name=parent_block_hash,json=parentBlockHash,proto3" json:"parent_block_hash,omitempty" ssz-size:"32"`
	ProposerIndex     github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,7,opt,name=proposer_index,json=proposerIndex,proto3" json:"proposer_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	PayloadAttributes *v1.PayloadAttributesV2                                           `protobuf:"bytes,8,opt,name=payload_attributes,json=payloadAttributes,proto3" json:"payload_attributes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventPayloadAttributeV2_BasePayloadAttribute) Reset() {
	*x = EventPayloadAttributeV2_BasePayloadAttribute{}
	mi := &file_proto_qrl_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPayloadAttributeV2_BasePayloadAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPayloadAttributeV2_BasePayloadAttribute) ProtoMessage() {}

func (x *EventPayloadAttributeV2_BasePayloadAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPayloadAttributeV2_BasePayloadAttribute.ProtoReflect.Descriptor instead.
func (*EventPayloadAttributeV2_BasePayloadAttribute) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_events_proto_rawDescGZIP(), []int{5, 0}
}

func (x *EventPayloadAttributeV2_BasePayloadAttribute) GetProposalSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.ProposalSlot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *EventPayloadAttributeV2_BasePayloadAttribute) GetParentBlockNumber() uint64 {
	if x != nil {
		return x.ParentBlockNumber
	}
	return 0
}

func (x *EventPayloadAttributeV2_BasePayloadAttribute) GetParentBlockRoot() []byte {
	if x != nil {
		return x.ParentBlockRoot
	}
	return nil
}

func (x *EventPayloadAttributeV2_BasePayloadAttribute) GetParentBlockHash() []byte {
	if x != nil {
		return x.ParentBlockHash
	}
	return nil
}

func (x *EventPayloadAttributeV2_BasePayloadAttribute) GetProposerIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.ProposerIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

func (x *EventPayloadAttributeV2_BasePayloadAttribute) GetPayloadAttributes() *v1.PayloadAttributesV2 {
	if x != nil {
		return x.PayloadAttributes
	}
	return nil
}

var File_proto_qrl_v1_events_proto protoreflect.FileDescriptor

const file_proto_qrl_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x19proto/qrl/v1/events.proto\x12\rtheqrl.qrl.v1\x1a google/protobuf/descriptor.proto\x1a\x1bproto/qrl/ext/options.proto\x1a&proto/engine/v1/execution_engine.proto\"-\n" +
	"\x13StreamEventsRequest\x12\x16\n" +
	"\x06topics\x18\x01 \x03(\tR\x06topics\"\x86\x03\n" +
	"\tEventHead\x12O\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12\x1c\n" +
	"\x05block\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\x05block\x12\x1c\n" +
	"\x05state\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\x05state\x12)\n" +
	"\x10epoch_transition\x18\x04 \x01(\bR\x0fepochTransition\x12G\n" +
	"\x1cprevious_duty_dependent_root\x18\x05 \x01(\fB\x06\x8a\xb5\x18\x0232R\x19previousDutyDependentRoot\x12E\n" +
	"\x1bcurrent_duty_dependent_root\x18\x06 \x01(\fB\x06\x8a\xb5\x18\x0232R\x18currentDutyDependentRoot\x121\n" +
	"\x14execution_optimistic\x18\a \x01(\bR\x13executionOptimistic\"\xae\x01\n" +
	"\n" +
	"EventBlock\x12O\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12\x1c\n" +
	"\x05block\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\x05block\x121\n" +
	"\x14execution_optimistic\x18\x03 \x01(\bR\x13executionOptimistic\"\xb7\x03\n" +
	"\x0fEventChainReorg\x12O\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x04R\x05depth\x12,\n" +
	"\x0eold_head_block\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\foldHeadBlock\x12,\n" +
	"\x0enew_head_block\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\fnewHeadBlock\x12,\n" +
	"\x0eold_head_state\x18\x05 \x01(\fB\x06\x8a\xb5\x18\x0232R\foldHeadState\x12,\n" +
	"\x0enew_head_state\x18\x06 \x01(\fB\x06\x8a\xb5\x18\x0232R\fnewHeadState\x12R\n" +
	"\x05epoch\x18\a \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x05epoch\x121\n" +
	"\x14execution_optimistic\x18\b \x01(\bR\x13executionOptimistic\"\xdd\x01\n" +
	"\x18EventFinalizedCheckpoint\x12\x1c\n" +
	"\x05block\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\x05block\x12\x1c\n" +
	"\x05state\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\x05state\x12R\n" +
	"\x05epoch\x18\x03 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x05epoch\x121\n" +
	"\x14execution_optimistic\x18\x04 \x01(\bR\x13executionOptimistic\"\xdb\x04\n" +
	"\x17EventPayloadAttributeV2\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12O\n" +
	"\x04data\x18\x02 \x01(\v2;.theqrl.qrl.v1.EventPayloadAttributeV2.BasePayloadAttributeR\x04data\x1a\xd4\x03\n" +
	"\x14BasePayloadAttribute\x12`\n" +
	"\rproposal_slot\x18\x03 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\fproposalSlot\x12.\n" +
	"\x13parent_block_number\x18\x04 \x01(\x04R\x11parentBlockNumber\x122\n" +
	"\x11parent_block_root\x18\x05 \x01(\fB\x06\x8a\xb5\x18\x0232R\x0fparentBlockRoot\x122\n" +
	"\x11parent_block_hash\x18\x06 \x01(\fB\x06\x8a\xb5\x18\x0232R\x0fparentBlockHash\x12l\n" +
	"\x0eproposer_index\x18\a \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\rproposerIndex\x12T\n" +
	"\x12payload_attributes\x18\b \x01(\v2%.theqrl.engine.v1.PayloadAttributesV2R\x11payloadAttributesBn\n" +
	"\x11org.theqrl.qrl.v1B\x11BeaconEventsProtoP\x01Z$github.com/theQRL/qrysm/proto/qrl/v1\xaa\x02\rTheQRL.QRL.V1\xca\x02\rTheQRL\\QRL\\v1b\x06proto3"

var (
	file_proto_qrl_v1_events_proto_rawDescOnce sync.Once
	file_proto_qrl_v1_events_proto_rawDescData []byte
)

func file_proto_qrl_v1_events_proto_rawDescGZIP() []byte {
	file_proto_qrl_v1_events_proto_rawDescOnce.Do(func() {
		file_proto_qrl_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_events_proto_rawDesc), len(file_proto_qrl_v1_events_proto_rawDesc)))
	})
	return file_proto_qrl_v1_events_proto_rawDescData
}

var file_proto_qrl_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_qrl_v1_events_proto_goTypes = []any{
	(*StreamEventsRequest)(nil),                          // 0: theqrl.qrl.v1.StreamEventsRequest
	(*EventHead)(nil),                                    // 1: theqrl.qrl.v1.EventHead
	(*EventBlock)(nil),                                   // 2: theqrl.qrl.v1.EventBlock
	(*EventChainReorg)(nil),                              // 3: theqrl.qrl.v1.EventChainReorg
	(*EventFinalizedCheckpoint)(nil),                     // 4: theqrl.qrl.v1.EventFinalizedCheckpoint
	(*EventPayloadAttributeV2)(nil),                      // 5: theqrl.qrl.v1.EventPayloadAttributeV2
	(*EventPayloadAttributeV2_BasePayloadAttribute)(nil), // 6: theqrl.qrl.v1.EventPayloadAttributeV2.BasePayloadAttribute
	(*v1.PayloadAttributesV2)(nil),                       // 7: theqrl.engine.v1.PayloadAttributesV2
}
var file_proto_qrl_v1_events_proto_depIdxs = []int32{
	6, // 0: theqrl.qrl.v1.EventPayloadAttributeV2.data:type_name -> theqrl.qrl.v1.EventPayloadAttributeV2.BasePayloadAttribute
	7, // 1: theqrl.qrl.v1.EventPayloadAttributeV2.BasePayloadAttribute.payload_attributes:type_name -> theqrl.engine.v1.PayloadAttributesV2
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_qrl_v1_events_proto_init() }
func file_proto_qrl_v1_events_proto_init() {
	if File_proto_qrl_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_events_proto_rawDesc), len(file_proto_qrl_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrl_v1_events_proto_goTypes,
		DependencyIndexes: file_proto_qrl_v1_events_proto_depIdxs,
		MessageInfos:      file_proto_qrl_v1_events_proto_msgTypes,
	}.Build()
	File_proto_qrl_v1_events_proto = out.File
	file_proto_qrl_v1_events_proto_goTypes = nil
	file_proto_qrl_v1_events_proto_depIdxs = nil
}
