// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrl/v1/node.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_go_bitfield "github.com/theQRL/go-bitfield"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerDirection int32

const (
	PeerDirection_INBOUND  PeerDirection = 0
	PeerDirection_OUTBOUND PeerDirection = 1
)

// Enum value maps for PeerDirection.
var (
	PeerDirection_name = map[int32]string{
		0: "INBOUND",
		1: "OUTBOUND",
	}
	PeerDirection_value = map[string]int32{
		"INBOUND":  0,
		"OUTBOUND": 1,
	}
)

func (x PeerDirection) Enum() *PeerDirection {
	p := new(PeerDirection)
	*p = x
	return p
}

func (x PeerDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_qrl_v1_node_proto_enumTypes[0].Descriptor()
}

func (PeerDirection) Type() protoreflect.EnumType {
	return &file_proto_qrl_v1_node_proto_enumTypes[0]
}

func (x PeerDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerDirection.Descriptor instead.
func (PeerDirection) EnumDescriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{0}
}

type ConnectionState int32

const (
	ConnectionState_DISCONNECTED  ConnectionState = 0
	ConnectionState_CONNECTING    ConnectionState = 1
	ConnectionState_CONNECTED     ConnectionState = 2
	ConnectionState_DISCONNECTING ConnectionState = 3
)

// Enum value maps for ConnectionState.
var (
	ConnectionState_name = map[int32]string{
		0: "DISCONNECTED",
		1: "CONNECTING",
		2: "CONNECTED",
		3: "DISCONNECTING",
	}
	ConnectionState_value = map[string]int32{
		"DISCONNECTED":  0,
		"CONNECTING":    1,
		"CONNECTED":     2,
		"DISCONNECTING": 3,
	}
)

func (x ConnectionState) Enum() *ConnectionState {
	p := new(ConnectionState)
	*p = x
	return p
}

func (x ConnectionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_qrl_v1_node_proto_enumTypes[1].Descriptor()
}

func (ConnectionState) Type() protoreflect.EnumType {
	return &file_proto_qrl_v1_node_proto_enumTypes[1]
}

func (x ConnectionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionState.Descriptor instead.
func (ConnectionState) EnumDescriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{1}
}

type IdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Identity              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityResponse) Reset() {
	*x = IdentityResponse{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityResponse) ProtoMessage() {}

func (x *IdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityResponse.ProtoReflect.Descriptor instead.
func (*IdentityResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityResponse) GetData() *Identity {
	if x != nil {
		return x.Data
	}
	return nil
}

type Identity struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PeerId             string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Qnr                string                 `protobuf:"bytes,2,opt,name=qnr,proto3" json:"qnr,omitempty"`
	P2PAddresses       []string               `protobuf:"bytes,3,rep,name=p2p_addresses,json=p2pAddresses,proto3" json:"p2p_addresses,omitempty"`
	DiscoveryAddresses []string               `protobuf:"bytes,4,rep,name=discovery_addresses,json=discoveryAddresses,proto3" json:"discovery_addresses,omitempty"`
	Metadata           *Metadata              `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *Identity) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Identity) GetQnr() string {
	if x != nil {
		return x.Qnr
	}
	return ""
}

func (x *Identity) GetP2PAddresses() []string {
	if x != nil {
		return x.P2PAddresses
	}
	return nil
}

func (x *Identity) GetDiscoveryAddresses() []string {
	if x != nil {
		return x.DiscoveryAddresses
	}
	return nil
}

func (x *Identity) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	SeqNumber     uint64                                    `protobuf:"varint,1,opt,name=seq_number,json=seqNumber,proto3" json:"seq_number,omitempty"`
	Attnets       github_com_theQRL_go_bitfield.Bitvector64 `protobuf:"bytes,2,opt,name=attnets,proto3" json:"attnets,omitempty" cast-type:"github.com/theQRL/go-bitfield.Bitvector64" ssz-size:"8"`
	Syncnets      github_com_theQRL_go_bitfield.Bitvector4  `protobuf:"bytes,3,opt,name=syncnets,proto3" json:"syncnets,omitempty" cast-type:"github.com/theQRL/go-bitfield.Bitvector4" ssz-size:"1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetSeqNumber() uint64 {
	if x != nil {
		return x.SeqNumber
	}
	return 0
}

func (x *Metadata) GetAttnets() github_com_theQRL_go_bitfield.Bitvector64 {
	if x != nil {
		return x.Attnets
	}
	return github_com_theQRL_go_bitfield.Bitvector64(nil)
}

func (x *Metadata) GetSyncnets() github_com_theQRL_go_bitfield.Bitvector4 {
	if x != nil {
		return x.Syncnets
	}
	return github_com_theQRL_go_bitfield.Bitvector4(nil)
}

type PeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerId        string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerRequest) Reset() {
	*x = PeerRequest{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRequest) ProtoMessage() {}

func (x *PeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRequest.ProtoReflect.Descriptor instead.
func (*PeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *PeerRequest) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type PeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         []ConnectionState      `protobuf:"varint,1,rep,packed,name=state,proto3,enum=theqrl.qrl.v1.ConnectionState" json:"state,omitempty"`
	Direction     []PeerDirection        `protobuf:"varint,2,rep,packed,name=direction,proto3,enum=theqrl.qrl.v1.PeerDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersRequest) Reset() {
	*x = PeersRequest{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersRequest) ProtoMessage() {}

func (x *PeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersRequest.ProtoReflect.Descriptor instead.
func (*PeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *PeersRequest) GetState() []ConnectionState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *PeersRequest) GetDirection() []PeerDirection {
	if x != nil {
		return x.Direction
	}
	return nil
}

type PeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Peer                  `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Meta          *PeerResponse_Meta     `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerResponse) Reset() {
	*x = PeerResponse{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerResponse) ProtoMessage() {}

func (x *PeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerResponse.ProtoReflect.Descriptor instead.
func (*PeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{5}
}

func (x *PeerResponse) GetData() *Peer {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PeerResponse) GetMeta() *PeerResponse_Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type PeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Peer                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Meta          *PeersResponse_Meta    `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersResponse) Reset() {
	*x = PeersResponse{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersResponse) ProtoMessage() {}

func (x *PeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersResponse.ProtoReflect.Descriptor instead.
func (*PeersResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *PeersResponse) GetData() []*Peer {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PeersResponse) GetMeta() *PeersResponse_Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type PeerCountResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Data          *PeerCountResponse_PeerCount `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerCountResponse) Reset() {
	*x = PeerCountResponse{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerCountResponse) ProtoMessage() {}

func (x *PeerCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerCountResponse.ProtoReflect.Descriptor instead.
func (*PeerCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{7}
}

func (x *PeerCountResponse) GetData() *PeerCountResponse_PeerCount {
	if x != nil {
		return x.Data
	}
	return nil
}

type Peer struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PeerId             string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Qnr                string                 `protobuf:"bytes,2,opt,name=qnr,proto3" json:"qnr,omitempty"`
	LastSeenP2PAddress string                 `protobuf:"bytes,3,opt,name=last_seen_p2p_address,json=lastSeenP2pAddress,proto3" json:"last_seen_p2p_address,omitempty"`
	State              ConnectionState        `protobuf:"varint,4,opt,name=state,proto3,enum=theqrl.qrl.v1.ConnectionState" json:"state,omitempty"`
	Direction          PeerDirection          `protobuf:"varint,5,opt,name=direction,proto3,enum=theqrl.qrl.v1.PeerDirection" json:"direction,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{8}
}

func (x *Peer) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *Peer) GetQnr() string {
	if x != nil {
		return x.Qnr
	}
	return ""
}

func (x *Peer) GetLastSeenP2PAddress() string {
	if x != nil {
		return x.LastSeenP2PAddress
	}
	return ""
}

func (x *Peer) GetState() ConnectionState {
	if x != nil {
		return x.State
	}
	return ConnectionState_DISCONNECTED
}

func (x *Peer) GetDirection() PeerDirection {
	if x != nil {
		return x.Direction
	}
	return PeerDirection_INBOUND
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *NodeVersion           `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{9}
}

func (x *VersionResponse) GetData() *NodeVersion {
	if x != nil {
		return x.Data
	}
	return nil
}

type NodeVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeVersion) Reset() {
	*x = NodeVersion{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeVersion) ProtoMessage() {}

func (x *NodeVersion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeVersion.ProtoReflect.Descriptor instead.
func (*NodeVersion) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{10}
}

func (x *NodeVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PeerResponse_Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerResponse_Meta) Reset() {
	*x = PeerResponse_Meta{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerResponse_Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerResponse_Meta) ProtoMessage() {}

func (x *PeerResponse_Meta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerResponse_Meta.ProtoReflect.Descriptor instead.
func (*PeerResponse_Meta) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{5, 0}
}

func (x *PeerResponse_Meta) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PeersResponse_Meta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersResponse_Meta) Reset() {
	*x = PeersResponse_Meta{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersResponse_Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersResponse_Meta) ProtoMessage() {}

func (x *PeersResponse_Meta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersResponse_Meta.ProtoReflect.Descriptor instead.
func (*PeersResponse_Meta) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{6, 0}
}

func (x *PeersResponse_Meta) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PeerCountResponse_PeerCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disconnected  uint64                 `protobuf:"varint,1,opt,name=disconnected,proto3" json:"disconnected,omitempty"`
	Connecting    uint64                 `protobuf:"varint,2,opt,name=connecting,proto3" json:"connecting,omitempty"`
	Connected     uint64                 `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	Disconnecting uint64                 `protobuf:"varint,4,opt,name=disconnecting,proto3" json:"disconnecting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerCountResponse_PeerCount) Reset() {
	*x = PeerCountResponse_PeerCount{}
	mi := &file_proto_qrl_v1_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerCountResponse_PeerCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerCountResponse_PeerCount) ProtoMessage() {}

func (x *PeerCountResponse_PeerCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerCountResponse_PeerCount.ProtoReflect.Descriptor instead.
func (*PeerCountResponse_PeerCount) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_node_proto_rawDescGZIP(), []int{7, 0}
}

func (x *PeerCountResponse_PeerCount) GetDisconnected() uint64 {
	if x != nil {
		return x.Disconnected
	}
	return 0
}

func (x *PeerCountResponse_PeerCount) GetConnecting() uint64 {
	if x != nil {
		return x.Connecting
	}
	return 0
}

func (x *PeerCountResponse_PeerCount) GetConnected() uint64 {
	if x != nil {
		return x.Connected
	}
	return 0
}

func (x *PeerCountResponse_PeerCount) GetDisconnecting() uint64 {
	if x != nil {
		return x.Disconnecting
	}
	return 0
}

var File_proto_qrl_v1_node_proto protoreflect.FileDescriptor

const file_proto_qrl_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x17proto/qrl/v1/node.proto\x12\rtheqrl.qrl.v1\x1a google/protobuf/descriptor.proto\x1a\x1bproto/qrl/ext/options.proto\"?\n" +
	"\x10IdentityResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.theqrl.qrl.v1.IdentityR\x04data\"\xc0\x01\n" +
	"\bIdentity\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x10\n" +
	"\x03qnr\x18\x02 \x01(\tR\x03qnr\x12#\n" +
	"\rp2p_addresses\x18\x03 \x03(\tR\fp2pAddresses\x12/\n" +
	"\x13discovery_addresses\x18\x04 \x03(\tR\x12discoveryAddresses\x123\n" +
	"\bmetadata\x18\x05 \x01(\v2\x17.theqrl.qrl.v1.MetadataR\bmetadata\"\xc6\x01\n" +
	"\bMetadata\x12\x1d\n" +
	"\n" +
	"seq_number\x18\x01 \x01(\x04R\tseqNumber\x12L\n" +
	"\aattnets\x18\x02 \x01(\fB2\x82\xb5\x18)github.com/theQRL/go-bitfield.Bitvector64\x8a\xb5\x18\x018R\aattnets\x12M\n" +
	"\bsyncnets\x18\x03 \x01(\fB1\x82\xb5\x18(github.com/theQRL/go-bitfield.Bitvector4\x8a\xb5\x18\x011R\bsyncnets\"&\n" +
	"\vPeerRequest\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\"\x80\x01\n" +
	"\fPeersRequest\x124\n" +
	"\x05state\x18\x01 \x03(\x0e2\x1e.theqrl.qrl.v1.ConnectionStateR\x05state\x12:\n" +
	"\tdirection\x18\x02 \x03(\x0e2\x1c.theqrl.qrl.v1.PeerDirectionR\tdirection\"\x8b\x01\n" +
	"\fPeerResponse\x12'\n" +
	"\x04data\x18\x01 \x01(\v2\x13.theqrl.qrl.v1.PeerR\x04data\x124\n" +
	"\x04meta\x18\x02 \x01(\v2 .theqrl.qrl.v1.PeerResponse.MetaR\x04meta\x1a\x1c\n" +
	"\x04Meta\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"\x8d\x01\n" +
	"\rPeersResponse\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.theqrl.qrl.v1.PeerR\x04data\x125\n" +
	"\x04meta\x18\x02 \x01(\v2!.theqrl.qrl.v1.PeersResponse.MetaR\x04meta\x1a\x1c\n" +
	"\x04Meta\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"\xe9\x01\n" +
	"\x11PeerCountResponse\x12>\n" +
	"\x04data\x18\x01 \x01(\v2*.theqrl.qrl.v1.PeerCountResponse.PeerCountR\x04data\x1a\x93\x01\n" +
	"\tPeerCount\x12\"\n" +
	"\fdisconnected\x18\x01 \x01(\x04R\fdisconnected\x12\x1e\n" +
	"\n" +
	"connecting\x18\x02 \x01(\x04R\n" +
	"connecting\x12\x1c\n" +
	"\tconnected\x18\x03 \x01(\x04R\tconnected\x12$\n" +
	"\rdisconnecting\x18\x04 \x01(\x04R\rdisconnecting\"\xd6\x01\n" +
	"\x04Peer\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x10\n" +
	"\x03qnr\x18\x02 \x01(\tR\x03qnr\x121\n" +
	"\x15last_seen_p2p_address\x18\x03 \x01(\tR\x12lastSeenP2pAddress\x124\n" +
	"\x05state\x18\x04 \x01(\x0e2\x1e.theqrl.qrl.v1.ConnectionStateR\x05state\x12:\n" +
	"\tdirection\x18\x05 \x01(\x0e2\x1c.theqrl.qrl.v1.PeerDirectionR\tdirection\"A\n" +
	"\x0fVersionResponse\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.theqrl.qrl.v1.NodeVersionR\x04data\"'\n" +
	"\vNodeVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion**\n" +
	"\rPeerDirection\x12\v\n" +
	"\aINBOUND\x10\x00\x12\f\n" +
	"\bOUTBOUND\x10\x01*U\n" +
	"\x0fConnectionState\x12\x10\n" +
	"\fDISCONNECTED\x10\x00\x12\x0e\n" +
	"\n" +
	"CONNECTING\x10\x01\x12\r\n" +
	"\tCONNECTED\x10\x02\x12\x11\n" +
	"\rDISCONNECTING\x10\x03Bl\n" +
	"\x11org.theqrl.qrl.v1B\x0fBeaconNodeProtoP\x01Z$github.com/theQRL/qrysm/proto/qrl/v1\xaa\x02\rTheQRL.QRL.V1\xca\x02\rTheQRL\\QRL\\v1b\x06proto3"

var (
	file_proto_qrl_v1_node_proto_rawDescOnce sync.Once
	file_proto_qrl_v1_node_proto_rawDescData []byte
)

func file_proto_qrl_v1_node_proto_rawDescGZIP() []byte {
	file_proto_qrl_v1_node_proto_rawDescOnce.Do(func() {
		file_proto_qrl_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_node_proto_rawDesc), len(file_proto_qrl_v1_node_proto_rawDesc)))
	})
	return file_proto_qrl_v1_node_proto_rawDescData
}

var file_proto_qrl_v1_node_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_qrl_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_qrl_v1_node_proto_goTypes = []any{
	(PeerDirection)(0),                  // 0: theqrl.qrl.v1.PeerDirection
	(ConnectionState)(0),                // 1: theqrl.qrl.v1.ConnectionState
	(*IdentityResponse)(nil),            // 2: theqrl.qrl.v1.IdentityResponse
	(*Identity)(nil),                    // 3: theqrl.qrl.v1.Identity
	(*Metadata)(nil),                    // 4: theqrl.qrl.v1.Metadata
	(*PeerRequest)(nil),                 // 5: theqrl.qrl.v1.PeerRequest
	(*PeersRequest)(nil),                // 6: theqrl.qrl.v1.PeersRequest
	(*PeerResponse)(nil),                // 7: theqrl.qrl.v1.PeerResponse
	(*PeersResponse)(nil),               // 8: theqrl.qrl.v1.PeersResponse
	(*PeerCountResponse)(nil),           // 9: theqrl.qrl.v1.PeerCountResponse
	(*Peer)(nil),                        // 10: theqrl.qrl.v1.Peer
	(*VersionResponse)(nil),             // 11: theqrl.qrl.v1.VersionResponse
	(*NodeVersion)(nil),                 // 12: theqrl.qrl.v1.NodeVersion
	(*PeerResponse_Meta)(nil),           // 13: theqrl.qrl.v1.PeerResponse.Meta
	(*PeersResponse_Meta)(nil),          // 14: theqrl.qrl.v1.PeersResponse.Meta
	(*PeerCountResponse_PeerCount)(nil), // 15: theqrl.qrl.v1.PeerCountResponse.PeerCount
}
var file_proto_qrl_v1_node_proto_depIdxs = []int32{
	3,  // 0: theqrl.qrl.v1.IdentityResponse.data:type_name -> theqrl.qrl.v1.Identity
	4,  // 1: theqrl.qrl.v1.Identity.metadata:type_name -> theqrl.qrl.v1.Metadata
	1,  // 2: theqrl.qrl.v1.PeersRequest.state:type_name -> theqrl.qrl.v1.ConnectionState
	0,  // 3: theqrl.qrl.v1.PeersRequest.direction:type_name -> theqrl.qrl.v1.PeerDirection
	10, // 4: theqrl.qrl.v1.PeerResponse.data:type_name -> theqrl.qrl.v1.Peer
	13, // 5: theqrl.qrl.v1.PeerResponse.meta:type_name -> theqrl.qrl.v1.PeerResponse.Meta
	10, // 6: theqrl.qrl.v1.PeersResponse.data:type_name -> theqrl.qrl.v1.Peer
	14, // 7: theqrl.qrl.v1.PeersResponse.meta:type_name -> theqrl.qrl.v1.PeersResponse.Meta
	15, // 8: theqrl.qrl.v1.PeerCountResponse.data:type_name -> theqrl.qrl.v1.PeerCountResponse.PeerCount
	1,  // 9: theqrl.qrl.v1.Peer.state:type_name -> theqrl.qrl.v1.ConnectionState
	0,  // 10: theqrl.qrl.v1.Peer.direction:type_name -> theqrl.qrl.v1.PeerDirection
	12, // 11: theqrl.qrl.v1.VersionResponse.data:type_name -> theqrl.qrl.v1.NodeVersion
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_qrl_v1_node_proto_init() }
func file_proto_qrl_v1_node_proto_init() {
	if File_proto_qrl_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_node_proto_rawDesc), len(file_proto_qrl_v1_node_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrl_v1_node_proto_goTypes,
		DependencyIndexes: file_proto_qrl_v1_node_proto_depIdxs,
		EnumInfos:         file_proto_qrl_v1_node_proto_enumTypes,
		MessageInfos:      file_proto_qrl_v1_node_proto_msgTypes,
	}.Build()
	File_proto_qrl_v1_node_proto = out.File
	file_proto_qrl_v1_node_proto_goTypes = nil
	file_proto_qrl_v1_node_proto_depIdxs = nil
}
