// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrl/v1/ssz.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SSZContainer struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Version             Version                `protobuf:"varint,1,opt,name=version,proto3,enum=theqrl.qrl.v1.Version" json:"version,omitempty"`
	ExecutionOptimistic bool                   `protobuf:"varint,2,opt,name=execution_optimistic,json=executionOptimistic,proto3" json:"execution_optimistic,omitempty"`
	Data                []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Finalized           bool                   `protobuf:"varint,4,opt,name=finalized,proto3" json:"finalized,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SSZContainer) Reset() {
	*x = SSZContainer{}
	mi := &file_proto_qrl_v1_ssz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSZContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSZContainer) ProtoMessage() {}

func (x *SSZContainer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_ssz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSZContainer.ProtoReflect.Descriptor instead.
func (*SSZContainer) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_ssz_proto_rawDescGZIP(), []int{0}
}

func (x *SSZContainer) GetVersion() Version {
	if x != nil {
		return x.Version
	}
	return Version_ZOND
}

func (x *SSZContainer) GetExecutionOptimistic() bool {
	if x != nil {
		return x.ExecutionOptimistic
	}
	return false
}

func (x *SSZContainer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SSZContainer) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

var File_proto_qrl_v1_ssz_proto protoreflect.FileDescriptor

const file_proto_qrl_v1_ssz_proto_rawDesc = "" +
	"\n" +
	"\x16proto/qrl/v1/ssz.proto\x12\rtheqrl.qrl.v1\x1a\x1aproto/qrl/v1/version.proto\"\xa5\x01\n" +
	"\fSSZContainer\x120\n" +
	"\aversion\x18\x01 \x01(\x0e2\x16.theqrl.qrl.v1.VersionR\aversion\x121\n" +
	"\x14execution_optimistic\x18\x02 \x01(\bR\x13executionOptimistic\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1c\n" +
	"\tfinalized\x18\x04 \x01(\bR\tfinalizedBe\n" +
	"\x11org.theqrl.qrl.v1B\bSszProtoP\x01Z$github.com/theQRL/qrysm/proto/qrl/v1\xaa\x02\rTheQRL.QRL.V1\xca\x02\rTheQRL\\QRL\\v1b\x06proto3"

var (
	file_proto_qrl_v1_ssz_proto_rawDescOnce sync.Once
	file_proto_qrl_v1_ssz_proto_rawDescData []byte
)

func file_proto_qrl_v1_ssz_proto_rawDescGZIP() []byte {
	file_proto_qrl_v1_ssz_proto_rawDescOnce.Do(func() {
		file_proto_qrl_v1_ssz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_ssz_proto_rawDesc), len(file_proto_qrl_v1_ssz_proto_rawDesc)))
	})
	return file_proto_qrl_v1_ssz_proto_rawDescData
}

var file_proto_qrl_v1_ssz_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_qrl_v1_ssz_proto_goTypes = []any{
	(*SSZContainer)(nil), // 0: theqrl.qrl.v1.SSZContainer
	(Version)(0),         // 1: theqrl.qrl.v1.Version
}
var file_proto_qrl_v1_ssz_proto_depIdxs = []int32{
	1, // 0: theqrl.qrl.v1.SSZContainer.version:type_name -> theqrl.qrl.v1.Version
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_qrl_v1_ssz_proto_init() }
func file_proto_qrl_v1_ssz_proto_init() {
	if File_proto_qrl_v1_ssz_proto != nil {
		return
	}
	file_proto_qrl_v1_version_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_ssz_proto_rawDesc), len(file_proto_qrl_v1_ssz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrl_v1_ssz_proto_goTypes,
		DependencyIndexes: file_proto_qrl_v1_ssz_proto_depIdxs,
		MessageInfos:      file_proto_qrl_v1_ssz_proto_msgTypes,
	}.Build()
	File_proto_qrl_v1_ssz_proto = out.File
	file_proto_qrl_v1_ssz_proto_goTypes = nil
	file_proto_qrl_v1_ssz_proto_depIdxs = nil
}
