// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrl/v1/validator.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_go_bitfield "github.com/theQRL/go-bitfield"
	github_com_theQRL_qrysm_consensus_types_primitives "github.com/theQRL/qrysm/consensus-types/primitives"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidatorStatus int32

const (
	ValidatorStatus_PENDING_INITIALIZED ValidatorStatus = 0
	ValidatorStatus_PENDING_QUEUED      ValidatorStatus = 1
	ValidatorStatus_ACTIVE_ONGOING      ValidatorStatus = 2
	ValidatorStatus_ACTIVE_EXITING      ValidatorStatus = 3
	ValidatorStatus_ACTIVE_SLASHED      ValidatorStatus = 4
	ValidatorStatus_EXITED_UNSLASHED    ValidatorStatus = 5
	ValidatorStatus_EXITED_SLASHED      ValidatorStatus = 6
	ValidatorStatus_WITHDRAWAL_POSSIBLE ValidatorStatus = 7
	ValidatorStatus_WITHDRAWAL_DONE     ValidatorStatus = 8
	ValidatorStatus_ACTIVE              ValidatorStatus = 9
	ValidatorStatus_PENDING             ValidatorStatus = 10
	ValidatorStatus_EXITED              ValidatorStatus = 11
	ValidatorStatus_WITHDRAWAL          ValidatorStatus = 12
)

// Enum value maps for ValidatorStatus.
var (
	ValidatorStatus_name = map[int32]string{
		0:  "PENDING_INITIALIZED",
		1:  "PENDING_QUEUED",
		2:  "ACTIVE_ONGOING",
		3:  "ACTIVE_EXITING",
		4:  "ACTIVE_SLASHED",
		5:  "EXITED_UNSLASHED",
		6:  "EXITED_SLASHED",
		7:  "WITHDRAWAL_POSSIBLE",
		8:  "WITHDRAWAL_DONE",
		9:  "ACTIVE",
		10: "PENDING",
		11: "EXITED",
		12: "WITHDRAWAL",
	}
	ValidatorStatus_value = map[string]int32{
		"PENDING_INITIALIZED": 0,
		"PENDING_QUEUED":      1,
		"ACTIVE_ONGOING":      2,
		"ACTIVE_EXITING":      3,
		"ACTIVE_SLASHED":      4,
		"EXITED_UNSLASHED":    5,
		"EXITED_SLASHED":      6,
		"WITHDRAWAL_POSSIBLE": 7,
		"WITHDRAWAL_DONE":     8,
		"ACTIVE":              9,
		"PENDING":             10,
		"EXITED":              11,
		"WITHDRAWAL":          12,
	}
)

func (x ValidatorStatus) Enum() *ValidatorStatus {
	p := new(ValidatorStatus)
	*p = x
	return p
}

func (x ValidatorStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidatorStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_qrl_v1_validator_proto_enumTypes[0].Descriptor()
}

func (ValidatorStatus) Type() protoreflect.EnumType {
	return &file_proto_qrl_v1_validator_proto_enumTypes[0]
}

func (x ValidatorStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidatorStatus.Descriptor instead.
func (ValidatorStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_qrl_v1_validator_proto_rawDescGZIP(), []int{0}
}

type Validator struct {
	state                      protoimpl.MessageState                                   `protogen:"open.v1"`
	Pubkey                     []byte                                                   `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty" spec-name:"pubkey" ssz-size:"2592"`
	WithdrawalRecipient        []byte                                                   `protobuf:"bytes,2,opt,name=withdrawal_recipient,json=withdrawalRecipient,proto3" json:"withdrawal_recipient,omitempty" ssz-size:"64"`
	EffectiveBalance           uint64                                                   `protobuf:"varint,3,opt,name=effective_balance,json=effectiveBalance,proto3" json:"effective_balance,omitempty"`
	Slashed                    bool                                                     `protobuf:"varint,4,opt,name=slashed,proto3" json:"slashed,omitempty"`
	ActivationEligibilityEpoch github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,5,opt,name=activation_eligibility_epoch,json=activationEligibilityEpoch,proto3" json:"activation_eligibility_epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	ActivationEpoch            github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,6,opt,name=activation_epoch,json=activationEpoch,proto3" json:"activation_epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	ExitEpoch                  github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,7,opt,name=exit_epoch,json=exitEpoch,proto3" json:"exit_epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	WithdrawableEpoch          github_com_theQRL_qrysm_consensus_types_primitives.Epoch `protobuf:"varint,8,opt,name=withdrawable_epoch,json=withdrawableEpoch,proto3" json:"withdrawable_epoch,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Epoch"`
	RandaoCommitment           []byte                                                   `protobuf:"bytes,9,opt,name=randao_commitment,json=randaoCommitment,proto3" json:"randao_commitment,omitempty" ssz-size:"32"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Validator) Reset() {
	*x = Validator{}
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Validator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Validator) ProtoMessage() {}

func (x *Validator) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Validator.ProtoReflect.Descriptor instead.
func (*Validator) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_validator_proto_rawDescGZIP(), []int{0}
}

func (x *Validator) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *Validator) GetWithdrawalRecipient() []byte {
	if x != nil {
		return x.WithdrawalRecipient
	}
	return nil
}

func (x *Validator) GetEffectiveBalance() uint64 {
	if x != nil {
		return x.EffectiveBalance
	}
	return 0
}

func (x *Validator) GetSlashed() bool {
	if x != nil {
		return x.Slashed
	}
	return false
}

func (x *Validator) GetActivationEligibilityEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.ActivationEligibilityEpoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

func (x *Validator) GetActivationEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.ActivationEpoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

func (x *Validator) GetExitEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.ExitEpoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

func (x *Validator) GetWithdrawableEpoch() github_com_theQRL_qrysm_consensus_types_primitives.Epoch {
	if x != nil {
		return x.WithdrawableEpoch
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Epoch(0)
}

func (x *Validator) GetRandaoCommitment() []byte {
	if x != nil {
		return x.RandaoCommitment
	}
	return nil
}

type ProduceBlockRequest struct {
	state         protoimpl.MessageState                                  `protogen:"open.v1"`
	Slot          github_com_theQRL_qrysm_consensus_types_primitives.Slot `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	RandaoReveal  []byte                                                  `protobuf:"bytes,2,opt,name=randao_reveal,json=randaoReveal,proto3" json:"randao_reveal,omitempty" ssz-size:"32"`
	Graffiti      []byte                                                  `protobuf:"bytes,3,opt,name=graffiti,proto3,oneof" json:"graffiti,omitempty" ssz-size:"32"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceBlockRequest) Reset() {
	*x = ProduceBlockRequest{}
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceBlockRequest) ProtoMessage() {}

func (x *ProduceBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceBlockRequest.ProtoReflect.Descriptor instead.
func (*ProduceBlockRequest) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_validator_proto_rawDescGZIP(), []int{1}
}

func (x *ProduceBlockRequest) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *ProduceBlockRequest) GetRandaoReveal() []byte {
	if x != nil {
		return x.RandaoReveal
	}
	return nil
}

func (x *ProduceBlockRequest) GetGraffiti() []byte {
	if x != nil {
		return x.Graffiti
	}
	return nil
}

type ProduceBlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       Version                `protobuf:"varint,1,opt,name=version,proto3,enum=theqrl.qrl.v1.Version" json:"version,omitempty"`
	Data          *BeaconBlockContainer  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceBlockResponse) Reset() {
	*x = ProduceBlockResponse{}
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceBlockResponse) ProtoMessage() {}

func (x *ProduceBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceBlockResponse.ProtoReflect.Descriptor instead.
func (*ProduceBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_validator_proto_rawDescGZIP(), []int{2}
}

func (x *ProduceBlockResponse) GetVersion() Version {
	if x != nil {
		return x.Version
	}
	return Version_ZOND
}

func (x *ProduceBlockResponse) GetData() *BeaconBlockContainer {
	if x != nil {
		return x.Data
	}
	return nil
}

type ProduceBlindedBlockResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Version       Version                      `protobuf:"varint,1,opt,name=version,proto3,enum=theqrl.qrl.v1.Version" json:"version,omitempty"`
	Data          *BlindedBeaconBlockContainer `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceBlindedBlockResponse) Reset() {
	*x = ProduceBlindedBlockResponse{}
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceBlindedBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceBlindedBlockResponse) ProtoMessage() {}

func (x *ProduceBlindedBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceBlindedBlockResponse.ProtoReflect.Descriptor instead.
func (*ProduceBlindedBlockResponse) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_validator_proto_rawDescGZIP(), []int{3}
}

func (x *ProduceBlindedBlockResponse) GetVersion() Version {
	if x != nil {
		return x.Version
	}
	return Version_ZOND
}

func (x *ProduceBlindedBlockResponse) GetData() *BlindedBeaconBlockContainer {
	if x != nil {
		return x.Data
	}
	return nil
}

type SyncCommitteeContribution struct {
	state             protoimpl.MessageState                                  `protogen:"open.v1"`
	Slot              github_com_theQRL_qrysm_consensus_types_primitives.Slot `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.Slot"`
	BeaconBlockRoot   []byte                                                  `protobuf:"bytes,2,opt,name=beacon_block_root,json=beaconBlockRoot,proto3" json:"beacon_block_root,omitempty" ssz-size:"32"`
	SubcommitteeIndex uint64                                                  `protobuf:"varint,3,opt,name=subcommittee_index,json=subcommitteeIndex,proto3" json:"subcommittee_index,omitempty"`
	AggregationBits   github_com_theQRL_go_bitfield.Bitvector128              `protobuf:"bytes,4,opt,name=aggregation_bits,json=aggregationBits,proto3" json:"aggregation_bits,omitempty" cast-type:"github.com/theQRL/go-bitfield.Bitvector128" ssz-size:"16"`
	Signatures        [][]byte                                                `protobuf:"bytes,5,rep,name=signatures,proto3" json:"signatures,omitempty" ssz-max:"128" ssz-size:"?,4627"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncCommitteeContribution) Reset() {
	*x = SyncCommitteeContribution{}
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncCommitteeContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCommitteeContribution) ProtoMessage() {}

func (x *SyncCommitteeContribution) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCommitteeContribution.ProtoReflect.Descriptor instead.
func (*SyncCommitteeContribution) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_validator_proto_rawDescGZIP(), []int{4}
}

func (x *SyncCommitteeContribution) GetSlot() github_com_theQRL_qrysm_consensus_types_primitives.Slot {
	if x != nil {
		return x.Slot
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.Slot(0)
}

func (x *SyncCommitteeContribution) GetBeaconBlockRoot() []byte {
	if x != nil {
		return x.BeaconBlockRoot
	}
	return nil
}

func (x *SyncCommitteeContribution) GetSubcommitteeIndex() uint64 {
	if x != nil {
		return x.SubcommitteeIndex
	}
	return 0
}

func (x *SyncCommitteeContribution) GetAggregationBits() github_com_theQRL_go_bitfield.Bitvector128 {
	if x != nil {
		return x.AggregationBits
	}
	return github_com_theQRL_go_bitfield.Bitvector128(nil)
}

func (x *SyncCommitteeContribution) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type ContributionAndProof struct {
	state           protoimpl.MessageState                                            `protogen:"open.v1"`
	AggregatorIndex github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,1,opt,name=aggregator_index,json=aggregatorIndex,proto3" json:"aggregator_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	Contribution    *SyncCommitteeContribution                                        `protobuf:"bytes,2,opt,name=contribution,proto3" json:"contribution,omitempty"`
	SelectionProof  []byte                                                            `protobuf:"bytes,3,opt,name=selection_proof,json=selectionProof,proto3" json:"selection_proof,omitempty" ssz-size:"4627"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ContributionAndProof) Reset() {
	*x = ContributionAndProof{}
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContributionAndProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContributionAndProof) ProtoMessage() {}

func (x *ContributionAndProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContributionAndProof.ProtoReflect.Descriptor instead.
func (*ContributionAndProof) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_validator_proto_rawDescGZIP(), []int{5}
}

func (x *ContributionAndProof) GetAggregatorIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.AggregatorIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

func (x *ContributionAndProof) GetContribution() *SyncCommitteeContribution {
	if x != nil {
		return x.Contribution
	}
	return nil
}

func (x *ContributionAndProof) GetSelectionProof() []byte {
	if x != nil {
		return x.SelectionProof
	}
	return nil
}

type SignedContributionAndProof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ContributionAndProof  `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty" ssz-size:"4627"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedContributionAndProof) Reset() {
	*x = SignedContributionAndProof{}
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedContributionAndProof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedContributionAndProof) ProtoMessage() {}

func (x *SignedContributionAndProof) ProtoReflect() protoreflect.Message {
	mi := &file_proto_qrl_v1_validator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedContributionAndProof.ProtoReflect.Descriptor instead.
func (*SignedContributionAndProof) Descriptor() ([]byte, []int) {
	return file_proto_qrl_v1_validator_proto_rawDescGZIP(), []int{6}
}

func (x *SignedContributionAndProof) GetMessage() *ContributionAndProof {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SignedContributionAndProof) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_proto_qrl_v1_validator_proto protoreflect.FileDescriptor

const file_proto_qrl_v1_validator_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/qrl/v1/validator.proto\x12\rtheqrl.qrl.v1\x1a google/protobuf/descriptor.proto\x1a\x1bproto/qrl/ext/options.proto\x1a\x1fproto/qrl/v1/beacon_block.proto\x1a\x1aproto/qrl/v1/version.proto\"\xa1\x05\n" +
	"\tValidator\x12*\n" +
	"\x06pubkey\x18\x01 \x01(\fB\x12\x8a\xb5\x18\x042592\x9a\xb5\x18\x06pubkeyR\x06pubkey\x129\n" +
	"\x14withdrawal_recipient\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0264R\x13withdrawalRecipient\x12+\n" +
	"\x11effective_balance\x18\x03 \x01(\x04R\x10effectiveBalance\x12\x18\n" +
	"\aslashed\x18\x04 \x01(\bR\aslashed\x12~\n" +
	"\x1cactivation_eligibility_epoch\x18\x05 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x1aactivationEligibilityEpoch\x12g\n" +
	"\x10activation_epoch\x18\x06 \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x0factivationEpoch\x12[\n" +
	"\n" +
	"exit_epoch\x18\a \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\texitEpoch\x12k\n" +
	"\x12withdrawable_epoch\x18\b \x01(\x04B<\x82\xb5\x188github.com/theQRL/qrysm/consensus-types/primitives.EpochR\x11withdrawableEpoch\x123\n" +
	"\x11randao_commitment\x18\t \x01(\fB\x06\x8a\xb5\x18\x0232R\x10randaoCommitment\"\xc9\x01\n" +
	"\x13ProduceBlockRequest\x12O\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x12+\n" +
	"\rrandao_reveal\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\frandaoReveal\x12'\n" +
	"\bgraffiti\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232H\x00R\bgraffiti\x88\x01\x01B\v\n" +
	"\t_graffiti\"\x81\x01\n" +
	"\x14ProduceBlockResponse\x120\n" +
	"\aversion\x18\x01 \x01(\x0e2\x16.theqrl.qrl.v1.VersionR\aversion\x127\n" +
	"\x04data\x18\x02 \x01(\v2#.theqrl.qrl.v1.BeaconBlockContainerR\x04data\"\x8f\x01\n" +
	"\x1bProduceBlindedBlockResponse\x120\n" +
	"\aversion\x18\x01 \x01(\x0e2\x16.theqrl.qrl.v1.VersionR\aversion\x12>\n" +
	"\x04data\x18\x02 \x01(\v2*.theqrl.qrl.v1.BlindedBeaconBlockContainerR\x04data\"\xe3\x02\n" +
	"\x19SyncCommitteeContribution\x12O\n" +
	"\x04slot\x18\x01 \x01(\x04B;\x82\xb5\x187github.com/theQRL/qrysm/consensus-types/primitives.SlotR\x04slot\x122\n" +
	"\x11beacon_block_root\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\x0fbeaconBlockRoot\x12-\n" +
	"\x12subcommittee_index\x18\x03 \x01(\x04R\x11subcommitteeIndex\x12_\n" +
	"\x10aggregation_bits\x18\x04 \x01(\fB4\x82\xb5\x18*github.com/theQRL/go-bitfield.Bitvector128\x8a\xb5\x18\x0216R\x0faggregationBits\x121\n" +
	"\n" +
	"signatures\x18\x05 \x03(\fB\x11\x8a\xb5\x18\x06?,4627\x92\xb5\x18\x03128R\n" +
	"signatures\"\x89\x02\n" +
	"\x14ContributionAndProof\x12p\n" +
	"\x10aggregator_index\x18\x01 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\x0faggregatorIndex\x12L\n" +
	"\fcontribution\x18\x02 \x01(\v2(.theqrl.qrl.v1.SyncCommitteeContributionR\fcontribution\x121\n" +
	"\x0fselection_proof\x18\x03 \x01(\fB\b\x8a\xb5\x18\x044627R\x0eselectionProof\"\x83\x01\n" +
	"\x1aSignedContributionAndProof\x12=\n" +
	"\amessage\x18\x01 \x01(\v2#.theqrl.qrl.v1.ContributionAndProofR\amessage\x12&\n" +
	"\tsignature\x18\x04 \x01(\fB\b\x8a\xb5\x18\x044627R\tsignature*\x87\x02\n" +
	"\x0fValidatorStatus\x12\x17\n" +
	"\x13PENDING_INITIALIZED\x10\x00\x12\x12\n" +
	"\x0ePENDING_QUEUED\x10\x01\x12\x12\n" +
	"\x0eACTIVE_ONGOING\x10\x02\x12\x12\n" +
	"\x0eACTIVE_EXITING\x10\x03\x12\x12\n" +
	"\x0eACTIVE_SLASHED\x10\x04\x12\x14\n" +
	"\x10EXITED_UNSLASHED\x10\x05\x12\x12\n" +
	"\x0eEXITED_SLASHED\x10\x06\x12\x17\n" +
	"\x13WITHDRAWAL_POSSIBLE\x10\a\x12\x13\n" +
	"\x0fWITHDRAWAL_DONE\x10\b\x12\n" +
	"\n" +
	"\x06ACTIVE\x10\t\x12\v\n" +
	"\aPENDING\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06EXITED\x10\v\x12\x0e\n" +
	"\n" +
	"WITHDRAWAL\x10\fBk\n" +
	"\x11org.theqrl.qrl.v1B\x0eValidatorProtoP\x01Z$github.com/theQRL/qrysm/proto/qrl/v1\xaa\x02\rTheQRL.QRL.V1\xca\x02\rTheQRL\\QRL\\v1b\x06proto3"

var (
	file_proto_qrl_v1_validator_proto_rawDescOnce sync.Once
	file_proto_qrl_v1_validator_proto_rawDescData []byte
)

func file_proto_qrl_v1_validator_proto_rawDescGZIP() []byte {
	file_proto_qrl_v1_validator_proto_rawDescOnce.Do(func() {
		file_proto_qrl_v1_validator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_validator_proto_rawDesc), len(file_proto_qrl_v1_validator_proto_rawDesc)))
	})
	return file_proto_qrl_v1_validator_proto_rawDescData
}

var file_proto_qrl_v1_validator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_qrl_v1_validator_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_qrl_v1_validator_proto_goTypes = []any{
	(ValidatorStatus)(0),                // 0: theqrl.qrl.v1.ValidatorStatus
	(*Validator)(nil),                   // 1: theqrl.qrl.v1.Validator
	(*ProduceBlockRequest)(nil),         // 2: theqrl.qrl.v1.ProduceBlockRequest
	(*ProduceBlockResponse)(nil),        // 3: theqrl.qrl.v1.ProduceBlockResponse
	(*ProduceBlindedBlockResponse)(nil), // 4: theqrl.qrl.v1.ProduceBlindedBlockResponse
	(*SyncCommitteeContribution)(nil),   // 5: theqrl.qrl.v1.SyncCommitteeContribution
	(*ContributionAndProof)(nil),        // 6: theqrl.qrl.v1.ContributionAndProof
	(*SignedContributionAndProof)(nil),  // 7: theqrl.qrl.v1.SignedContributionAndProof
	(Version)(0),                        // 8: theqrl.qrl.v1.Version
	(*BeaconBlockContainer)(nil),        // 9: theqrl.qrl.v1.BeaconBlockContainer
	(*BlindedBeaconBlockContainer)(nil), // 10: theqrl.qrl.v1.BlindedBeaconBlockContainer
}
var file_proto_qrl_v1_validator_proto_depIdxs = []int32{
	8,  // 0: theqrl.qrl.v1.ProduceBlockResponse.version:type_name -> theqrl.qrl.v1.Version
	9,  // 1: theqrl.qrl.v1.ProduceBlockResponse.data:type_name -> theqrl.qrl.v1.BeaconBlockContainer
	8,  // 2: theqrl.qrl.v1.ProduceBlindedBlockResponse.version:type_name -> theqrl.qrl.v1.Version
	10, // 3: theqrl.qrl.v1.ProduceBlindedBlockResponse.data:type_name -> theqrl.qrl.v1.BlindedBeaconBlockContainer
	5,  // 4: theqrl.qrl.v1.ContributionAndProof.contribution:type_name -> theqrl.qrl.v1.SyncCommitteeContribution
	6,  // 5: theqrl.qrl.v1.SignedContributionAndProof.message:type_name -> theqrl.qrl.v1.ContributionAndProof
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_qrl_v1_validator_proto_init() }
func file_proto_qrl_v1_validator_proto_init() {
	if File_proto_qrl_v1_validator_proto != nil {
		return
	}
	file_proto_qrl_v1_beacon_block_proto_init()
	file_proto_qrl_v1_version_proto_init()
	file_proto_qrl_v1_validator_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_validator_proto_rawDesc), len(file_proto_qrl_v1_validator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrl_v1_validator_proto_goTypes,
		DependencyIndexes: file_proto_qrl_v1_validator_proto_depIdxs,
		EnumInfos:         file_proto_qrl_v1_validator_proto_enumTypes,
		MessageInfos:      file_proto_qrl_v1_validator_proto_msgTypes,
	}.Build()
	File_proto_qrl_v1_validator_proto = out.File
	file_proto_qrl_v1_validator_proto_goTypes = nil
	file_proto_qrl_v1_validator_proto_depIdxs = nil
}
