// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/qrl/v1/version.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Version int32

const (
	Version_ZOND Version = 0
)

// Enum value maps for Version.
var (
	Version_name = map[int32]string{
		0: "ZOND",
	}
	Version_value = map[string]int32{
		"ZOND": 0,
	}
)

func (x Version) Enum() *Version {
	p := new(Version)
	*p = x
	return p
}

func (x Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Version) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_qrl_v1_version_proto_enumTypes[0].Descriptor()
}

func (Version) Type() protoreflect.EnumType {
	return &file_proto_qrl_v1_version_proto_enumTypes[0]
}

func (x Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Version.Descriptor instead.
func (Version) EnumDescriptor() ([]byte, []int) {
	return file_proto_qrl_v1_version_proto_rawDescGZIP(), []int{0}
}

var File_proto_qrl_v1_version_proto protoreflect.FileDescriptor

const file_proto_qrl_v1_version_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/qrl/v1/version.proto\x12\rtheqrl.qrl.v1*\x13\n" +
	"\aVersion\x12\b\n" +
	"\x04ZOND\x10\x00Bi\n" +
	"\x11org.theqrl.qrl.v1B\fVersionProtoP\x01Z$github.com/theQRL/qrysm/proto/qrl/v1\xaa\x02\rTheQRL.QRL.V1\xca\x02\rTheQRL\\QRL\\v1b\x06proto3"

var (
	file_proto_qrl_v1_version_proto_rawDescOnce sync.Once
	file_proto_qrl_v1_version_proto_rawDescData []byte
)

func file_proto_qrl_v1_version_proto_rawDescGZIP() []byte {
	file_proto_qrl_v1_version_proto_rawDescOnce.Do(func() {
		file_proto_qrl_v1_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_version_proto_rawDesc), len(file_proto_qrl_v1_version_proto_rawDesc)))
	})
	return file_proto_qrl_v1_version_proto_rawDescData
}

var file_proto_qrl_v1_version_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_qrl_v1_version_proto_goTypes = []any{
	(Version)(0), // 0: theqrl.qrl.v1.Version
}
var file_proto_qrl_v1_version_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_qrl_v1_version_proto_init() }
func file_proto_qrl_v1_version_proto_init() {
	if File_proto_qrl_v1_version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_qrl_v1_version_proto_rawDesc), len(file_proto_qrl_v1_version_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_qrl_v1_version_proto_goTypes,
		DependencyIndexes: file_proto_qrl_v1_version_proto_depIdxs,
		EnumInfos:         file_proto_qrl_v1_version_proto_enumTypes,
	}.Build()
	File_proto_qrl_v1_version_proto = out.File
	file_proto_qrl_v1_version_proto_goTypes = nil
	file_proto_qrl_v1_version_proto_depIdxs = nil
}
