// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: proto/engine/v1/execution_engine.proto

package enginev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	github_com_theQRL_qrysm_consensus_types_primitives "github.com/theQRL/qrysm/consensus-types/primitives"
	_ "github.com/theQRL/qrysm/proto/qrl/ext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadStatus_Status int32

const (
	PayloadStatus_UNKNOWN            PayloadStatus_Status = 0
	PayloadStatus_VALID              PayloadStatus_Status = 1
	PayloadStatus_INVALID            PayloadStatus_Status = 2
	PayloadStatus_SYNCING            PayloadStatus_Status = 3
	PayloadStatus_ACCEPTED           PayloadStatus_Status = 4
	PayloadStatus_INVALID_BLOCK_HASH PayloadStatus_Status = 5
)

// Enum value maps for PayloadStatus_Status.
var (
	PayloadStatus_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "VALID",
		2: "INVALID",
		3: "SYNCING",
		4: "ACCEPTED",
		5: "INVALID_BLOCK_HASH",
	}
	PayloadStatus_Status_value = map[string]int32{
		"UNKNOWN":            0,
		"VALID":              1,
		"INVALID":            2,
		"SYNCING":            3,
		"ACCEPTED":           4,
		"INVALID_BLOCK_HASH": 5,
	}
)

func (x PayloadStatus_Status) Enum() *PayloadStatus_Status {
	p := new(PayloadStatus_Status)
	*p = x
	return p
}

func (x PayloadStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_engine_v1_execution_engine_proto_enumTypes[0].Descriptor()
}

func (PayloadStatus_Status) Type() protoreflect.EnumType {
	return &file_proto_engine_v1_execution_engine_proto_enumTypes[0]
}

func (x PayloadStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadStatus_Status.Descriptor instead.
func (PayloadStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{5, 0}
}

type ExecutionPayloadBodyV1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  [][]byte               `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Withdrawals   []*Withdrawal          `protobuf:"bytes,2,rep,name=withdrawals,proto3" json:"withdrawals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPayloadBodyV1) Reset() {
	*x = ExecutionPayloadBodyV1{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadBodyV1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadBodyV1) ProtoMessage() {}

func (x *ExecutionPayloadBodyV1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadBodyV1.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadBodyV1) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionPayloadBodyV1) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ExecutionPayloadBodyV1) GetWithdrawals() []*Withdrawal {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

type ExecutionPayloadZond struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentHash    []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty" ssz-size:"32"`
	FeeRecipient  []byte                 `protobuf:"bytes,2,opt,name=fee_recipient,json=feeRecipient,proto3" json:"fee_recipient,omitempty" ssz-size:"64"`
	StateRoot     []byte                 `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty" ssz-size:"32"`
	ReceiptsRoot  []byte                 `protobuf:"bytes,4,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty" ssz-size:"32"`
	LogsBloom     []byte                 `protobuf:"bytes,5,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty" ssz-size:"256"`
	PrevRandao    []byte                 `protobuf:"bytes,6,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty" ssz-size:"32"`
	BlockNumber   uint64                 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasLimit      uint64                 `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed       uint64                 `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData     []byte                 `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty" ssz-max:"32"`
	BaseFeePerGas []byte                 `protobuf:"bytes,12,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty" ssz-size:"32"`
	BlockHash     []byte                 `protobuf:"bytes,13,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty" ssz-size:"32"`
	Transactions  [][]byte               `protobuf:"bytes,14,rep,name=transactions,proto3" json:"transactions,omitempty" ssz-max:"1048576,1073741824" ssz-size:"?,?"`
	Withdrawals   []*Withdrawal          `protobuf:"bytes,15,rep,name=withdrawals,proto3" json:"withdrawals,omitempty" ssz-max:"16"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPayloadZond) Reset() {
	*x = ExecutionPayloadZond{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadZond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadZond) ProtoMessage() {}

func (x *ExecutionPayloadZond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadZond.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadZond) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionPayloadZond) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionPayloadZond) GetFeeRecipient() []byte {
	if x != nil {
		return x.FeeRecipient
	}
	return nil
}

func (x *ExecutionPayloadZond) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ExecutionPayloadZond) GetReceiptsRoot() []byte {
	if x != nil {
		return x.ReceiptsRoot
	}
	return nil
}

func (x *ExecutionPayloadZond) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *ExecutionPayloadZond) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *ExecutionPayloadZond) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionPayloadZond) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ExecutionPayloadZond) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecutionPayloadZond) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecutionPayloadZond) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *ExecutionPayloadZond) GetBaseFeePerGas() []byte {
	if x != nil {
		return x.BaseFeePerGas
	}
	return nil
}

func (x *ExecutionPayloadZond) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ExecutionPayloadZond) GetTransactions() [][]byte {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ExecutionPayloadZond) GetWithdrawals() []*Withdrawal {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

type ExecutionPayloadZondWithValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       *ExecutionPayloadZond  `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPayloadZondWithValue) Reset() {
	*x = ExecutionPayloadZondWithValue{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadZondWithValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadZondWithValue) ProtoMessage() {}

func (x *ExecutionPayloadZondWithValue) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadZondWithValue.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadZondWithValue) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionPayloadZondWithValue) GetPayload() *ExecutionPayloadZond {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecutionPayloadZondWithValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ExecutionPayloadHeaderZond struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ParentHash       []byte                 `protobuf:"bytes,1,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty" ssz-size:"32"`
	FeeRecipient     []byte                 `protobuf:"bytes,2,opt,name=fee_recipient,json=feeRecipient,proto3" json:"fee_recipient,omitempty" ssz-size:"64"`
	StateRoot        []byte                 `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty" ssz-size:"32"`
	ReceiptsRoot     []byte                 `protobuf:"bytes,4,opt,name=receipts_root,json=receiptsRoot,proto3" json:"receipts_root,omitempty" ssz-size:"32"`
	LogsBloom        []byte                 `protobuf:"bytes,5,opt,name=logs_bloom,json=logsBloom,proto3" json:"logs_bloom,omitempty" ssz-size:"256"`
	PrevRandao       []byte                 `protobuf:"bytes,6,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty" ssz-size:"32"`
	BlockNumber      uint64                 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	GasLimit         uint64                 `protobuf:"varint,8,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasUsed          uint64                 `protobuf:"varint,9,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	Timestamp        uint64                 `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ExtraData        []byte                 `protobuf:"bytes,11,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty" ssz-max:"32"`
	BaseFeePerGas    []byte                 `protobuf:"bytes,12,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty" ssz-size:"32"`
	BlockHash        []byte                 `protobuf:"bytes,13,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty" ssz-size:"32"`
	TransactionsRoot []byte                 `protobuf:"bytes,14,opt,name=transactions_root,json=transactionsRoot,proto3" json:"transactions_root,omitempty" ssz-size:"32"`
	WithdrawalsRoot  []byte                 `protobuf:"bytes,15,opt,name=withdrawals_root,json=withdrawalsRoot,proto3" json:"withdrawals_root,omitempty" ssz-size:"32"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionPayloadHeaderZond) Reset() {
	*x = ExecutionPayloadHeaderZond{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPayloadHeaderZond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPayloadHeaderZond) ProtoMessage() {}

func (x *ExecutionPayloadHeaderZond) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPayloadHeaderZond.ProtoReflect.Descriptor instead.
func (*ExecutionPayloadHeaderZond) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionPayloadHeaderZond) GetParentHash() []byte {
	if x != nil {
		return x.ParentHash
	}
	return nil
}

func (x *ExecutionPayloadHeaderZond) GetFeeRecipient() []byte {
	if x != nil {
		return x.FeeRecipient
	}
	return nil
}

func (x *ExecutionPayloadHeaderZond) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *ExecutionPayloadHeaderZond) GetReceiptsRoot() []byte {
	if x != nil {
		return x.ReceiptsRoot
	}
	return nil
}

func (x *ExecutionPayloadHeaderZond) GetLogsBloom() []byte {
	if x != nil {
		return x.LogsBloom
	}
	return nil
}

func (x *ExecutionPayloadHeaderZond) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *ExecutionPayloadHeaderZond) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ExecutionPayloadHeaderZond) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *ExecutionPayloadHeaderZond) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ExecutionPayloadHeaderZond) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecutionPayloadHeaderZond) GetExtraData() []byte {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *ExecutionPayloadHeaderZond) GetBaseFeePerGas() []byte {
	if x != nil {
		return x.BaseFeePerGas
	}
	return nil
}

func (x *ExecutionPayloadHeaderZond) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *ExecutionPayloadHeaderZond) GetTransactionsRoot() []byte {
	if x != nil {
		return x.TransactionsRoot
	}
	return nil
}

func (x *ExecutionPayloadHeaderZond) GetWithdrawalsRoot() []byte {
	if x != nil {
		return x.WithdrawalsRoot
	}
	return nil
}

type PayloadAttributesV2 struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Timestamp             uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PrevRandao            []byte                 `protobuf:"bytes,2,opt,name=prev_randao,json=prevRandao,proto3" json:"prev_randao,omitempty" ssz-size:"32"`
	SuggestedFeeRecipient []byte                 `protobuf:"bytes,3,opt,name=suggested_fee_recipient,json=suggestedFeeRecipient,proto3" json:"suggested_fee_recipient,omitempty" ssz-size:"64"`
	Withdrawals           []*Withdrawal          `protobuf:"bytes,4,rep,name=withdrawals,proto3" json:"withdrawals,omitempty" ssz-max:"16"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PayloadAttributesV2) Reset() {
	*x = PayloadAttributesV2{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadAttributesV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadAttributesV2) ProtoMessage() {}

func (x *PayloadAttributesV2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadAttributesV2.ProtoReflect.Descriptor instead.
func (*PayloadAttributesV2) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{4}
}

func (x *PayloadAttributesV2) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PayloadAttributesV2) GetPrevRandao() []byte {
	if x != nil {
		return x.PrevRandao
	}
	return nil
}

func (x *PayloadAttributesV2) GetSuggestedFeeRecipient() []byte {
	if x != nil {
		return x.SuggestedFeeRecipient
	}
	return nil
}

func (x *PayloadAttributesV2) GetWithdrawals() []*Withdrawal {
	if x != nil {
		return x.Withdrawals
	}
	return nil
}

type PayloadStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          PayloadStatus_Status   `protobuf:"varint,1,opt,name=status,proto3,enum=theqrl.engine.v1.PayloadStatus_Status" json:"status,omitempty"`
	LatestValidHash []byte                 `protobuf:"bytes,2,opt,name=latest_valid_hash,json=latestValidHash,proto3" json:"latest_valid_hash,omitempty" ssz-size:"32"`
	ValidationError string                 `protobuf:"bytes,3,opt,name=validation_error,json=validationError,proto3" json:"validation_error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayloadStatus) Reset() {
	*x = PayloadStatus{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadStatus) ProtoMessage() {}

func (x *PayloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadStatus.ProtoReflect.Descriptor instead.
func (*PayloadStatus) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{5}
}

func (x *PayloadStatus) GetStatus() PayloadStatus_Status {
	if x != nil {
		return x.Status
	}
	return PayloadStatus_UNKNOWN
}

func (x *PayloadStatus) GetLatestValidHash() []byte {
	if x != nil {
		return x.LatestValidHash
	}
	return nil
}

func (x *PayloadStatus) GetValidationError() string {
	if x != nil {
		return x.ValidationError
	}
	return ""
}

type ForkchoiceState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HeadBlockHash      []byte                 `protobuf:"bytes,1,opt,name=head_block_hash,json=headBlockHash,proto3" json:"head_block_hash,omitempty" ssz-size:"32"`
	SafeBlockHash      []byte                 `protobuf:"bytes,2,opt,name=safe_block_hash,json=safeBlockHash,proto3" json:"safe_block_hash,omitempty" ssz-size:"32"`
	FinalizedBlockHash []byte                 `protobuf:"bytes,3,opt,name=finalized_block_hash,json=finalizedBlockHash,proto3" json:"finalized_block_hash,omitempty" ssz-size:"32"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ForkchoiceState) Reset() {
	*x = ForkchoiceState{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForkchoiceState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForkchoiceState) ProtoMessage() {}

func (x *ForkchoiceState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForkchoiceState.ProtoReflect.Descriptor instead.
func (*ForkchoiceState) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{6}
}

func (x *ForkchoiceState) GetHeadBlockHash() []byte {
	if x != nil {
		return x.HeadBlockHash
	}
	return nil
}

func (x *ForkchoiceState) GetSafeBlockHash() []byte {
	if x != nil {
		return x.SafeBlockHash
	}
	return nil
}

func (x *ForkchoiceState) GetFinalizedBlockHash() []byte {
	if x != nil {
		return x.FinalizedBlockHash
	}
	return nil
}

type Withdrawal struct {
	state          protoimpl.MessageState                                            `protogen:"open.v1"`
	Index          uint64                                                            `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ValidatorIndex github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex `protobuf:"varint,2,opt,name=validator_index,json=validatorIndex,proto3" json:"validator_index,omitempty" cast-type:"github.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndex"`
	Address        []byte                                                            `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty" ssz-size:"64"`
	Amount         uint64                                                            `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Withdrawal) Reset() {
	*x = Withdrawal{}
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Withdrawal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Withdrawal) ProtoMessage() {}

func (x *Withdrawal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_engine_v1_execution_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Withdrawal.ProtoReflect.Descriptor instead.
func (*Withdrawal) Descriptor() ([]byte, []int) {
	return file_proto_engine_v1_execution_engine_proto_rawDescGZIP(), []int{7}
}

func (x *Withdrawal) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Withdrawal) GetValidatorIndex() github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex {
	if x != nil {
		return x.ValidatorIndex
	}
	return github_com_theQRL_qrysm_consensus_types_primitives.ValidatorIndex(0)
}

func (x *Withdrawal) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Withdrawal) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_proto_engine_v1_execution_engine_proto protoreflect.FileDescriptor

const file_proto_engine_v1_execution_engine_proto_rawDesc = "" +
	"\n" +
	"&proto/engine/v1/execution_engine.proto\x12\x10theqrl.engine.v1\x1a\x1bproto/qrl/ext/options.proto\"|\n" +
	"\x16ExecutionPayloadBodyV1\x12\"\n" +
	"\ftransactions\x18\x01 \x03(\fR\ftransactions\x12>\n" +
	"\vwithdrawals\x18\x02 \x03(\v2\x1c.theqrl.engine.v1.WithdrawalR\vwithdrawals\"\x94\x05\n" +
	"\x14ExecutionPayloadZond\x12'\n" +
	"\vparent_hash\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"parentHash\x12+\n" +
	"\rfee_recipient\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0264R\ffeeRecipient\x12%\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\tstateRoot\x12+\n" +
	"\rreceipts_root\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\freceiptsRoot\x12&\n" +
	"\n" +
	"logs_bloom\x18\x05 \x01(\fB\a\x8a\xb5\x18\x03256R\tlogsBloom\x12'\n" +
	"\vprev_randao\x18\x06 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"prevRandao\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12\x1b\n" +
	"\tgas_limit\x18\b \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\t \x01(\x04R\agasUsed\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x04R\ttimestamp\x12%\n" +
	"\n" +
	"extra_data\x18\v \x01(\fB\x06\x92\xb5\x18\x0232R\textraData\x12/\n" +
	"\x10base_fee_per_gas\x18\f \x01(\fB\x06\x8a\xb5\x18\x0232R\rbaseFeePerGas\x12%\n" +
	"\n" +
	"block_hash\x18\r \x01(\fB\x06\x8a\xb5\x18\x0232R\tblockHash\x12A\n" +
	"\ftransactions\x18\x0e \x03(\fB\x1d\x8a\xb5\x18\x03?,?\x92\xb5\x18\x121048576,1073741824R\ftransactions\x12F\n" +
	"\vwithdrawals\x18\x0f \x03(\v2\x1c.theqrl.engine.v1.WithdrawalB\x06\x92\xb5\x18\x0216R\vwithdrawals\"w\n" +
	"\x1dExecutionPayloadZondWithValue\x12@\n" +
	"\apayload\x18\x01 \x01(\v2&.theqrl.engine.v1.ExecutionPayloadZondR\apayload\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xf7\x04\n" +
	"\x1aExecutionPayloadHeaderZond\x12'\n" +
	"\vparent_hash\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"parentHash\x12+\n" +
	"\rfee_recipient\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0264R\ffeeRecipient\x12%\n" +
	"\n" +
	"state_root\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\tstateRoot\x12+\n" +
	"\rreceipts_root\x18\x04 \x01(\fB\x06\x8a\xb5\x18\x0232R\freceiptsRoot\x12&\n" +
	"\n" +
	"logs_bloom\x18\x05 \x01(\fB\a\x8a\xb5\x18\x03256R\tlogsBloom\x12'\n" +
	"\vprev_randao\x18\x06 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"prevRandao\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12\x1b\n" +
	"\tgas_limit\x18\b \x01(\x04R\bgasLimit\x12\x19\n" +
	"\bgas_used\x18\t \x01(\x04R\agasUsed\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x04R\ttimestamp\x12%\n" +
	"\n" +
	"extra_data\x18\v \x01(\fB\x06\x92\xb5\x18\x0232R\textraData\x12/\n" +
	"\x10base_fee_per_gas\x18\f \x01(\fB\x06\x8a\xb5\x18\x0232R\rbaseFeePerGas\x12%\n" +
	"\n" +
	"block_hash\x18\r \x01(\fB\x06\x8a\xb5\x18\x0232R\tblockHash\x123\n" +
	"\x11transactions_root\x18\x0e \x01(\fB\x06\x8a\xb5\x18\x0232R\x10transactionsRoot\x121\n" +
	"\x10withdrawals_root\x18\x0f \x01(\fB\x06\x8a\xb5\x18\x0232R\x0fwithdrawalsRoot\"\xe4\x01\n" +
	"\x13PayloadAttributesV2\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12'\n" +
	"\vprev_randao\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\n" +
	"prevRandao\x12>\n" +
	"\x17suggested_fee_recipient\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0264R\x15suggestedFeeRecipient\x12F\n" +
	"\vwithdrawals\x18\x04 \x03(\v2\x1c.theqrl.engine.v1.WithdrawalB\x06\x92\xb5\x18\x0216R\vwithdrawals\"\x90\x02\n" +
	"\rPayloadStatus\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.theqrl.engine.v1.PayloadStatus.StatusR\x06status\x122\n" +
	"\x11latest_valid_hash\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\x0flatestValidHash\x12)\n" +
	"\x10validation_error\x18\x03 \x01(\tR\x0fvalidationError\"`\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05VALID\x10\x01\x12\v\n" +
	"\aINVALID\x10\x02\x12\v\n" +
	"\aSYNCING\x10\x03\x12\f\n" +
	"\bACCEPTED\x10\x04\x12\x16\n" +
	"\x12INVALID_BLOCK_HASH\x10\x05\"\xab\x01\n" +
	"\x0fForkchoiceState\x12.\n" +
	"\x0fhead_block_hash\x18\x01 \x01(\fB\x06\x8a\xb5\x18\x0232R\rheadBlockHash\x12.\n" +
	"\x0fsafe_block_hash\x18\x02 \x01(\fB\x06\x8a\xb5\x18\x0232R\rsafeBlockHash\x128\n" +
	"\x14finalized_block_hash\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0232R\x12finalizedBlockHash\"\xcc\x01\n" +
	"\n" +
	"Withdrawal\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x04R\x05index\x12n\n" +
	"\x0fvalidator_index\x18\x02 \x01(\x04BE\x82\xb5\x18Agithub.com/theQRL/qrysm/consensus-types/primitives.ValidatorIndexR\x0evalidatorIndex\x12 \n" +
	"\aaddress\x18\x03 \x01(\fB\x06\x8a\xb5\x18\x0264R\aaddress\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x04R\x06amountB\x86\x01\n" +
	"\x14org.theqrl.engine.v1B\x14ExecutionEngineProtoP\x01Z0github.com/theQRL/qrysm/proto/engine/v1;enginev1\xaa\x02\x10TheQRL.Engine.V1\xca\x02\x10TheQRL\\Engine\\v1b\x06proto3"

var (
	file_proto_engine_v1_execution_engine_proto_rawDescOnce sync.Once
	file_proto_engine_v1_execution_engine_proto_rawDescData []byte
)

func file_proto_engine_v1_execution_engine_proto_rawDescGZIP() []byte {
	file_proto_engine_v1_execution_engine_proto_rawDescOnce.Do(func() {
		file_proto_engine_v1_execution_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_engine_v1_execution_engine_proto_rawDesc), len(file_proto_engine_v1_execution_engine_proto_rawDesc)))
	})
	return file_proto_engine_v1_execution_engine_proto_rawDescData
}

var file_proto_engine_v1_execution_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_engine_v1_execution_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_engine_v1_execution_engine_proto_goTypes = []any{
	(PayloadStatus_Status)(0),             // 0: theqrl.engine.v1.PayloadStatus.Status
	(*ExecutionPayloadBodyV1)(nil),        // 1: theqrl.engine.v1.ExecutionPayloadBodyV1
	(*ExecutionPayloadZond)(nil),          // 2: theqrl.engine.v1.ExecutionPayloadZond
	(*ExecutionPayloadZondWithValue)(nil), // 3: theqrl.engine.v1.ExecutionPayloadZondWithValue
	(*ExecutionPayloadHeaderZond)(nil),    // 4: theqrl.engine.v1.ExecutionPayloadHeaderZond
	(*PayloadAttributesV2)(nil),           // 5: theqrl.engine.v1.PayloadAttributesV2
	(*PayloadStatus)(nil),                 // 6: theqrl.engine.v1.PayloadStatus
	(*ForkchoiceState)(nil),               // 7: theqrl.engine.v1.ForkchoiceState
	(*Withdrawal)(nil),                    // 8: theqrl.engine.v1.Withdrawal
}
var file_proto_engine_v1_execution_engine_proto_depIdxs = []int32{
	8, // 0: theqrl.engine.v1.ExecutionPayloadBodyV1.withdrawals:type_name -> theqrl.engine.v1.Withdrawal
	8, // 1: theqrl.engine.v1.ExecutionPayloadZond.withdrawals:type_name -> theqrl.engine.v1.Withdrawal
	2, // 2: theqrl.engine.v1.ExecutionPayloadZondWithValue.payload:type_name -> theqrl.engine.v1.ExecutionPayloadZond
	8, // 3: theqrl.engine.v1.PayloadAttributesV2.withdrawals:type_name -> theqrl.engine.v1.Withdrawal
	0, // 4: theqrl.engine.v1.PayloadStatus.status:type_name -> theqrl.engine.v1.PayloadStatus.Status
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_engine_v1_execution_engine_proto_init() }
func file_proto_engine_v1_execution_engine_proto_init() {
	if File_proto_engine_v1_execution_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_engine_v1_execution_engine_proto_rawDesc), len(file_proto_engine_v1_execution_engine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_engine_v1_execution_engine_proto_goTypes,
		DependencyIndexes: file_proto_engine_v1_execution_engine_proto_depIdxs,
		EnumInfos:         file_proto_engine_v1_execution_engine_proto_enumTypes,
		MessageInfos:      file_proto_engine_v1_execution_engine_proto_msgTypes,
	}.Build()
	File_proto_engine_v1_execution_engine_proto = out.File
	file_proto_engine_v1_execution_engine_proto_goTypes = nil
	file_proto_engine_v1_execution_engine_proto_depIdxs = nil
}
