name: Publish docker images for both AMD64 & ARM64

on:
  push:
    branches:
      - main

jobs:
  publish-docker:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show System Info
        run: |
          uname -a
          lscpu

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential

      - name: Install Bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64"
          mkdir -p bin
          mv bazelisk-linux-amd64 bin/bazel
          chmod +x bin/bazel
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Publish Docker Image
        run: |
          export PATH="$(pwd)/bin:$PATH"
          chmod +x ./hack/build_and_upload_docker.sh
          ./hack/build_and_upload_docker.sh latest
